<?php
/* これは文字化け防止のための日本語文字列です。
   このソースファイルは Shift_JIS で保存されています。
   Above is a Japanese strings to avoid charset mis-understanding.
   This source file is saved with Shift_JIS.

   ***** DO NOT EDIT THIS FILE WITH WORDPRESS ADMIN PANEL *****
*/

/* ==================================================
 *   KtaiService_EZweb class
   ================================================== */

class KtaiService_EZweb extends KtaiServices {
	static public $networks;
	static public $device_IDs;
	static public $pictograms;

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->theme = ks_option('ks_theme_ezweb');
	$this->operator = 'KDDI';
	$this->image_pictograms = false;
	$this->use_redir = true;
	$this->show_plugin_icon = false;
	$this->pcview_enabled = false;
	$this->sub_ID_available = true;
	if ( $this->sub_ID_available && isset($_SERVER['HTTP_X_UP_SUBNO']) ) {
		$this->sub_ID = stripslashes($_SERVER['HTTP_X_UP_SUBNO']);
	} else {
		$this->sub_ID = NULL;
	}
	$this->cookie_available = true;
	$this->ext_css_available = false;
	$this->available_js_version = false;
	if (isset($_SERVER['X-UP-DEVCAP-SCREENPIXELS'])) {
		list($this->screen_width, $this->screen_height) = array_map('intval', explode(',', $_SERVER['X-UP-DEVCAP-SCREENPIXELS']));
	}
	$this->charset = 'SJIS-win';
	$this->mime_type = 'text/html';
	$this->preamble = '<?xml version="1.0" encoding="__CHARSET__"?>
<!DOCTYPE html PUBLIC "-//OPENWAVE//DTD XHTML 1.0//EN" "http://www.openwave.com/DTD/xhtml-basic.dtd">'; // <?php /* syntax hilighting fix */
	$this->require_id_msg = "ERROR: Please configure to send you EZ number (subscriber ID).\nGo au one top &gt; au customer support &gt; Apply/Change &gt; EZ number sending preference.";

	// http://www.au.kddi.com/ezfactory/tec/spec/ezsava_ip.html
	// Last Update: 2011-04-28
	$this->networks_new = array(
		'111.107.116.0/26',
		'111.107.116.64/26',
		'111.107.116.192/28',
	);

	// Last Update: 2010-11-11
	$this->networks = array(
		'210.230.128.224/28', 
		'121.111.227.160/27', 
		'61.117.1.0/28', 
		'219.108.158.0/27', 
		'219.215.146.0/28', 
		'61.117.2.32/29', 
		'61.117.2.40/29', 
		'219.108.158.40/29', 
		'219.125.148.0/25', 
		'222.5.63.0/25', 
		'222.5.63.128/25', 
		'222.5.62.128/25', 
		'59.135.38.128/25', 
		'219.108.157.0/25', 
		'219.125.145.0/25', 
		'121.111.231.0/25', 
		'121.111.227.0/25', 
		'118.152.214.192/26', 
		'118.159.131.0/25', 
		'118.159.133.0/25', 
		'118.159.132.160/27', 
		'118.86.142.0/26', // Feb, 2010
		'118.86.141.64/26', // Apr, 2010
		'118.86.141.128/26', // Apr, 2010
		'118.86.141.192/26', // Apr, 2010 
		'118.159.133.192/26', // Nov, 2010
		'111.86.143.192/27', // Nov, 2010
		'111.86.143.224/27', // Nov, 2010
		'111.86.147.0/27', // Nov, 2010
		'111.86.142.128/27', // Nov, 2010
		'111.86.142.160/27', // Nov, 2010
		'111.86.142.192/27', // Nov, 2010
		'111.86.142.224/27', // Nov, 2010
		'111.86.143.0/27', // Nov, 2010
		'111.86.143.32/27', // Nov, 2010
		'111.86.147.32/27', // Jan, 2011
		'111.86.147.64/27', // Jan, 2011
		'111.86.147.96/27', // Jan, 2011
		'111.86.147.128/27', // Jan, 2011
		'111.86.147.160/27', // Jan, 2011
		'111.86.147.192/27', // Jan, 2011
		'111.86.147.224/27', // Jan, 2011
		);
	// http://www.au.kddi.com/ezfactory/tec/spec/4_4.html
	// Last Update: 2011-05-14
	// array('term_name', 'type'); 0: non flat-rate, 1: KCP, 2: KCP+, 3: KCP 3.0
	$this->device_IDs = array(
		"TS3Z" => array("T007", 3),
		"KC46" => array("K009", 3),
		"SN3U" => array("S007", 3),
		"TS3Y" => array("T008", 3),
		"CA3K" => array("CA007", 3),
		"KC45" => array("K010", 1),
		"KC44" => array("mamorino2", 1),
		"SN3T" => array("G11[iida]", 3),
		"PT36" => array("PT002", 1),
		"TS3X" => array("T006", 3),
		"KC42" => array("K007", 2),
		"SH3L" => array("SH011", 2),
		"SN3S" => array("S006", 3),
		"KC43" => array("K008", 1),
		"CA3J" => array("CA006", 2),
		"CA3I" => array("G'zOne TYPE-X", 2),
		"SH3K" => array("SH010", 2),
		"TS3W" => array("X-RAY[iida]", 3),
		"SN3Q" => array("S005", 3),
		"TS3V" => array("T005", 2),
		"SN3R" => array("URBANO MOND", 3),
		"KC41" => array("K006 (Camera less)", 1),
		"SH3J" => array("SH009", 2),
		"KC3Z" => array("K006", 1),
		"TS3U" => array("LIGHT POOL[iida]", 2),
		"KC3Y" => array("K005", 1),
		"SH3I" => array("SH008", 2),
		"SN3O" => array("S003", 2),
		"KC3X" => array("SA002", 2),
		"TS3S" => array("T004", 3),
		"SN3P" => array("S004", 3),
		"HI3H" => array("beskey", 2),
		"CA3H" => array("CA005", 2),
		"SH3H" => array("SH007", 2),
		"KC3W" => array("mamorino", 1),
		"SH3G" => array("SH006", 2),
		"KC3V" => array("lotta[iida]", 1),
		"KC3U" => array("K004", 1),
		"SN3N" => array("URBANO BARONE", 2),
		"SH3F" => array("SH005", 2),
		"SN3L" => array("BRAVIA Phone U1", 2),
		"SH3E" => array("SH004", 2),
		"KC3S" => array("PRISMOID[iida]", 1),
		"TS3R" => array("T003", 2),
		"SH3D" => array("SH003", 2),
		"CA3G" => array("CA004", 2),
		"SN3M" => array("S002", 1),
		"KC3R" => array("SA001", 2),
		"CA3F" => array("CA003", 2),
		"TS3Q" => array("PLY[iida]", 1),
		"KC3P" => array("K003", 1),
		"HI3G" => array("Mobile Hi-Vision CAM Wooo", 2),
		"KC3Q" => array("misora[iida]", 1),
		"TS3O" => array("biblio", 2),
		"TS3P" => array("T002", 2),
		"SH3B" => array("SH002", 2),
		"KC3O" => array("K002", 1),
		"SH3C" => array("Sportio water beat", 2),
		"CA3E" => array("CA002", 2),
		"SN3K" => array("G9[iida]", 2),
		"SN3J" => array("S001", 2),
		"PT35" => array("NS02", 1),
		"MA35" => array("P001", 2),
		"TS3N" => array("T001", 2),
		"HI3F" => array("H001", 2),
		"SH38" => array("SH001", 2),
		"CA3D" => array("CA001", 2),
		"SN3I" => array("Premier3", 2),
		"KC3N" => array("NS01", 1),
		"KC3M" => array("K001", 1),
		"SN3H" => array("Xmini", 2),
		"HI3E" => array("W63H", 2),
		"TS3M" => array("W65T", 2),
		"CA3C" => array("W63CA", 2),
		"SH37" => array("W64SH", 2),
		"KC3I" => array("W63K", 1),
		"SN3G" => array("W64S", 1),
		"MA34" => array("W62P", 1),
		"TS3L" => array("W64T", 2),
		"KC3K" => array("W63K (Camera Less)", 1),
		"SH36" => array("URBANO", 1),
		"PT34" => array("W62PT", 1),
		"SA3E" => array("W64SA", 2),
		"CA3B" => array("W62CA", 2),
		"HI3D" => array("W62H", 2),
		"SH35" => array("W62SH", 2),
		"SN3F" => array("re", 2), 
		"KC3H" => array("W63K", 1), 
		"TS3K" => array("Sportio", 2), 
		"TS3J" => array("W62T", 2), 
		"SA3D" => array("W63SA", 2), 
		"KC3G" => array("W62K", 1), 
		"SN3D" => array("W61S", 2), 
		"SA3C" => array("W61SA", 2), 
		"SN3E" => array("W62S", 1), 
		"TS3I" => array("W61T", 2), 
		"HI3C" => array("W61H", 1), 
		"ST34" => array("W62SA", 1), 
		"PT33" => array("W61PT", 1), 
		"MA33" => array("W61P", 1), 
		"CA3A" => array("W61CA", 1), 
		"KC3D" => array("W61K", 1), 
		"SA3B" => array("W54SA", 2), 
		"SH34" => array("W61SH", 1), 
		"SN3C" => array("W54S", 2), 
		"TS3H" => array("W56T", 2), 
		"TS3G" => array("W55T", 1), 
		"HI3B" => array("W53H", 1), 
		"KC3B" => array("W53K/W64K", 1), 
		"ST33" => array("INFOBAR 2", 1), 
		"KC3E" => array("W44K II (Camera Less)", 1), 
		"SN3B" => array("W53S", 1), 
		"CA39" => array("W53CA", 1), 
		"ST32" => array("W53SA", 1), 
		"TS3E" => array("W54T", 1), 
		"SH33" => array("W52SH", 1), 
		"CA38" => array("W52CA", 1), 
		"MA32" => array("W52P", 1), 
		"SN3A" => array("W52S", 1), 
		"TS3D" => array("W53T", 1), 
		"SA3A" => array("W52SA", 1), 
		"HI3A" => array("W52H", 1), 
		"KC3A" => array("MEDIA SKIN", 1), 
		"SH32" => array("W51SH", 1), 
		"SN39" => array("W51S", 1), 
		"TS3C" => array("W52T", 1), 
		"TS3B" => array("W51T", 1), 
		"SA39" => array("W51SA", 1), 
		"HI39" => array("W51H", 1), 
		"CA37" => array("W51CA", 1), 
		"MA31" => array("W51P", 1), 
		"KC39" => array("W51K", 1), 
		"TS39" => array("DRAPE", 1), 
		"TS3A" => array("W47T", 1), 
		"SN38" => array("W44S", 1), 
		"KC38" => array("W44K/K II", 1), 
		"SA38" => array("W43SA", 1), 
		"TS38" => array("W45T", 1), 
		"CA35" => array("W43CA", 1), 
		"HI38" => array("W43H/H II", 1), 
		"SN37" => array("W43S", 1), 
		"KC37" => array("W43K", 1), 
		"ST31" => array("W42SA", 1), 
		"SH31" => array("W41SH", 1), 
		"CA34" => array("W42CA", 1), 
		"HI37" => array("W42H", 1), 
		"TS37" => array("W44T/T II/T III", 1), 
		"TS35" => array("neon", 1), 
		"TS36" => array("W43T", 1), 
		"SN36" => array("W42S", 1), 
		"KC36" => array("W42K", 1), 
		"KC35" => array("W41K", 1), 
		"SA36" => array("W41SA", 1), 
		"TS34" => array("W41T", 1), 
		"HI36" => array("W41H", 1), 
		"CA33" => array("W41CA", 1), 
		"SN34" => array("W41S", 1), 
		"HI34" => array("PENCK", 1), 
		"SA35" => array("W33SA/SA II", 1), 
		"TS33" => array("W32T", 1), 
		"SA34" => array("W32SA", 1), 
		"KC34" => array("W32K", 1), 
		"HI35" => array("W32H", 1), 
		"SN33" => array("W32S", 1), 
		"SN35" => array("W32S", 1), 
		"CA32" => array("W31CA", 1), 
		"TS32" => array("W31T", 1), 
		"SN32" => array("W31S", 1), 
		"KC33" => array("W31K/K II", 1), 
		"SA33" => array("W31SA/SA II", 1), 
		"SA32" => array("W22SA", 1), 
		"HI33" => array("W22H", 1), 
		"CA31" => array("W21CA/CA II", 1), 
		"TS31" => array("W21T", 1), 
		"SA31" => array("W21SA", 1), 
		"SN31" => array("W21S", 1), 
		"KC32" => array("W21K", 1), 
		"HI32" => array("W21H", 1), 
		"KC31" => array("W11K", 1), 
		"HI31" => array("W11H", 1), 
		"TS3T" => array("E08T", 2),
		"KC3T" => array("E07K", 1),
		"SH3A" => array("E06SH", 2),
		"SH39" => array("E05SH", 2), 
		"CA36" => array("E03CA", 1), 
		"SA37" => array("E02SA", 1), 
		"ST2C" => array("Sweets cute", 0), 
		"ST29" => array("Sweets pure", 0), 
		"CA28" => array("G'zOne TYPE-R", 0), 
		"ST26" => array("Sweets", 0), 
		"ST25" => array("talby", 0), 
		"ST22" => array("INFOBAR", 0), 
		"KC2A" => array("A5528K", 0), 
		"SA2A" => array("A5527SA", 0), 
		"KC29" => array("A5526K", 0), 
		"ST2D" => array("A5525SA", 0), 
		"TS2D" => array("A5523T", 0), 
		"SA29" => array("A5522SA", 0), 
		"KC28" => array("A5521K", 0), 
		"ST2A" => array("A5520SA/SA II", 0), 
		"ST28" => array("A5518SA", 0), 
		"TS2C" => array("A5517T", 0), 
		"TS2B" => array("A5516T", 0), 
		"KC27" => array("A5515K", 0), 
		"ST27" => array("A5514SA", 0), 
		"CA27" => array("A5512CA", 0), 
		"TS2A" => array("A5511T", 0), 
		"TS29" => array("A5509T", 0), 
		"ST24" => array("A5507SA", 0), 
		"TS28" => array("A5506T", 0), 
		"SA27" => array("A5505SA", 0), 
		"TS27" => array("A5504T", 0), 
		"SA26" => array("A5503SA", 0), 
		"KC24" => array("A5502K", 0), 
		"KC25" => array("A5502K", 0), 
		"TS26" => array("A5501T", 0), 
		"CA26" => array("A5407CA", 0), 
		"CA25" => array("A5406CA", 0), 
		"ST23" => array("A5405SA", 0), 
		"SN25" => array("A5404S", 0), 
		"CA24" => array("A5403CA", 0), 
		"SN24" => array("A5402S", 0), 
		"CA23" => array("A5401CA II", 0), 
		"CA23" => array("A5401CA", 0), 
		"ST21" => array("A5306ST", 0), 
		"KC22" => array("A5305K", 0), 
		"TS24" => array("A5304T", 0), 
		"HI24" => array("A5303H II", 0), 
		"HI23" => array("A5303H", 0), 
		"CA22" => array("A5302CA", 0), 
		"TS23" => array("A5301T", 0), 
		"SA22" => array("A3015SA", 0), 
		"PT22" => array("A3016PT", 0), 
		"PT21" => array("A1405PT", 0), 
		"SN29" => array("A1404S/S II", 0), 
		"KC26" => array("A1403K/B01K", 0), 
		"SN27" => array("A1402S", 0), 
		"SN28" => array("A1402S II (Camera Less)", 0), 
		"SN26" => array("A1402S", 0), 
		"KC23" => array("A1401K", 0), 
		"SA28" => array("A1305SA", 0), 
		"TS25" => array("A1304T II", 0), 
		"TS25" => array("A1304T II", 0), 
		"TS25" => array("A1304T (Camera Less)", 0), 
		"SA25" => array("A1303SA", 0), 
		"SA24" => array("A1302SA", 0), 
		"SN23" => array("A1301S", 0), 
		"ST14" => array("A1014ST", 0), 
		"KC15" => array("A1013K", 0), 
		"SN21" => array("A3014S", 0), 
		"TS22" => array("A3013T", 0), 
		"CA21" => array("A3012CA", 0), 
		"SA21" => array("A3011SA", 0), 
		"SN22" => array("A1101S", 0), 
		"KC14" => array("A1012K", 0), 
		"ST13" => array("A1011ST", 0), 
		"TS21" => array("C5001T", 0), 
		"MA21" => array("C3003P", 0), 
		"KC21" => array("C3002K", 0), 
		"HI21" => array("C3001H", 0), 
		"SN17" => array("C1002S", 0), 
		"SY15" => array("C1001SA", 0), 
		"CA14" => array("C452CA", 0), 
		"HI14" => array("C451H", 0), 
		"TS14" => array("C415T", 0), 
		"KC13" => array("C414K II", 0), 
		"KC13" => array("C414K", 0), 
		"SN15" => array("C413S", 0), 
		"SN16" => array("C413S", 0), 
		"SY14" => array("C412SA", 0), 
		"ST12" => array("C411ST", 0), 
		"TS13" => array("C410T", 0), 
		"CA13" => array("C409CA", 0), 
		"MA13" => array("C408P", 0), 
		"HI13" => array("C407H", 0), 
		"SN13" => array("C406S", 0), 
		"SY13" => array("C405SA", 0), 
		"SN12" => array("C404S", 0), 
		"SN14" => array("C404S", 0), 
		"ST11" => array("C403ST", 0), 
		"DN11" => array("C402DE", 0), 
		"SY12" => array("C401SA", 0), 
	);
	// http://www.au.kddi.com/ezfactory/tec/spec/3.html
	self::$pictograms = array (
		'1'   => "\xf6\x59", // 「!」
		'2'   => "\xf6\x5a", // 「!」
		'3'   => "\xf6\x5b", // 「?」
		'4'   => "\xf7\x48", // 「Q」
		'5'   => "\xf7\x49", // 左向き三角1
		'6'   => "\xf7\x4a", // 右向き三角1
		'7'   => "\xf7\x4b", // 左向き三角2
		'8'   => "\xf7\x4c", // 右向き三角2
		'9'   => "\xf7\x4d", // 小四角 1
		'10'  => "\xf7\x4e", // 小四角 2
		'11'  => "\xf7\x4f", // インフォメーションシンボル
		'12'  => "\xf6\x9a", // ワイングラス
		'13'  => "\xf6\xea", // スピーカー
		'14'  => "\xf7\x96", // ドルマーク
		'15'  => "\xf6\x5e", // 月 1
		'16'  => "\xf6\x5f", // いなずま
		'17'  => "\xf7\x50", // 中四角 1
		'18'  => "\xf7\x51", // 中四角 2
		'19'  => "\xf7\x52", // 小菱形 1
		'20'  => "\xf7\x53", // 小菱形 2
		'21'  => "\xf7\x54", // 中四角 1
		'22'  => "\xf7\x55", // 中四角 2
		'23'  => "\xf7\x56", // 小菱形 1
		'24'  => "\xf7\x57", // 小菱形 2
		'25'  => "\xf7\x97", // 腕時計
		'26'  => "\xf7\x58", // プラス
		'27'  => "\xf7\x59", // マイナス
		'28'  => "\xf7\x5a", // 星 1
		'29'  => "\xf7\x5b", // 上矢印 1
		'30'  => "\xf7\x5c", // 下矢印 1
		'31'  => "\xf7\x5d", // 丸に斜め線
		'32'  => "\xf7\x5e", // 下三角 1
		'33'  => "\xf7\x5f", // 上三角 1
		'34'  => "\xf7\x60", // 下三角 2
		'35'  => "\xf7\x61", // 上三角 2
		'36'  => "\xf7\x62", // 大菱形 1
		'37'  => "\xf7\x63", // 大菱形 2
		'38'  => "\xf7\x64", // 特大四角 1
		'39'  => "\xf7\x65", // 特大四角 2
		'40'  => "\xf7\x66", // 大丸 1
		'41'  => "\xf7\x67", // 大丸 2
		'42'  => "\xf7\x68", // 上矢印 2 (左上)
		'43'  => "\xf7\x69", // 下矢印 2 (右下)
		'44'  => "\xf6\x60", // 太陽
		'45'  => "\xf6\x93", // 野球ボール
		'46'  => "\xf7\xb1", // 時計
		'47'  => "\xf6\x61", // 月 2 (顔つき)
		'48'  => "\xf6\xeb", // ベル
		'49'  => "\xf7\x7c", // プッシュピン (画鋲)
		'50'  => "\xf6\xd3", // 小顔
		'51'  => "\xf7\xb2", // ハート
		'52'  => "\xf6\x9b", // マティーニ (カクテルグラス)
		'53'  => "\xf6\xec", // 四つ葉
		'54'  => "\xf7\x6a", // トレードマーク (TM)
		'55'  => "\xf7\x6b", // かける
		'56'  => "\xf7\x7d", // 文書 1
		'57'  => "\xf7\x98", // 砂時計 1
		'58'  => "\xf6\x54", // 砂時計 2
		'59'  => "\xf7\x7e", // フロッピーディスク 1
		'60'  => "\xf6\x62", // 雪の結晶
		'61'  => "\xf7\x6c", // バツ 1
		'62'  => "\xf7\x6d", // バツ 2
		'63'  => "\xf7\x6e", // 右矢印 1
		'64'  => "\xf7\x6f", // 左矢印 1
		'65'  => "\xf6\x9c", // マグカップ
		'66'  => "\xf7\x70", // 割る
		'67'  => "\xf7\x80", // カレンダー
		'68'  => "\xf6\xd4", // スマイルフェイス
		'69'  => "\xf6\x63", // 星 2
		'70'  => "\xf7\x71", // 右矢印 2 (右上)
		'71'  => "\xf7\x72", // 左矢印 2 (左下)
		'72'  => "\xf6\xed", // ジュエリー
		'73'  => "\xf7\x73", // チェックマーク 1
		'74'  => "\xf6\xb8", // 犬 (プードル)
		'75'  => "\xf6\x40", // 星 3
		'76'  => "\xf6\x44", // スパーク
		'77'  => "\xf6\x4e", // 電球
		'78'  => "\xf6\xb9", // 鳥
		'79'  => "\xf7\xac", // フォルダ 1 (閉)
		'80'  => "\xf6\xd5", // 顔 1
		'81'  => "\xf7\x74", // コピーライトマーク (C)
		'82'  => "\xf7\x75", // レジスタードマーク (R)
		'83'  => "\xf6\x74", // ブリーフケース (ハンドバック)
		'84'  => "\xf7\xad", // フォルダ 2 (開)
		'85'  => "\xf7\xb3", // 電話 1 (プッシュホン)
		'86'  => "\xf6\xd6", // 吹き出しコメント
		'87'  => "\xf7\x99", // クレジットカード
		'88'  => "\xf7\x76", // 上三角 3
		'89'  => "\xf7\x77", // 下三角 3
		'90'  => "\xf7\x90", // USA (国旗)
		'91'  => "\xf6\x75", // ノート 3
		'92'  => "\xf7\x81", // クリップボード
		'93'  => "\xf7\xb4", // カップ
		'94'  => "\xf6\xee", // カメラ
		'95'  => "\xf6\x64", // 雨
		'96'  => "\xf6\x94", // フットボール
		'97'  => "\xf7\x82", // 本 1
		'98'  => "\xf6\x5c", // 立ち入り禁止
		'99'  => "\xf6\x42", // 信号
		'100' => "\xf7\x83", // 本 2
		'101' => "\xf7\x84", // 本 3
		'102' => "\xf7\x85", // 本 4
		'103' => "\xf7\x86", // 文書 2
		'104' => "\xf6\xef", // はさみ
		'105' => "\xf7\x87", // ひめくりカレンダー
		'106' => "\xf6\x76", // チケット・キップ
		'107' => "\xf6\x65", // くもり
		'108' => "\xf6\xfa", // 封筒
		'109' => "\xf7\x9a", // 小切手 (CHECK)
		'110' => "\xf6\xf0", // ビデオカメラ
		'111' => "\xf7\x9b", // ハンディカム
		'112' => "\xf6\x84", // 家
		'113' => "\xf6\xbd", // 花 (チューリップ)
		'114' => "\xf7\x9c", // ナイフ
		'115' => "\xf7\x9d", // ビデオテープ
		'116' => "\xf6\xd7", // めがね
		'117' => "\xf7\x78", // 回り矢印 1
		'118' => "\xf7\x79", // 回り矢印 2
		'119' => "\xf6\xf1", // むしめがね
		'120' => "\xf6\xf2", // 鍵
		'121' => "\xf7\x88", // ノート 1
		'122' => "\xf6\x77", // ノート 2 (開)
		'123' => "\xf7\x9e", // ボルト & ナット
		'124' => "\xf6\xf3", // くつ (ハイヒール)
		'125' => "\xf6\x8a", // 車
		'126' => "\xf7\x9f", // フロッピー 2
		'127' => "\xf7\x91", // チャート (棒グラフ)
		'128' => "\xf7\x92", // グラフ 1 (折れ線グラフ)
		'129' => "\xf6\xf4", // メールボックス
		'130' => "\xf7\xa0", // 懐中電灯
		'131' => "\xf7\x89", // Roldex
		'132' => "\xf7\x7a", // チェックマーク 2
		'133' => "\xf6\xa7", // はっぱ
		'134' => "\xf6\xba", // 猟犬
		'135' => "\xf7\xa1", // 電池
		'136' => "\xf7\x7b", // スクロール
		'137' => "\xf7\x8a", // がびょう
		'138' => "\xf6\xf5", // 錠前
		'139' => "\xf7\xa2", // ドル札
		'140' => "\xf6\xd8", // 指差し確認左
		'141' => "\xf6\xd9", // 指差し確認右
		'142' => "\xf7\x8b", // 台帳
		'143' => "\xf6\x78", // クリップ
		'144' => "\xf6\xa8", // プレゼント
		'145' => "\xf6\xf6", // 名札
		'146' => "\xf6\x85", // ゴハン 1 (ナイフとフォーク)
		'147' => "\xf7\x8c", // 複数本
		'148' => "\xf6\x8b", // トラック
		'149' => "\xf6\x79", // エンピツ
		'150' => "\xf7\xa3", // ロゴ (PDC社)
		'151' => "\xf7\xae", // 封筒 2
		'152' => "\xf7\xa4", // レンチ
		'153' => "\xf7\xaf", // 送信 BOX
		'154' => "\xf7\xb0", // 受信 BOX
		'155' => "\xf6\xf7", // 電話 2 (受話器)
		'156' => "\xf6\x86", // 工場・建物
		'157' => "\xf7\x8d", // 定規 1 (直線)
		'158' => "\xf6\x7a", // 定規 2 (三角)
		'159' => "\xf7\x93", // グラフ 2
		'160' => "\xf6\x9d", // 食事 2 (マンガ肉)
		'161' => "\xf7\xa5", // 電話 3 (携帯)
		'162' => "\xf7\xa6", // コンセント
		'163' => "\xf6\xda", // 家族
		'164' => "\xf7\xa7", // リンク
		'165' => "\xf6\xf8", // パッケージ
		'166' => "\xf6\xf9", // FAX
		'167' => "\xf6\x66", // ときどき曇り
		'168' => "\xf6\x8c", // 飛行機
		'169' => "\xf6\x8d", // ボート (船)
		'170' => "\xf6\xa1", // サイコロ
		'171' => "\xf7\xa8", // 新聞
		'172' => "\xf6\x8e", // 電車
		'173' => "\xf7\xa9", // 全部ブランク
		'174' => "\xf7\xaa", // 半分ブランク
		'175' => "\xf7\xab", // 4分の1ブランク
		'176' => "\xf6\x55", // 喫煙
		'177' => "\xf6\x56", // 禁煙
		'178' => "\xf6\x57", // 車椅子
		'179' => "\xf6\x58", // 若葉マーク
		'180' => "\xf6\xfb", // 四角数字 1
		'181' => "\xf6\xfc", // 四角数字 2
		'182' => "\xf7\x40", // 四角数字 3
		'183' => "\xf7\x41", // 四角数字 4
		'184' => "\xf7\x42", // 四角数字 5
		'185' => "\xf7\x43", // 四角数字 6
		'186' => "\xf7\x44", // 四角数字 7
		'187' => "\xf7\x45", // 四角数字 8
		'188' => "\xf7\x46", // 四角数字 9
		'189' => "\xf7\x47", // 四角数字 10
		'190' => "\xf6\x41", // 台風
		'191' => "\xf6\x5d", // ゆきだるま
		'192' => "\xf6\x67", // 星座 (おひつじ座)
		'193' => "\xf6\x68", // 星座 (おうし座)
		'194' => "\xf6\x69", // 星座 (双子座)
		'195' => "\xf6\x6a", // 星座 (かに座)
		'196' => "\xf6\x6b", // 星座 (しし座)
		'197' => "\xf6\x6c", // 星座 (おとめ座)
		'198' => "\xf6\x6d", // 星座 (天秤座)
		'199' => "\xf6\x6e", // 星座 (さそり座)
		'200' => "\xf6\x6f", // 星座 (いて座)
		'201' => "\xf6\x70", // 星座 (やぎ座)
		'202' => "\xf6\x71", // 星座 (水瓶座)
		'203' => "\xf6\x72", // 星座 (うお座)
		'204' => "\xf6\x73", // 星座 (へびつかい座)
		'205' => "\xf6\x7b", // ATM
		'206' => "\xf6\x7c", // 24 HOURS (コンビニ)
		'207' => "\xf6\x7d", // トイレ
		'208' => "\xf6\x7e", // パーキング
		'209' => "\xf6\x80", // バス停
		'210' => "\xf6\x81", // アンテナ (位置情報マーク)
		'211' => "\xf6\x82", // 港 (いかりマーク)
		'212' => "\xf6\x83", // 銀行
		'213' => "\xf7\x8e", // ガススタンド
		'214' => "\xf7\x8f", // 地図
		'215' => "\xf6\x87", // 自転車
		'216' => "\xf6\x88", // バス
		'217' => "\xf6\x89", // 新幹線
		'218' => "\xf6\x43", // マラソン
		'219' => "\xf6\x8f", // サッカー
		'220' => "\xf6\x90", // テニス
		'221' => "\xf6\x91", // スノーボード
		'222' => "\xf6\x92", // チェッカーフラッグ (モータースポーツ)
		'223' => "\xf6\x45", // 遊園地
		'224' => "\xf6\x95", // 温泉
		'225' => "\xf6\x96", // 居酒屋 (赤ちょうちん)
		'226' => "\xf6\x97", // 映画 (かちんこ)
		'227' => "\xf6\x98", // 夜の橋
		'228' => "\xf6\x99", // 東京タワー
		'229' => "\xf6\x46", // スロット (777)
		'230' => "\xf6\x47", // くす玉 (アタリのくす玉)
		'231' => "\xf6\x9e", // 当選弓矢
		'232' => "\xf6\x9f", // ゲームのコントローラ
		'233' => "\xf6\xa0", // 賞金
		'234' => "\xf6\xa2", // クリスマスツリー
		'235' => "\xf6\xa3", // 花見 (さくら)
		'236' => "\xf6\xa4", // お化け
		'237' => "\xf6\xa5", // 旗 (祝日・日の丸)
		'238' => "\xf6\xa6", // スイカ
		'239' => "\xf6\xa9", // ケーキ
		'240' => "\xf6\xaa", // フライパン (目玉焼き)
		'241' => "\xf6\xab", // さくらんぼ
		'242' => "\xf6\xac", // ふぐ
		'243' => "\xf6\xad", // イチゴ
		'244' => "\xf6\xae", // おにぎり
		'245' => "\xf6\xaf", // ハンバーガー (ファーストフード)
		'246' => "\xf6\x48", // くじら
		'247' => "\xf6\xb0", // うさぎ
		'248' => "\xf6\xb1", // うま
		'249' => "\xf6\xb2", // さる
		'250' => "\xf6\xb3", // かえる
		'251' => "\xf6\xb4", // 猫
		'252' => "\xf6\xb5", // ペンギン
		'253' => "\xf6\xb6", // あり
		'254' => "\xf6\xb7", // ぶた
		'255' => "\xf6\xbb", // やしのき
		'256' => "\xf6\xbc", // ひまわり
		'257' => "\xf6\x49", // 顔 1 (うれしいカオ)
		'258' => "\xf6\x4a", // 顔 2 (おこったカオ)
		'259' => "\xf6\x4b", // 顔 3 (かなしいカオ)
		'260' => "\xf6\x4c", // 顔 4 (つかれたカオ)
		'261' => "\xf6\x4d", // 眠い (ZZZ...)
		'262' => "\xf6\xbe", // 怒り (ムカッ)
		'263' => "\xf6\xbf", // 雫 (涙・汗)
		'264' => "\xf6\xc0", // からかう (あっかんべえ)
		'265' => "\xf6\x4f", // ハート 2 (われている)
		'266' => "\xf6\x50", // ハート 3 (大きい & 小さい)
		'267' => "\xf6\x51", // スパーク 2 (キラリマーク)
		'268' => "\xf6\x52", // 爆弾
		'269' => "\xf6\x53", // 炎
		'270' => "\xf6\xc1", // 捜索 (SOS)
		'271' => "\xf6\xc2", // 力こぶ
		'272' => "\xf6\xc3", // ハート 5 (矢がささっている)
		'273' => "\xf6\xc4", // キスマーク
		'274' => "\xf6\xc5", // 宇宙人
		'275' => "\xf6\xc6", // なると
		'276' => "\xf6\xc7", // 足跡 (犬)
		'277' => "\xf6\xc8", // 悪魔
		'278' => "\xf6\xc9", // 花丸
		'279' => "\xf6\xca", // 丸秘
		'280' => "\xf6\xcb", // 100点満点
		'281' => "\xf6\xcc", // パンチ
		'282' => "\xf6\xcd", // ダッシュ
		'283' => "\xf6\xce", // ウンチマーク
		'284' => "\xf6\xcf", // 人差し指サイン
		'285' => "\xf6\xd0", // マル得
		'286' => "\xf6\xd1", // どくろ
		'287' => "\xf6\xd2", // おやゆびサイン (指が上)
		'288' => "\xf6\xdb", // テレビ
		'289' => "\xf6\xdc", // マイク
		'290' => "\xf6\xdd", // 財布
		'291' => "\xf6\xde", // メロディ
		'292' => "\xf6\xdf", // ギター (エレキ)
		'293' => "\xf6\xe0", // バイオリン (クラシック)
		'294' => "\xf6\xe1", // ヘッドフォン
		'295' => "\xf6\xe2", // 口紅
		'296' => "\xf6\xe3", // アクション (ピストル)
		'297' => "\xf6\xe4", // エステ
		'298' => "\xf7\x94", // EZ マーク
		'299' => "\xf7\x95", // 無料 (FREE)
		'300' => "\xf6\xe5", // CD/DVD
		'301' => "\xf6\xe6", // 婦人服
		'302' => "\xf6\xe7", // UFO
		'303' => "\xf6\xe8", // 更新 (UP!)
		'304' => "\xf6\xe9", // 注射器 (血)
		'305' => "\xf7\xb5", // 霧
		'306' => "\xf7\xb6", // ゴルフ
		'307' => "\xf7\xb7", // バスケットボール
		'308' => "\xf7\xb8", // ポケットベル
		'309' => "\xf7\xb9", // アート
		'310' => "\xf7\xba", // 演劇
		'311' => "\xf7\xbb", // イベント (サーカス)
		'312' => "\xf7\xbc", // リボン
		'313' => "\xf7\xbd", // バースデー
		'314' => "\xf7\xbe", // スペード
		'315' => "\xf7\xbf", // ダイヤ
		'316' => "\xf7\xc0", // クラブ
		'317' => "\xf7\xc1", // 目
		'318' => "\xf7\xc2", // 耳
		'319' => "\xf7\xc3", // 手 (チョキ)
		'320' => "\xf7\xc4", // 手 (パー)
		'321' => "\xf7\xc5", // 新月
		'322' => "\xf7\xc6", // やや欠け月
		'323' => "\xf7\xc7", // 半月
		'324' => "\xf7\xc8", // クリア
		'325' => "\xf7\xc9", // 四角数字 0
		'326' => "\xf7\xca", // 決定 (OK)
		'327' => "\xf7\xcb", // ふらふら (顔)
		'328' => "\xf7\xcc", // かわいい
		'329' => "\xf7\xcd", // どんっ (衝撃)
		'330' => "\xf7\xce", // あせあせ (飛び散る汗)
		'331' => "\xf7\xcf", // イージープラス
		'332' => "\xf7\xd0", // 地球
		'333' => "\xf7\xd1", // ラーメン
		'334' => "\xf7\xe5", // NEW
		'335' => "\xf7\xe6", // 紳士服
		'336' => "\xf7\xe7", // 紳士靴
		'337' => "\xf7\xe8", // パソコン
		'338' => "\xf7\xe9", // ラジオ
		'339' => "\xf7\xea", // バラ
		'340' => "\xf7\xeb", // チャペル
		'341' => "\xf7\xec", // 地下鉄
		'342' => "\xf7\xed", // 富士山
		'343' => "\xf7\xee", // 八分音符
		'344' => "\xf7\xef", // 天使
		'345' => "\xf7\xf0", // トラ
		'346' => "\xf7\xf1", // くま
		'347' => "\xf7\xf2", // ねずみ
		'348' => "\xf7\xf3", // ウィンク (顔)
		'349' => "\xf7\xf4", // 目がハート (顔)
		'350' => "\xf7\xf5", // ショッキング (顔)
		'351' => "\xf7\xf6", // 困り (顔)
		'352' => "\xf7\xf7", // たこ
		'353' => "\xf7\xf8", // ロケット
		'354' => "\xf7\xf9", // 王冠
		'355' => "\xf7\xfa", // チュー (キスしている)
		'356' => "\xf7\xfb", // ハンマー
		'357' => "\xf7\xfc", // 打ち上げ花火
		'358' => "\xf3\x40", // 枯れ葉
		'359' => "\xf3\x41", // 仕事かばん
		'360' => "\xf3\x42", // 噴水
		'361' => "\xf3\x43", // キャンプ
		'362' => "\xf3\x44", // 麻雀
		'363' => "\xf3\x45", // VS (バーサス)
		'364' => "\xf3\x46", // トロフィー
		'365' => "\xf3\x47", // カメ
		'366' => "\xf3\x48", // スペイン国旗
		'367' => "\xf3\x49", // ロシア国旗
		'368' => "\xf3\x4a", // 工事中
		'369' => "\xf3\x4b", // 風呂
		'370' => "\xf3\x4c", // 祝日マーク
		'371' => "\xf3\x4d", // 夕方街並み
		'372' => "\xf3\x4e", // 卵割り
		'373' => "\xf3\x4f", // 株価
		'374' => "\xf3\x50", // ポリス
		'375' => "\xf3\x51", // 郵便局
		'376' => "\xf3\x52", // 病院
		'377' => "\xf3\x53", // 学校
		'378' => "\xf3\x54", // ホテル
		'379' => "\xf3\x55", // 船
		'380' => "\xf3\x56", // 18禁
		'381' => "\xf3\x57", // 圏内
		'382' => "\xf3\x58", // COOL!
		'383' => "\xf3\x59", // 割マーク
		'384' => "\xf3\x5a", // ザ・マーク
		'385' => "\xf3\x5b", // IDマーク
		'386' => "\xf3\x5c", // 満マーク
		'387' => "\xf3\x5d", // 空マーク
		'388' => "\xf3\x5e", // 指定マーク
		'389' => "\xf3\x5f", // 営業中マーク
		'390' => "\xf3\x60", // 上指差し
		'391' => "\xf3\x61", // 下指差し
		'392' => "\xf3\x62", // 占い (水晶)
		'393' => "\xf3\x63", // マナーモード
		'394' => "\xf3\x64", // 電源OFF
		'395' => "\xf3\x65", // メモする
		'396' => "\xf3\x66", // ネクタイ
		'397' => "\xf3\x67", // ハイビスカス
		'398' => "\xf3\x68", // 花束
		'399' => "\xf3\x69", // サボテン
		'400' => "\xf3\x6a", // お銚子 & 杯
		'401' => "\xf3\x6b", // 乾杯 (ビール)
		'402' => "\xf3\x6c", // 祝マーク
		'403' => "\xf3\x6d", // 風邪薬 (カプセル)
		'404' => "\xf3\x6e", // 風船
		'405' => "\xf3\x6f", // クラッカー
		'406' => "\xf3\x70", // eznavigation
		'407' => "\xf3\x71", // 帽子
		'408' => "\xf3\x72", // ロングブーツ
		'409' => "\xf3\x73", // ネイル
		'410' => "\xf3\x74", // 美容院
		'411' => "\xf3\x75", // 床屋
		'412' => "\xf3\x76", // 着物
		'413' => "\xf3\x77", // ビキニ
		'414' => "\xf3\x78", // ハート (トランプ)
		'415' => "\xf3\x79", // 光るハート
		'416' => "\xf3\x7a", // 青ハート
		'417' => "\xf3\x7b", // 緑ハート
		'418' => "\xf3\x7c", // 黄ハート
		'419' => "\xf3\x7d", // 紫ハート
		'420' => "\xf3\x7e", // きらきら
		'421' => "\xf3\x80", // スキー
		'422' => "\xf3\x81", // ○
		'423' => "\xf3\x82", // 日本茶
		'424' => "\xf3\x83", // 食パン
		'425' => "\xf3\x84", // ソフトクリーム
		'426' => "\xf3\x85", // ポテト
		'427' => "\xf3\x86", // だんご
		'428' => "\xf3\x87", // おせんべい
		'429' => "\xf3\x88", // ごはん
		'430' => "\xf3\x89", // スパゲティ
		'431' => "\xf3\x8a", // カレー
		'432' => "\xf3\x8b", // おでん
		'433' => "\xf3\x8c", // 寿司
		'434' => "\xf3\x8d", // りんご
		'435' => "\xf3\x8e", // みかん
		'436' => "\xf3\x8f", // トマト
		'437' => "\xf3\x90", // なす
		'438' => "\xf3\x91", // 弁当
		'439' => "\xf3\x92", // 鍋
		'440' => "\xf3\x93", // ふっ (顔)
		'441' => "\xf3\x94", // しょんぼり (顔)
		'442' => "\xf3\x95", // 勝ち誇り (顔)
		'443' => "\xf3\x96", // 失敗 (顔)
		'444' => "\xf3\x97", // わからん
		'445' => "\xf3\x98", // 眠い
		'446' => "\xf3\x99", // てれてれ (顔)
		'447' => "\xf3\x9a", // 青ざめ (顔)
		'448' => "\xf3\x9b", // 風邪ひき
		'449' => "\xf3\x9c", // 熱 (顔)
		'450' => "\xf3\x9d", // 横目 (顔)
		'451' => "\xf3\x9e", // びっくり (顔)
		'452' => "\xf3\x9f", // あせり (顔)
		'453' => "\xf3\xa0", // 楽譜
		'454' => "\xf3\xa1", // にこにこ (顔)
		'455' => "\xf3\xa2", // チュー 2 (顔)
		'456' => "\xf3\xa3", // チュッ (顔)
		'457' => "\xf3\xa4", // 鼻
		'458' => "\xf3\xa5", // 口
		'459' => "\xf3\xa6", // ゴメン／お願い
		'460' => "\xf3\xa7", // 拍手
		'461' => "\xf3\xa8", // OK! (指で丸サイン)
		'462' => "\xf3\xa9", // ブーイング (指が下)
		'463' => "\xf3\xaa", // バイバイ
		'464' => "\xf3\xab", // NG (ネコ)
		'465' => "\xf3\xac", // OK! 2 (ネコ)
		'466' => "\xf3\xad", // 平謝り (ネコ)
		'467' => "\xf3\xae", // カップル
		'468' => "\xf3\xaf", // バニー
		'469' => "\xf3\xb0", // トランペット
		'470' => "\xf3\xb1", // ビリヤード
		'471' => "\xf3\xb2", // 水泳
		'472' => "\xf3\xb3", // 消防車
		'473' => "\xf3\xb4", // 救急車
		'474' => "\xf3\xb5", // パトカー
		'475' => "\xf3\xb6", // ジェットコースター
		'476' => "\xf3\xb7", // 門松
		'477' => "\xf3\xb8", // 雛祭り
		'478' => "\xf3\xb9", // 卒業式
		'479' => "\xf3\xba", // 入学式
		'480' => "\xf3\xbb", // こいのぼり
		'481' => "\xf3\xbc", // 傘
		'482' => "\xf3\xbd", // 花嫁
		'483' => "\xf3\xbe", // かき氷
		'484' => "\xf3\xbf", // 線香花火
		'485' => "\xf3\xc0", // 巻き貝
		'486' => "\xf3\xc1", // 風鈴
		'487' => "\xf3\xc2", // ハロウィン
		'488' => "\xf3\xc3", // お月見
		'489' => "\xf3\xc4", // サンタ
		'490' => "\xf3\xc5", // 夜／流れ星
		'491' => "\xf3\xc6", // 虹
		'492' => "\xf3\xc7", // ホテル 2
		'493' => "\xf3\xc8", // 日の出
		'494' => "\xf3\xc9", // シルクハット
		'495' => "\xf3\xca", // デパート
		'496' => "\xf3\xcb", // 城 (日本)
		'497' => "\xf3\xcc", // 城 (ヨーロッパ)
		'498' => "\xf3\xcd", // 工場 2
		'499' => "\xf3\xce", // フランス国旗
		'500' => "\xf7\xd2", // オープンウェーブ
		'501' => "\xf7\xd3", // ロック確認
		'502' => "\xf7\xd4", // 大文字
		'503' => "\xf7\xd5", // 小文字
		'504' => "\xf7\xd6", // 数字
		'505' => "\xf7\xd7", // 記号
		'506' => "\xf7\xd8", // アクセプト
		'507' => "\xf7\xd9", // チェックボックス
		'508' => "\xf7\xda", // エディット
		'509' => "\xf7\xdb", // ラジオボタン
		'510' => "\xf7\xdc", // 見る (虫眼鏡)
		'511' => "\xf7\xdd", // 戻る
		'512' => "\xf7\xde", // お気に入り
		'513' => "\xf7\xdf", // 終了
		'514' => "\xf7\xe0", // ホーム
		'515' => "\xf7\xe1", // 受信箱 1
		'516' => "\xf7\xe2", // マーク
		'517' => "\xf7\xe3", // 個人 (鍵)
		'518' => "\xf7\xe4", // 再読み込み
		'700' => "\xf3\xcf", // ドイツ国旗
		'701' => "\xf3\xd0", // イタリア国旗
		'702' => "\xf3\xd1", // イギリス国旗
		'703' => "\xf3\xd2", // 中国国旗
		'704' => "\xf3\xd3", // 韓国国旗
		'705' => "\xf3\xd4", // 白人
		'706' => "\xf3\xd5", // 中国人
		'707' => "\xf3\xd6", // インド人
		'708' => "\xf3\xd7", // おじいさん
		'709' => "\xf3\xd8", // おばあさん
		'710' => "\xf3\xd9", // 赤ちゃん
		'711' => "\xf3\xda", // 工事現場の人
		'712' => "\xf3\xdb", // お姫様
		'713' => "\xf3\xdc", // イルカ
		'714' => "\xf3\xdd", // ダンス
		'715' => "\xf3\xde", // 熱帯魚
		'716' => "\xf3\xdf", // げじげじ
		'717' => "\xf3\xe0", // 象
		'718' => "\xf3\xe1", // コアラ
		'719' => "\xf3\xe2", // ホルスタイン
		'720' => "\xf3\xe3", // ヘビ
		'721' => "\xf3\xe4", // 鶏
		'722' => "\xf3\xe5", // うりぼう
		'723' => "\xf3\xe6", // ふたこぶらくだ
		'724' => "\xf3\xe7", // A型
		'725' => "\xf3\xe8", // B型
		'726' => "\xf3\xe9", // O型
		'727' => "\xf3\xea", // AB型
		'728' => "\xf3\xeb", // 足跡
		'729' => "\xf3\xec", // スニーカー
		'730' => "\xf3\xed", // 旗
		'731' => "\xf3\xee", // 上向きカーブ矢印
		'732' => "\xf3\xef", // 下向きカーブ矢印
		'733' => "\xf3\xf0", // 「!?」
		'734' => "\xf3\xf1", // 「!!」
		'735' => "\xf3\xf2", // くるり
		'736' => "\xf3\xf3", // メロン
		'737' => "\xf3\xf4", // パイナップル
		'738' => "\xf3\xf5", // ぶどう
		'739' => "\xf3\xf6", // バナナ
		'740' => "\xf3\xf7", // とうもろこし
		'741' => "\xf3\xf8", // きのこ
		'742' => "\xf3\xf9", // 栗
		'743' => "\xf3\xfa", // 桃
		'744' => "\xf3\xfb", // やきいも
		'745' => "\xf3\xfc", // ピザ
		'746' => "\xf4\x40", // ターキー
		'747' => "\xf4\x41", // 七夕笹飾り
		'748' => "\xf4\x42", // トロピカルドリンク
		'749' => "\xf4\x43", // 辰
		'750' => "\xf4\x44", // ピアノ
		'751' => "\xf4\x45", // サーフィン
		'752' => "\xf4\x46", // 釣り
		'753' => "\xf4\x47", // ボウリング
		'754' => "\xf4\x48", // なまはげ
		'755' => "\xf4\x49", // 天狗
		'756' => "\xf4\x4a", // パンダ
		'757' => "\xf4\x4b", // あかんべー
		'758' => "\xf4\x4c", // ぶたの鼻
		'759' => "\xf4\x4d", // 花
		'760' => "\xf4\x4e", // アイスクリーム
		'761' => "\xf4\x4f", // ドーナツ
		'762' => "\xf4\x50", // クッキー
		'763' => "\xf4\x51", // チョコ
		'764' => "\xf4\x52", // キャンディ (包み)
		'765' => "\xf4\x53", // キャンディ (ぺろぺろ)
		'766' => "\xf4\x54", // 見ざる (猿)
		'767' => "\xf4\x55", // 言わざる (猿)
		'768' => "\xf4\x56", // 聞かざる (猿)
		'769' => "\xf4\x57", // 火山
		'770' => "\xf4\x58", // リボンがけのハート
		'771' => "\xf4\x59", // 英語「ABC」
		'772' => "\xf4\x5a", // プリン
		'773' => "\xf4\x5b", // ミツバチ
		'774' => "\xf4\x5c", // テントウムシ
		'775' => "\xf4\x5d", // 蜂蜜ポット
		'776' => "\xf4\x5e", // 青りんご
		'777' => "\xf4\x5f", // 羽のはえたお札
		'778' => "\xf4\x60", // 目がまわる時の記号
		'779' => "\xf4\x61", // ぷー (かわいく怒)
		'780' => "\xf4\x62", // ぷー (かわいく怒) (ネコ)
		'781' => "\xf4\x63", // 天の川
		'782' => "\xf4\x64", // チュー (ネコ)
		'783' => "\xf4\x65", // にこ (ネコ)
		'784' => "\xf4\x66", // メールする
		'785' => "\xf4\x67", // 泣き笑い (ネコ)
		'786' => "\xf4\x68", // 泣き笑い (顔)
		'787' => "\xf4\x69", // 目がハート (ネコ)
		'788' => "\xf4\x6a", // ほえー (ネコ)
		'789' => "\xf4\x6b", // ほえー (顔)
		'790' => "\xf4\x6c", // 涙ぽろり (ネコ)
		'791' => "\xf4\x6d", // 涙ぽろり (顔)
		'792' => "\xf4\x6e", // きりり (ネコ)
		'793' => "\xf4\x6f", // ドレス
		'794' => "\xf4\x70", // モヤイ像
		'795' => "\xf4\x71", // 駅
		'796' => "\xf4\x72", // 花札
		'797' => "\xf4\x73", // ジョーカー
		'798' => "\xf4\x74", // エビフライ
		'799' => "\xf4\x75", // eメールアイコン
		'800' => "\xf4\x76", // 歩く人
		'801' => "\xf4\x77", // パトカーのランプ
		'802' => "\xf4\x78", // ezmovie
		'803' => "\xf4\x79", // ドキドキしているハート
		'804' => "\xf4\x7a", // 正面向きのひよこ
		'805' => "\xf4\x7b", // ジーンズ
		'806' => "\xf4\x7c", // ハートつきメール
		'807' => "\xf4\x7d", // 循環矢印
		'808' => "\xf4\x7e", // 左右両方矢印
		'809' => "\xf4\x80", // 上下両方矢印
		'810' => "\xf4\x81", // 荒波
		'811' => "\xf4\x82", // 双葉
		'812' => "\xf4\x83", // かたつむり
		'813' => "\xf4\x84", // うっしっし (ネコ)
		'814' => "\xf4\x85", // うっしっし (顔)
		'815' => "\xf4\x86", // Cメールアイコン
		'816' => "\xf4\x87", // ハーブ
		'817' => "\xf4\x88", // 手 (グー)
		'818' => "\xf4\x89", // 「#」
		'819' => "\xf4\x8a", // 挙手 (キャラクター)
		'820' => "\xf4\x8b", // 万歳 (キャラクター)
		'821' => "\xf4\x8c", // しょんぼり (キャラクター)
		'822' => "\xf4\x8d", // かわいく怒る (キャラクター)
	);
	return;
}

/* ==================================================
 * @param	boolean $allow_search_engine
 * @return	boolean $in_network
 */
public function in_network($allow_search_engine = false) {
	return parent::in_network(self::$networks, $allow_search_engine);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function replace_smiley($buffer) {
	$smiles = array(
		'icon_smile.gif'     => self::$pictograms['257'],
		'icon_biggrin.gif'   => self::$pictograms['454'], 
		'icon_sad.gif'       => self::$pictograms['259'], 
		'icon_surprised.gif' => self::$pictograms['451'], 
		'icon_eek.gif'       => self::$pictograms['451'], 
		'icon_confused.gif'  => self::$pictograms['444'], 
		'icon_cool.gif'      => self::$pictograms['382'], 
		'icon_mad.gif'       => self::$pictograms['258'], 
		'icon_razz.gif'      => self::$pictograms['264'], 
		'icon_neutral.gif'   => self::$pictograms['440'], 
		'icon_wink.gif'      => self::$pictograms['348'], 
		'icon_lol.gif'       => self::$pictograms['789'], 
		'icon_redface.gif'   => self::$pictograms['446'], // or 349
		'icon_cry.gif'       => self::$pictograms['786'], 
		'icon_evil.gif'      => self::$pictograms['277'],  
		'icon_twisted.gif'   => self::$pictograms['277'], 
		'icon_rolleyes.gif'  => self::$pictograms['444'], 
		'icon_exclaim.gif'   => self::$pictograms['2'], 
		'icon_question.gif'  => self::$pictograms['3'], 
		'icon_idea.gif'      => self::$pictograms['77'], 
		'icon_arrow.gif'     => self::$pictograms['63'], 
		'icon_mrgreen.gif'   => self::$pictograms['814'], 
	);
	$smiles = apply_filters('ktai_smiley_table', $smiles, __CLASS__);
	$smiles = apply_filters('smiley_table/ktai_style.php', $smiles);
	return parent::replace_smiley($buffer, $smiles);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function convert_pict($buffer) {
	// http://www.au.kddi.com/email/emoji/taiohyo/
	// http://mb.softbank.jp/mb/service/3G/mail/pictogram/
	// http://www.nttdocomo.co.jp/service/mail/imode_mail/emoji_convert/
	// http://www.willcom-inc.com/ja/service/e_mail/pdf/conversiontable.pdf
	$translated = self::$pictograms + array(
		'se001' => self::$pictograms['80'], // 男の子
		'se002' => self::$pictograms['50'], // 女の子
		'se003' => self::$pictograms['273'], // 美容 (キスマーク)
		'se004' => self::$pictograms['80'], // お父さん
		'se005' => self::$pictograms['50'], // お母さん
		'se006' => self::$pictograms['335'], // 洋服
		'se007' => self::$pictograms['336'], // ブーツ
		'se008' => self::$pictograms['94'], // カメラ
		'se009' => self::$pictograms['85'], // 電話
		'se00a' => self::$pictograms['161'], // 携帯電話
		'se00b' => self::$pictograms['166'], // FAX
		'se00c' => self::$pictograms['337'], // パソコン
		'se00d' => self::$pictograms['281'], // パンチ
		'se00e' => self::$pictograms['287'], // GOOD!
		'se00f' => self::$pictograms['284'], // No.1!
		'se010' => self::$pictograms['817'], // グー
		'se011' => self::$pictograms['319'], // チョキ
		'se012' => self::$pictograms['320'], // パー
		'se013' => self::$pictograms['421'], // スキー
		'se014' => self::$pictograms['306'], // ゴルフ
		'se015' => self::$pictograms['220'], // テニス
		'se016' => self::$pictograms['45'], // 野球
		'se017' => self::$pictograms['751'], // サーフィン
		'se018' => self::$pictograms['219'], // サッカー
		'se019' => self::$pictograms['203'], // 魚
		'se01a' => self::$pictograms['248'], // うま
		'se01b' => self::$pictograms['125'], // 車
		'se01c' => self::$pictograms['169'], // ヨット
		'se01d' => self::$pictograms['168'], // 飛行機
		'se01e' => self::$pictograms['172'], // 電車
		'se01f' => self::$pictograms['217'], // 新幹線
		'se020' => self::$pictograms['3'], // ハテナ
		'se021' => self::$pictograms['2'], // ビックリ
		'se022' => self::$pictograms['51'], // ハートマーク
		'se023' => self::$pictograms['265'], // ハートブレイク
		'se024' => self::$pictograms['46'], // 1時
		'se025' => self::$pictograms['46'], // 2時
		'se026' => self::$pictograms['46'], // 時計
		'se027' => self::$pictograms['46'], // 4時
		'se028' => self::$pictograms['46'], // 5時
		'se029' => self::$pictograms['46'], // 6時
		'se02a' => self::$pictograms['46'], // 7時
		'se02b' => self::$pictograms['46'], // 8時
		'se02c' => self::$pictograms['46'], // 9時
		'se02d' => self::$pictograms['46'], // 10時
		'se02e' => self::$pictograms['46'], // 11時
		'se02f' => self::$pictograms['46'], // 12時
		'se030' => self::$pictograms['235'], // お花見
		'se031' => self::$pictograms['354'], // エンブレム
		'se032' => self::$pictograms['339'], // バラ
		'se033' => self::$pictograms['234'], // クリスマス
		'se034' => self::$pictograms['72'], // 指輪
		'se035' => self::$pictograms['72'], // 宝石
		'se036' => self::$pictograms['112'], // 家
		'se037' => self::$pictograms['340'], // 教会
		'se038' => self::$pictograms['156'], // ビル
		'se039' => self::$pictograms['795'], // 駅
		'se03a' => self::$pictograms['213'], // ガソリンスタンド
		'se03b' => self::$pictograms['342'], // 山
		'se03c' => self::$pictograms['289'], // マイク
		'se03d' => self::$pictograms['110'], // 映画
		'se03e' => self::$pictograms['343'], // 音楽
		'se03f' => self::$pictograms['120'], // カギ
		'se040' => '[サックス]', // サックス
		'se041' => self::$pictograms['292'], // ギター
		'se042' => self::$pictograms['469'], // トランペット
		'se043' => self::$pictograms['146'], // レストラン
		'se044' => self::$pictograms['52'], // カクテル
		'se045' => self::$pictograms['93'], // コーヒー
		'se046' => self::$pictograms['239'], // ケーキ
		'se047' => self::$pictograms['65'], // ビール
		'se048' => self::$pictograms['191'], // 雪
		'se049' => self::$pictograms['107'], // 曇り
		'se04a' => self::$pictograms['44'], // 晴れ (昼)
		'se04b' => self::$pictograms['95'], // 雨
		'se04c' => self::$pictograms['15'], // 晴れ (夜)
		'se04d' => self::$pictograms['493'], // 朝
		'se04e' => self::$pictograms['344'], // 天使
		'se04f' => self::$pictograms['251'], // ねこ
		'se050' => self::$pictograms['345'], // とら
		'se051' => self::$pictograms['346'], // くま
		'se052' => self::$pictograms['134'], // いぬ
		'se053' => self::$pictograms['347'], // ねずみ
		'se054' => self::$pictograms['246'], // クジラ
		'se055' => self::$pictograms['252'], // ペンギン
		'se056' => self::$pictograms['454'], // 楽 (顔)
		'se057' => self::$pictograms['257'], // 喜 (顔)
		'se058' => self::$pictograms['444'], // 哀 (顔)
		'se059' => self::$pictograms['258'], // 怒 (顔)
		'se05a' => self::$pictograms['283'], // ウンチ
		'se101' => self::$pictograms['129'], // メール受信
		'se102' => self::$pictograms['153'], // メール送信
		'se103' => self::$pictograms['784'], // メール宛先
		'se104' => self::$pictograms['513'], // 電話連絡先
		'se105' => self::$pictograms['264'], // アカンベー (顔)
		'se106' => self::$pictograms['349'], // ラブラブ (顔)
		'se107' => self::$pictograms['350'], // ガビーン (顔)
		'se108' => self::$pictograms['351'], // タラー (顔)
		'se109' => self::$pictograms['249'], // さる
		'se10a' => self::$pictograms['352'], // タコ
		'se10b' => self::$pictograms['254'], // ぶた
		'se10c' => self::$pictograms['274'], // 宇宙人
		'se10d' => self::$pictograms['353'], // ロケット
		'se10e' => self::$pictograms['354'], // 王冠
		'se10f' => self::$pictograms['77'], // 電球
		'se110' => self::$pictograms['53'], // よつば
		'se111' => self::$pictograms['355'], // キス
		'se112' => self::$pictograms['144'], // バースデー (プレゼント)
		'se113' => self::$pictograms['296'], // ピストル
		'se114' => self::$pictograms['119'], // 虫眼鏡
		'se115' => self::$pictograms['218'], // 陸上
		'se116' => self::$pictograms['356'], // オークション
		'se117' => self::$pictograms['357'], // 花火
		'se118' => self::$pictograms['133'], // もみじ
		'se119' => self::$pictograms['358'], // 落ち葉
		'se11a' => self::$pictograms['277'], // 悪魔
		'se11b' => self::$pictograms['236'], // おばけ
		'se11c' => self::$pictograms['286'], // ドクロ
		'se11d' => self::$pictograms['269'], // ファイヤー
		'se11e' => self::$pictograms['359'], // かばん
		'se11f' => '[座席]', // 座席
		'se120' => self::$pictograms['245'], // ハンバーガー
		'se121' => self::$pictograms['360'], // 公園
		'se122' => self::$pictograms['361'], // キャンプ場
		'se123' => self::$pictograms['224'], // 温泉
		'se124' => self::$pictograms['223'], // 遊園地
		'se125' => self::$pictograms['106'], // チケット
		'se126' => self::$pictograms['300'], // CD
		'se127' => self::$pictograms['300'], // DVD
		'se128' => self::$pictograms['338'], // ラジオ
		'se129' => self::$pictograms['115'], // ビデオ
		'se12a' => self::$pictograms['288'], // テレビ
		'se12b' => self::$pictograms['232'], // ゲーム
		'se12c' => self::$pictograms['343'], // 歌い出し
		'se12d' => self::$pictograms['362'], // マージャン
		'se12e' => self::$pictograms['363'], // 対決
		'se12f' => self::$pictograms['233'], // 賞金 (ドル袋)
		'se130' => self::$pictograms['231'], // 当たり
		'se131' => self::$pictograms['364'], // トロフィー
		'se132' => self::$pictograms['222'], // ゴール (チェッカーフラッグ)
		'se133' => self::$pictograms['229'], // スロット (777)
		'se134' => self::$pictograms['248'], // 競馬
		'se135' => self::$pictograms['169'], // 競艇
		'se136' => self::$pictograms['215'], // 競輪
		'se137' => self::$pictograms['368'], // 工事中
		'se138' => '♂', // 男性
		'se139' => '♀', // 女性
		'se13a' => self::$pictograms['710'], // 乳幼児
		'se13b' => self::$pictograms['304'], // 注射器
		'se13c' => self::$pictograms['261'], // 睡眠 (Zzz)
		'se13d' => self::$pictograms['16'], // 雷
		'se13e' => self::$pictograms['124'], // ハイヒール
		'se13f' => self::$pictograms['369'], // 入浴
		'se140' => self::$pictograms['207'], // トイレ
		'se141' => self::$pictograms['13'], // 音声
		'se142' => self::$pictograms['13'], // お知らせ (メガホン)
		'se143' => self::$pictograms['370'], // 祝日
		'se144' => self::$pictograms['138'], // ロックON
		'se145' => self::$pictograms['138'], // ロックOFF
		'se146' => self::$pictograms['371'], // 街
		'se147' => self::$pictograms['240'], // 料理 (卵)
		'se148' => self::$pictograms['122'], // 本
		'se149' => '[$\\]', // 為替相場
		'se14a' => self::$pictograms['373'], // 株価
		'se14b' => self::$pictograms['210'], // ニュース (パラボラアンテナ)
		'se14c' => self::$pictograms['271'], // 元気 (力こぶ)
		'se14d' => self::$pictograms['212'], // 銀行
		'se14e' => self::$pictograms['99'], // 信号
		'se14f' => self::$pictograms['208'], // 駐車場
		'se150' => self::$pictograms['209'], // バス停
		'se151' => self::$pictograms['207'], // 公衆トイレ
		'se152' => self::$pictograms['374'], // 交番
		'se153' => self::$pictograms['375'], // 郵便局
		'se154' => self::$pictograms['205'], // ATM
		'se155' => self::$pictograms['376'], // 病院
		'se156' => self::$pictograms['206'], // コンビニ
		'se157' => self::$pictograms['377'], // 学校
		'se158' => self::$pictograms['378'], // ホテル
		'se159' => self::$pictograms['216'], // バス
		'se15a' => self::$pictograms['125'], // タクシー
		'se201' => self::$pictograms['800'], // 徒歩
		'se202' => self::$pictograms['379'], // 船
		'se203' => '[ココ]', // 目的地 (ココ)
		'se204' => self::$pictograms['51'], // 飾罫1
		'se205' => self::$pictograms['267'], // 飾罫2
		'se206' => self::$pictograms['28'], // 飾罫3
		'se207' => self::$pictograms['380'], // 18禁
		'se208' => self::$pictograms['177'], // 禁煙
		'se209' => self::$pictograms['179'], // 初心者
		'se20a' => self::$pictograms['178'], // バリアフリー (車椅子マーク)
		'se20b' => self::$pictograms['381'], // アンテナマーク
		'se20c' => self::$pictograms['414'], // ハート (トランプ)
		'se20d' => self::$pictograms['315'], // ダイヤ (トランプ)
		'se20e' => self::$pictograms['314'], // スペード (トランプ)
		'se20f' => self::$pictograms['316'], // クラブ (トランプ)
		'se210' => self::$pictograms['818'], // シャープダイヤル
		'se211' => self::$pictograms['299'], // フリーダイヤル
		'se212' => self::$pictograms['334'], // 新着
		'se213' => self::$pictograms['303'], // 更新
		'se214' => self::$pictograms['382'], // おすすめ (COOL)
		'se215' => self::$pictograms['233'], // 有料
		'se216' => self::$pictograms['299'], // 無料
		'se217' => '[月]', // 月額
		'se218' => '[申]', // 申し込み
		'se219' => self::$pictograms['40'], // 見出しボタン1 (オレンジ)
		'se21a' => self::$pictograms['41'], // 見出しボタン2 (緑)
		'se21b' => self::$pictograms['41'], // 見出しボタン4 (紫)
		'se21c' => self::$pictograms['180'], // 1 (one)
		'se21d' => self::$pictograms['181'], // 2 (two)
		'se21e' => self::$pictograms['182'], // 3 (three)
		'se21f' => self::$pictograms['183'], // 4 (four)
		'se220' => self::$pictograms['184'], // 5 (five)
		'se221' => self::$pictograms['185'], // 6 (six)
		'se222' => self::$pictograms['186'], // 7 (seven)
		'se223' => self::$pictograms['187'], // 8 (eight)
		'se224' => self::$pictograms['188'], // 9 (nine)
		'se225' => self::$pictograms['325'], // 0 (zero)
		'se226' => self::$pictograms['285'], // お得
		'se227' => self::$pictograms['383'], // 割引
		'se228' => self::$pictograms['384'], // サービス料
		'se229' => self::$pictograms['385'], // ID
		'se22a' => self::$pictograms['386'], // 満席
		'se22b' => self::$pictograms['387'], // 空席
		'se22c' => self::$pictograms['388'], // 指定席
		'se22d' => self::$pictograms['389'], // 営業時間
		'se22e' => self::$pictograms['390'], // 上へ (指)
		'se22f' => self::$pictograms['391'], // 下へ (指)
		'se230' => self::$pictograms['140'], // 左へ (指)
		'se231' => self::$pictograms['141'], // 右へ (指)
		'se232' => self::$pictograms['29'], // 上
		'se233' => self::$pictograms['30'], // 下
		'se234' => self::$pictograms['63'], // 右
		'se235' => self::$pictograms['64'], // 左
		'se236' => self::$pictograms['70'], // 右上
		'se237' => self::$pictograms['42'], // 左上
		'se238' => self::$pictograms['43'], // 右下
		'se239' => self::$pictograms['71'], // 左下
		'se23a' => self::$pictograms['6'], // 次へ
		'se23b' => self::$pictograms['5'], // 前へ
		'se23c' => self::$pictograms['8'], // 早送り 
		'se23d' => self::$pictograms['7'], // 巻き戻し
		'se23e' => self::$pictograms['392'], // 星座
		'se23f' => self::$pictograms['192'], // おひつじ座
		'se240' => self::$pictograms['193'], // おうし座
		'se241' => self::$pictograms['194'], // ふたご座
		'se242' => self::$pictograms['195'], // かに座
		'se243' => self::$pictograms['196'], // しし座
		'se244' => self::$pictograms['197'], // おとめ座
		'se245' => self::$pictograms['198'], // てんぴん座
		'se246' => self::$pictograms['199'], // さそり座
		'se247' => self::$pictograms['200'], // いて座
		'se248' => self::$pictograms['201'], // やぎ座
		'se249' => self::$pictograms['202'], // みずがめ座
		'se24a' => self::$pictograms['203'], // うお座
		'se24b' => self::$pictograms['204'], // へびつかい座
		'se24c' => '[TOP]', // TOPページ
		'se24d' => self::$pictograms['326'], // OKボタン
		'se24e' => self::$pictograms['81'], // 著作権 (C)
		'se24f' => self::$pictograms['82'], // 登録商標 (R)
		'se250' => self::$pictograms['393'], // マナーモード
		'se251' => self::$pictograms['394'], // 電源切
		'se252' => self::$pictograms['1'], // ご注意 (!)
		'se253' => self::$pictograms['50'], // ご案内
		'se254' => self::$pictograms['156'], // J-PHONEショップ
		'se255' => self::$pictograms['332'], // スカイウェブ
		'se256' => self::$pictograms['108'], // スカイウォーカー
		'se257' => self::$pictograms['343'] . self::$pictograms['784'], // スカイメロディ
		'se258' => 'J-', // J-PHONE 1
		'se259' => 'Pho', // J-PHONE 2
		'se25a' => 'ne', // J-PHONE 3
		'se301' => self::$pictograms['395'], // メモ
		'se302' => self::$pictograms['396'], // ネクタイ
		'se303' => self::$pictograms['397'], // ハイビスカス
		'se304' => self::$pictograms['113'], // チューリップ
		'se305' => self::$pictograms['256'], // ひまわり
		'se306' => self::$pictograms['398'], // 花束
		'se307' => self::$pictograms['255'], // やしの木
		'se308' => self::$pictograms['399'], // サボテン
		'se309' => self::$pictograms['207'], // トイレ
		'se30a' => self::$pictograms['294'], // ヘッドホン
		'se30b' => self::$pictograms['400'], // 晩酌 (とっくり)
		'se30c' => self::$pictograms['401'], // 乾杯 (ビール)
		'se30d' => self::$pictograms['402'], // 祝
		'se30e' => self::$pictograms['176'], // 喫煙
		'se30f' => self::$pictograms['403'], // カプセル薬
		'se310' => self::$pictograms['404'], // 風船
		'se311' => self::$pictograms['268'], // 爆弾
		'se312' => self::$pictograms['405'], // クラッカー
		'se313' => self::$pictograms['104'], // ハサミ
		'se314' => self::$pictograms['312'], // リボン
		'se315' => self::$pictograms['279'], // マル秘
		'se316' => self::$pictograms['126'], // MD
		'se317' => self::$pictograms['13'], // メガフォン
		'se318' => self::$pictograms['407'], // 帽子
		'se319' => self::$pictograms['793'], // 可愛いワンピース
		'se31a' => self::$pictograms['124'], // ミュール
		'se31b' => self::$pictograms['408'], // ロングブーツ
		'se31c' => self::$pictograms['295'], // 口紅
		'se31d' => self::$pictograms['409'], // マニキュア
		'se31e' => self::$pictograms['297'], // エステ
		'se31f' => self::$pictograms['410'], // 美容院
		'se320' => self::$pictograms['411'], // 理髪店
		'se321' => self::$pictograms['412'], // 着物
		'se322' => self::$pictograms['413'], // ビキニ
		'se323' => self::$pictograms['83'], // ブランドバッグ
		'se324' => self::$pictograms['226'], // カチンコ
		'se325' => self::$pictograms['48'], // すず
		'se326' => self::$pictograms['291'], // 踊る音符
		'se327' => self::$pictograms['415'], // ぴかぴかハート
		'se328' => self::$pictograms['803'], // ドキドキハート
		'se329' => self::$pictograms['272'], // ハートを射とめて
		'se32a' => self::$pictograms['416'], // ハート (青)
		'se32b' => self::$pictograms['417'], // ハート (緑)
		'se32c' => self::$pictograms['418'], // ハート (黄)
		'se32d' => self::$pictograms['419'], // ハート (紫)
		'se32e' => self::$pictograms['420'], // NEW (ぴかぴか)
		'se32f' => self::$pictograms['69'], // ☆
		'se330' => self::$pictograms['282'], // ダッシュ
		'se331' => self::$pictograms['330'], // 飛び散る汗
		'se332' => self::$pictograms['422'], // ○
		'se333' => self::$pictograms['61'], // ×
		'se334' => self::$pictograms['262'], // 怒り
		'se335' => self::$pictograms['69'], // ☆ (点滅)
		'se336' => self::$pictograms['3'], // 動く "?"
		'se337' => self::$pictograms['2'], // 動く "!"
		'se338' => self::$pictograms['423'], // お茶
		'se339' => self::$pictograms['424'], // パン
		'se33a' => self::$pictograms['425'], // ソフトクリーム
		'se33b' => self::$pictograms['426'], // フライドポテト
		'se33c' => self::$pictograms['427'], // 串団子 
		'se33d' => self::$pictograms['428'], // せんべい
		'se33e' => self::$pictograms['429'], // ご飯
		'se33f' => self::$pictograms['430'], // スパゲティ
		'se340' => self::$pictograms['333'], // ラーメン
		'se341' => self::$pictograms['431'], // カレーライス
		'se342' => self::$pictograms['244'], // おにぎり
		'se343' => self::$pictograms['432'], // おでん
		'se344' => self::$pictograms['433'], // 寿司
		'se345' => self::$pictograms['434'], // りんご
		'se346' => self::$pictograms['435'], // みかん
		'se347' => self::$pictograms['243'], // いちご
		'se348' => self::$pictograms['238'], // すいか
		'se349' => self::$pictograms['436'], // トマト
		'se34a' => self::$pictograms['437'], // なす
		'se34b' => self::$pictograms['313'], // バースデーケーキ
		'se34c' => self::$pictograms['438'], // 駅弁
		'se34d' => self::$pictograms['439'], // ナベ
		'se401' => self::$pictograms['351'], // あせり (顔)
		'se402' => self::$pictograms['440'], // ほそくんでいる (顔)
		'se403' => self::$pictograms['441'], // ひたすらごめんなさい (顔)
		'se404' => self::$pictograms['442'], // えっへん (顔)
		'se405' => self::$pictograms['348'], // ウィンク (顔)
		'se406' => self::$pictograms['443'], // わさびがきいた (顔)
		'se407' => self::$pictograms['444'], // 目がぐるぐる (顔)
		'se408' => self::$pictograms['445'], // 鼻ちょうちん (顔)
		'se409' => self::$pictograms['264'], // あっかんべー (顔)
		'se40a' => self::$pictograms['446'], // 酔っ払い (顔)
		'se40b' => self::$pictograms['447'], // ゲロゲロ (顔)
		'se40c' => self::$pictograms['448'], // マスクをつけた顔
		'se40d' => self::$pictograms['449'], // 顔があかくなる
		'se40e' => self::$pictograms['450'], // しらけ顔
		'se40f' => self::$pictograms['447'], // 冷や汗 (顔)
		'se410' => self::$pictograms['451'], // びっくり (顔)
		'se411' => self::$pictograms['259'], // 泣き (顔)
		'se412' => self::$pictograms['786'], // 泣いたり笑ったり (顔)
		'se413' => self::$pictograms['791'], // 可愛く泣いてる人
		'se414' => self::$pictograms['454'], // にこにこ (顔)
		'se415' => self::$pictograms['257'], // あははと笑う (顔)
		'se416' => self::$pictograms['779'], // めちゃめちゃ怒っている (顔)
		'se417' => self::$pictograms['455'], // KISS:動く口
		'se418' => self::$pictograms['456'], // 投げKISS
		'se419' => self::$pictograms['317'], // 目
		'se41a' => self::$pictograms['457'], // 鼻
		'se41b' => self::$pictograms['318'], // 耳
		'se41c' => self::$pictograms['458'], // 口
		'se41d' => self::$pictograms['459'], // ごめんなさい (合わせた手)
		'se41e' => self::$pictograms['463'], // バイバイ (手を振る)
		'se41f' => self::$pictograms['460'], // 拍手
		'se420' => self::$pictograms['461'], // OK (指で丸サイン)
		'se421' => self::$pictograms['462'], // Booing (親指を下)
		'se422' => self::$pictograms['460'], // おっは～
		'se423' => self::$pictograms['464'], // × (両腕をクロス)
		'se424' => self::$pictograms['465'], // ○ (両腕を頭に)
		'se425' => self::$pictograms['467'], // 手をつないでいる
		'se426' => self::$pictograms['466'], // 土下座
		'se427' => self::$pictograms['820'], // バンザイ
		'se428' => self::$pictograms['467'], // 人と人が歩いている
		'se429' => self::$pictograms['468'], // ラインダンス (バニーガール)
		'se42a' => self::$pictograms['307'], // バスケットボール
		'se42b' => self::$pictograms['96'], // フットボール
		'se42c' => self::$pictograms['470'], // ビリヤード
		'se42d' => self::$pictograms['471'], // 水泳
		'se42e' => self::$pictograms['125'], // RV車
		'se42f' => self::$pictograms['148'], // トラック
		'se430' => self::$pictograms['472'], // 消防車
		'se431' => self::$pictograms['473'], // 救急車
		'se432' => self::$pictograms['474'], // パトカー
		'se433' => self::$pictograms['475'], // ジェットコースター
		'se434' => self::$pictograms['341'], // 地下鉄
		'se435' => self::$pictograms['217'], // 新幹線(700系)
		'se436' => self::$pictograms['476'], // 門松
		'se437' => self::$pictograms['763'], // チョコ
		'se438' => self::$pictograms['477'], // お雛様
		'se439' => self::$pictograms['478'], // 卒業式
		'se43a' => self::$pictograms['479'], // ランドセル
		'se43b' => self::$pictograms['480'], // 鯉のぼり
		'se43c' => self::$pictograms['481'], // とじかさ
		'se43d' => self::$pictograms['340'], // 結婚式
		'se43e' => self::$pictograms['810'], // 波がザーン
		'se43f' => self::$pictograms['483'], // かき氷
		'se440' => self::$pictograms['484'], // 線香花火
		'se441' => self::$pictograms['485'], // 貝
		'se442' => self::$pictograms['486'], // 風鈴
		'se443' => self::$pictograms['190'], // 台風
		'se444' => '[稲穂]', // 稲穂
		'se445' => self::$pictograms['487'], // ハロウィン
		'se446' => self::$pictograms['488'], // お月見
		'se447' => self::$pictograms['358'], // 風がビュー
		'se448' => self::$pictograms['489'], // サンタクロース
		'se449' => self::$pictograms['493'], // 朝日
		'se44a' => self::$pictograms['371'], // 夕日
		'se44b' => self::$pictograms['490'], // 流れ星
		'se44c' => self::$pictograms['491'], // 虹
		'se501' => self::$pictograms['492'], // ラブホテル
		'se502' => self::$pictograms['309'], // アート
		'se503' => self::$pictograms['494'], // 演劇
		'se504' => self::$pictograms['495'], // デパート
		'se505' => self::$pictograms['496'], // お城 (和)
		'se506' => self::$pictograms['497'], // お城 (洋)
		'se507' => self::$pictograms['110'], // 映画館
		'se508' => self::$pictograms['498'], // 工場
		'se509' => self::$pictograms['228'], // 東京タワー
		'se50a' => self::$pictograms['495'], // 109
		'se50b' => self::$pictograms['237'], // 日本 (国旗)
		'se50c' => self::$pictograms['90'], // アメリカ (国旗)
		'se50d' => self::$pictograms['499'], // フランス (国旗)
		'se50e' => self::$pictograms['700'], // ドイツ (国旗)
		'se50f' => self::$pictograms['701'], // イタリア (国旗)
		'se510' => self::$pictograms['702'], // イギリス (国旗)
		'se511' => self::$pictograms['366'], // スペイン (国旗)
		'se512' => self::$pictograms['367'], // ロシア (国旗)
		'se513' => self::$pictograms['703'], // 中国 (国旗)
		'se514' => self::$pictograms['704'], // 韓国 (国旗)
		'se515' => self::$pictograms['705'], // 白人
		'se516' => self::$pictograms['706'], // 中国人
		'se517' => self::$pictograms['707'], // インド人
		'se518' => self::$pictograms['708'], // おじいちゃん
		'se519' => self::$pictograms['709'], // おばあちゃん
		'se51a' => self::$pictograms['710'], // あかちゃん
		'se51b' => self::$pictograms['711'], // 安全第一
		'se51c' => self::$pictograms['712'], // お姫さま
		'se51d' => '[自由の女神]', // 自由の女神
		'se51e' => '[衛兵]', // 衛兵
		'se51f' => self::$pictograms['714'], // フラメンコ
		'se520' => self::$pictograms['713'], // イルカ
		'se521' => self::$pictograms['78'], // とり
		'se522' => self::$pictograms['715'], // 熱帯魚
		'se523' => self::$pictograms['78'], // ひよこ
		'se524' => '[ハムスター]', // ハムスター
		'se525' => self::$pictograms['716'], // けむし
		'se526' => self::$pictograms['717'], // ぞう
		'se527' => self::$pictograms['718'], // コアラ
		'se528' => self::$pictograms['249'], // チンパンジー
		'se529' => self::$pictograms['192'], // ひつじ
		'se52a' => self::$pictograms['134'], // おおかみ
		'se52b' => self::$pictograms['719'], // うし
		'se52c' => self::$pictograms['247'], // うさぎ
		'se52d' => self::$pictograms['720'], // へび
		'se52e' => self::$pictograms['721'], // にわとり
		'se52f' => self::$pictograms['722'], // いのしし
		'se530' => self::$pictograms['723'], // らくだ
		'se531' => self::$pictograms['250'], // かえる
		'se532' => self::$pictograms['724'], // A型
		'se533' => self::$pictograms['725'], // B型
		'se534' => self::$pictograms['727'], // AB型
		'se535' => self::$pictograms['726'], // O型
		'se536' => self::$pictograms['728'], // 足あと
		'se537' => self::$pictograms['54'], // TM (商標)
		'se538' => 'J-', 
		'se539' => 'Sky', 
		'se53a' => '“', 
		'se53b' => '”', 
		'se53c' => '◎V', 
		'se53d' => 'odaf', 
		'se53e' => 'one', 
		'd001'  => self::$pictograms['44'], // 晴れ
		'd002'  => self::$pictograms['107'], // 曇り
		'd003'  => self::$pictograms['95'], // 雨
		'd004'  => self::$pictograms['191'], // 雪 
		'd005'  => self::$pictograms['16'], // 雷
		'd006'  => self::$pictograms['190'], // 台風
		'd007'  => self::$pictograms['305'], // 霧
		'd008'  => self::$pictograms['481'], // 小雨
		'd009'  => self::$pictograms['192'], // 牡羊座
		'd010'  => self::$pictograms['193'], // 牡牛座
		'd011'  => self::$pictograms['194'], // 双子座
		'd012'  => self::$pictograms['195'], // 蟹座
		'd013'  => self::$pictograms['196'], // 獅子座
		'd014'  => self::$pictograms['197'], // 乙女座
		'd015'  => self::$pictograms['198'], // 天秤座
		'd016'  => self::$pictograms['199'], // 蠍座
		'd017'  => self::$pictograms['200'], // 射手座
		'd018'  => self::$pictograms['201'], // 山羊座
		'd019'  => self::$pictograms['202'], // 水瓶座
		'd020'  => self::$pictograms['203'], // 魚座
		'd021'  => self::$pictograms['335'], // スポーツ
		'd022'  => self::$pictograms['45'], // 野球
		'd023'  => self::$pictograms['306'], // ゴルフ
		'd024'  => self::$pictograms['220'], // テニス
		'd025'  => self::$pictograms['219'], // サッカー
		'd026'  => self::$pictograms['421'], // スキー
		'd027'  => self::$pictograms['307'], // バスケットボール
		'd028'  => self::$pictograms['222'], // モータースポーツ (チェッカーフラッグ)
		'd029'  => self::$pictograms['308'], // ポケットベル
		'd030'  => self::$pictograms['172'], // 電車
		'd031'  => self::$pictograms['341'], // 地下鉄
		'd032'  => self::$pictograms['217'], // 新幹線
		'd033'  => self::$pictograms['125'], // 車 (セダン)
		'd034'  => self::$pictograms['125'], // 車 (RV)
		'd035'  => self::$pictograms['216'], // バス
		'd036'  => self::$pictograms['379'], // 船
		'd037'  => self::$pictograms['168'], // 飛行機
		'd038'  => self::$pictograms['112'], // 家
		'd039'  => self::$pictograms['156'], // ビル
		'd040'  => self::$pictograms['375'], // 郵便局
		'd041'  => self::$pictograms['376'], // 病院
		'd042'  => self::$pictograms['212'], // 銀行
		'd043'  => self::$pictograms['205'], // ATM
		'd044'  => self::$pictograms['378'], // ホテル
		'd045'  => self::$pictograms['206'], // コンビニ
		'd046'  => self::$pictograms['213'], // ガソリンスタンド
		'd047'  => self::$pictograms['208'], // 駐車場
		'd048'  => self::$pictograms['99'], // 信号
		'd049'  => self::$pictograms['207'], // トイレ
		'd050'  => self::$pictograms['146'], // レストラン
		'd051'  => self::$pictograms['93'], // 喫茶店
		'd052'  => self::$pictograms['52'], // バー (マティーニ)
		'd053'  => self::$pictograms['401'], // ビール
		'd054'  => self::$pictograms['245'], // ファーストフード (ハンバーガー)
		'd055'  => self::$pictograms['124'], // ブティック
		'd056'  => self::$pictograms['104'], // 美容院 (鋏)
		'd057'  => self::$pictograms['289'], // カラオケ
		'd058'  => self::$pictograms['110'], // 映画
		'd059'  => self::$pictograms['70'], // 右斜め上
		'd060'  => self::$pictograms['223'], // 遊園地 (木馬)
		'd061'  => self::$pictograms['294'], // 音楽 (ヘッドホン)
		'd062'  => self::$pictograms['309'], // アート
		'd063'  => self::$pictograms['310'], // 演劇
		'd064'  => self::$pictograms['311'], // イベント (サーカス)
		'd065'  => self::$pictograms['106'], // チケット
		'd066'  => self::$pictograms['176'], // 喫煙
		'd067'  => self::$pictograms['177'], // 禁煙
		'd068'  => self::$pictograms['94'], // カメラ
		'd069'  => self::$pictograms['83'], // カバン
		'd070'  => self::$pictograms['97'], // 本
		'd071'  => self::$pictograms['312'], // リボン
		'd072'  => self::$pictograms['144'], // プレゼント
		'd073'  => self::$pictograms['313'], // バースデー
		'd074'  => self::$pictograms['85'], // 電話
		'd075'  => self::$pictograms['161'], // 携帯電話
		'd076'  => self::$pictograms['56'], // メモ
		'd077'  => self::$pictograms['288'], // TV
		'd078'  => self::$pictograms['232'], // ゲーム
		'd079'  => self::$pictograms['300'], // CD
		'd080'  => self::$pictograms['414'], // ハート
		'd081'  => self::$pictograms['314'], // スペード
		'd082'  => self::$pictograms['315'], // ダイヤ
		'd083'  => self::$pictograms['316'], // クラブ
		'd084'  => self::$pictograms['317'], // 目
		'd085'  => self::$pictograms['318'], // 耳
		'd086'  => self::$pictograms['817'], // 手 (グー)
		'd087'  => self::$pictograms['319'], // 手 (チョキ)
		'd088'  => self::$pictograms['320'], // 手 (パー)
		'd089'  => self::$pictograms['43'], // 右斜め下
		'd090'  => self::$pictograms['42'], // 左斜め上
		'd091'  => self::$pictograms['728'], // 足
		'd092'  => self::$pictograms['336'], // くつ
		'd093'  => self::$pictograms['116'], // 眼鏡
		'd094'  => self::$pictograms['178'], // 車椅子
		'd095'  => self::$pictograms['321'], // 新月
		'd096'  => self::$pictograms['322'], // やや欠け月
		'd097'  => self::$pictograms['323'], // 半月
		'd098'  => self::$pictograms['15'], // 三日月
		'd099'  => self::$pictograms['488'], // 満月
		'd100'  => self::$pictograms['134'], // 犬
		'd101'  => self::$pictograms['251'], // 猫
		'd102'  => self::$pictograms['169'], // リゾート (ヨット)
		'd103'  => self::$pictograms['234'], // クリスマス
		'd104'  => self::$pictograms['71'], // 左斜め下
		'd105'  => self::$pictograms['161'], // phone to
		'd106'  => self::$pictograms['784'], // mail to
		'd107'  => self::$pictograms['166'], // fax to
		'd108'  => '[i]', // iモード
		'd109'  => '[i]', // iモード (枠付き)
		'd110'  => self::$pictograms['108'], // メール
		'd111'  => '[ドコモ提供]', // ドコモ提供
		'd112'  => '[D]', // ドコモポイント
		'd113'  => self::$pictograms['109'], // 有料
		'd114'  => self::$pictograms['299'], // 無料
		'd115'  => self::$pictograms['385'], // ID
		'd116'  => self::$pictograms['120'], // パスワード
		'd117'  => self::$pictograms['118'], // 次項有
		'd118'  => self::$pictograms['324'], // クリア
		'd119'  => self::$pictograms['119'], // サーチ (調べる)
		'd120'  => self::$pictograms['334'], // NEW
		'd121'  => self::$pictograms['210'], // 位置情報
		'd122'  => self::$pictograms['299'], // フリーダイヤル
		'd123'  => self::$pictograms['818'], // シャープダイヤル
		'd124'  => self::$pictograms['4'], // モバQ
		'd125'  => self::$pictograms['180'], // 1 (one)
		'd126'  => self::$pictograms['181'], // 2 (two)
		'd127'  => self::$pictograms['182'], // 3 (three)
		'd128'  => self::$pictograms['183'], // 4 (four)
		'd129'  => self::$pictograms['184'], // 5 (five)
		'd130'  => self::$pictograms['185'], // 6 (six)
		'd131'  => self::$pictograms['186'], // 7 (seven)
		'd132'  => self::$pictograms['187'], // 8 (eight)
		'd133'  => self::$pictograms['188'], // 9 (nine)
		'd134'  => self::$pictograms['325'], // 0 (zero)
		'd135'  => self::$pictograms['326'], // 決定 (OK)
		'd136'  => self::$pictograms['51'], // 黒ハート
		'd137'  => self::$pictograms['803'], // 揺れるハート
		'd138'  => self::$pictograms['265'], // 失恋
		'd139'  => self::$pictograms['266'], // ハートたち (複数ハート)
		'd140'  => self::$pictograms['257'], // わーい (嬉しい顔)
		'd141'  => self::$pictograms['258'], // ちっ (怒った顔)
		'd142'  => self::$pictograms['443'], // がく～ (落胆した顔)
		'd143'  => self::$pictograms['259'], // もうやだ～ (悲しい顔)
		'd144'  => self::$pictograms['260'], // ふらふら
		'd145'  => self::$pictograms['731'], // グッド (上向き矢印)
		'd146'  => self::$pictograms['343'], // るんるん (音符)
		'd147'  => self::$pictograms['224'], // いい気分 (温泉)
		'd148'  => self::$pictograms['759'], // かわいい
		'd149'  => self::$pictograms['273'], // キスマーク
		'd150'  => self::$pictograms['76'], // ぴかぴか (新しい)
		'd151'  => self::$pictograms['77'], // ひらめき
		'd152'  => self::$pictograms['262'], // むかっ (怒り)
		'd153'  => self::$pictograms['281'], // パンチ
		'd154'  => self::$pictograms['268'], // 爆弾
		'd155'  => self::$pictograms['291'], // ムード
		'd156'  => self::$pictograms['732'], // バッド (下向き矢印)
		'd157'  => self::$pictograms['261'], // 眠い (睡眠)
		'd158'  => self::$pictograms['2'], // exclamation
		'd159'  => self::$pictograms['733'], // exclamation and question
		'd160'  => self::$pictograms['734'], // double exclamation
		'd161'  => self::$pictograms['329'], // どんっ (衝撃)
		'd162'  => self::$pictograms['330'], // あせあせ (飛び散る汗)
		'd163'  => self::$pictograms['263'], // たらーっ (汗)
		'd164'  => self::$pictograms['282'], // ダッシュ (走り出すさま)
		'd165'  => '～～', // ー (長音記号1)
		'd166'  => self::$pictograms['735'], // ー (長音記号2)
		'd167'  => self::$pictograms['226'], // カチンコ
		'd168'  => self::$pictograms['233'], // ふくろ
		'd169'  => self::$pictograms['508'], // ペン
		'd170'  => self::$pictograms['257'], // 人影
		'd171'  => '[椅子]', // いす
		'd172'  => self::$pictograms['490'], // 夜
		'd173'  => '→SOON', // soon
		'd174'  => '←ON→', // on
		'd175'  => 'END←', // end
		'd176'  => self::$pictograms['46'], // 時計
		'd201'  => 'α', // iアプリ
		'd202'  => '[α]', // iアプリ (枠付き)
		'd203'  => self::$pictograms['335'], // Tシャツ (ボーダー)
		'd204'  => self::$pictograms['290'], // がま口財布
		'd205'  => self::$pictograms['295'], // 化粧
		'd206'  => self::$pictograms['805'], // ジーンズ
		'd207'  => self::$pictograms['221'], // スノボ
		'd208'  => self::$pictograms['48'], // チャペル
		'd209'  => '[ドア]', // ドア
		'd210'  => self::$pictograms['233'], // ドル袋
		'd211'  => self::$pictograms['337'], // パソコン
		'd212'  => self::$pictograms['806'], // ラブレター
		'd213'  => self::$pictograms['152'], // レンチ
		'd214'  => self::$pictograms['149'], // 鉛筆
		'd215'  => self::$pictograms['354'], // 王冠
		'd216'  => self::$pictograms['72'], // 指輪
		'd217'  => self::$pictograms['57'], // 砂時計
		'd218'  => self::$pictograms['215'], // 自転車
		'd219'  => self::$pictograms['423'], // 湯のみ
		'd220'  => self::$pictograms['25'], // 腕時計
		'd221'  => self::$pictograms['351'], // 考えてる顔
		'd222'  => self::$pictograms['440'], // ほっとした顔
		'd223'  => self::$pictograms['452'], // 冷や汗 (顔)
		'd224'  => self::$pictograms['330'], // 冷や汗2 (顔)
		'd225'  => self::$pictograms['779'], // ぷっくっくな顔
		'd226'  => self::$pictograms['450'], // ボケーっとした顔
		'd227'  => self::$pictograms['349'], // 目がハート (顔)
		'd228'  => self::$pictograms['287'], // 指でOK
		'd229'  => self::$pictograms['264'], // あっかんべー
		'd230'  => self::$pictograms['348'], // ウィンク
		'd231'  => self::$pictograms['454'], // うれしい顔
		'd232'  => self::$pictograms['327'], // がまん顔
		'd233'  => self::$pictograms['251'], // 猫2
		'd234'  => self::$pictograms['786'], // 泣き顔
		'd235'  => self::$pictograms['791'], // 涙
		'd236'  => self::$pictograms['98'], // NG
		'd237'  => self::$pictograms['143'], // クリップ
		'd238'  => self::$pictograms['81'], // コピーライト (C)
		'd239'  => self::$pictograms['54'], // トレードマーク (TM)
		'd240'  => self::$pictograms['218'], // 走る人
		'd241'  => self::$pictograms['279'], // マル秘
		'd242'  => self::$pictograms['807'], // リサイクル
		'd243'  => self::$pictograms['82'], // レジスタードトレードマーク (R)
		'd244'  => self::$pictograms['1'], // 危険・警告 (!)
		'd245'  => self::$pictograms['98'], // 禁止
		'd246'  => self::$pictograms['387'], // 空室・空席・空車
		'd247'  => '[合格]', // 合格マーク
		'd248'  => self::$pictograms['386'], // 満室・満席・満車
		'd249'  => self::$pictograms['808'], // 矢印左右
		'd250'  => self::$pictograms['809'], // 矢印上下
		'd251'  => self::$pictograms['377'], // 学校
		'd252'  => self::$pictograms['810'], // 波
		'd253'  => self::$pictograms['342'], // 富士山
		'd254'  => self::$pictograms['53'], // クローバー
		'd255'  => self::$pictograms['241'], // さくらんぼ
		'd256'  => self::$pictograms['113'], // チューリップ
		'd257'  => self::$pictograms['739'], // バナナ
		'd258'  => self::$pictograms['434'], // りんご
		'd259'  => self::$pictograms['811'], // 芽
		'd260'  => self::$pictograms['133'], // もみじ
		'd261'  => self::$pictograms['235'], // 桜
		'd262'  => self::$pictograms['244'], // おにぎり
		'd263'  => self::$pictograms['239'], // ショートケーキ
		'd264'  => self::$pictograms['400'], // とっくり (おちょこ付き)
		'd265'  => self::$pictograms['333'], // どんぶり
		'd266'  => self::$pictograms['424'], // パン
		'd267'  => self::$pictograms['812'], // かたつむり
		'd268'  => self::$pictograms['78'], // ひよこ
		'd269'  => self::$pictograms['252'], // ペンギン
		'd270'  => self::$pictograms['715'], // 魚
		'd271'  => self::$pictograms['454'], // うまい! (顔)
		'd272'  => self::$pictograms['442'], // ウッシッシ (顔)
		'd273'  => self::$pictograms['248'], // ウマ
		'd274'  => self::$pictograms['254'], // ブタ
		'd275'  => self::$pictograms['12'], // ワイングラス
		'd276'  => self::$pictograms['350'], // げっそり (顔)
		'e253'  => self::$pictograms['284'], // 人差し指
		'e254'  => self::$pictograms['467'], // カップル
		'e255'  => self::$pictograms['179'], // 若葉マーク
		'e256'  => self::$pictograms['292'], // ギター
		'e257'  => self::$pictograms['373'], // 株価チャート
		'e258'  => self::$pictograms['98'], // 18歳以上禁止
		'e259'  => self::$pictograms['362'], // 麻雀牌
		'e260'  => self::$pictograms['332'], // コミュニティ
		'e261'  => self::$pictograms['420'], // ヒット
		'e262'  => self::$pictograms['171'], // 新聞
		'e263'  => self::$pictograms['489'], // サンタクロース
		'e264'  => self::$pictograms['163'], // 家族
		'e265'  => '　', // [未使用]
		'e266'  => self::$pictograms['233'], // コイン
		'e267'  => '　', // [未使用]
		'e268'  => '　', // [未使用]
		'e269'  => 'EM', // EMOBILE ロゴ (白地)
		'e270'  => 'EM', // EMOBILE ロゴ (赤地)
		'e271'  => '　', // [未使用]
		'e272'  => '　', // [未使用]
		'e273'  => '　', // [未使用]
		'e274'  => '　', // [未使用]
		'e275'  => '　', // [未使用]
		'e276'  => '　', // [未使用]
		'e277'  => '　', // [未使用]
		'e278'  => '　', // [未使用]
		'wf040' => self::$pictograms['51'], // ハート
		'wf041' => self::$pictograms['46'], // 時計
		'wf042' => self::$pictograms['85'], // 電話
		'wf043' => self::$pictograms['65'], // カップ
		'wf044' => '*', // *
		'wf045' => self::$pictograms['809'], // 上下 (矢印)
		'wf046' => self::$pictograms['808'], // 左右 (矢印)
		'wf047' => '(((', // 電波 (左)
		'wf048' => self::$pictograms['44'], // 晴れ
		'wf049' => self::$pictograms['95'], // 雨
		'wf04a' => self::$pictograms['107'], // 曇り
		'wf04b' => self::$pictograms['263'], // 涙
		'wf04c' => self::$pictograms['68'], // 笑顔
		'wf04d' => self::$pictograms['273'], // 口 (キスマーク)
		'wf04e' => self::$pictograms['291'], // メロディ (十六分音符)
		'wf04f' => self::$pictograms['125'], // 車
		'wf050' => self::$pictograms['172'], // 電車
		'wf051' => self::$pictograms['168'], // 飛行機
		'wf052' => '[バイク]'        , // バイク
		'wf053' => self::$pictograms['112'], // 家
		'wf054' => self::$pictograms['156'], // ビル
		'wf055' => self::$pictograms['319'], // ピース (手)
		'wf056' => self::$pictograms['146'], // ディナー (ナイフとフォーク)
		'wf057' => self::$pictograms['52'], // グラス
		'wf058' => self::$pictograms['791'], // 泣く (顔)
		'wf059' => self::$pictograms['113'], // チューリップ
		'wf05a' => self::$pictograms['45'], // 野球 (バット)
		'wf05b' => self::$pictograms['45'], // ボール
		'wf05c' => self::$pictograms['817'], // パンチ (手)
		'wf05d' => self::$pictograms['16'], // 雷
		'wf05e' => self::$pictograms['258'], // 怒った顔
		'wf05f' => self::$pictograms['401'], // ビール
		'wf060' => self::$pictograms['56'], // ノート
		'wf061' => self::$pictograms['149'], // ペン (鉛筆)
		'wf062' => self::$pictograms['286'], // ドクロ
		'wf063' => self::$pictograms['108'], // メール
		'wf064' => self::$pictograms['177'], // 禁煙
		'wf065' => self::$pictograms['48'], // ベル
		'wf066' => self::$pictograms['759'], // 花
		'wf067' => self::$pictograms['224'], // 温泉
		'wf068' => self::$pictograms['15'], // 月 (26日目)
		'wf069' => self::$pictograms['730'], // 旗
		'wf06a' => self::$pictograms['448'], // マスク (顔)
		'wf06b' => self::$pictograms['294'], // レコード
		'wf06c' => self::$pictograms['160'], // 肉
		'wf06d' => self::$pictograms['134'], // 犬
		'wf06e' => self::$pictograms['251'], // 猫
		'wf06f' => self::$pictograms['249'], // 猿
		'wf070' => self::$pictograms['717'], // 象
		'wf071' => self::$pictograms['352'], // たこ
		'wf072' => self::$pictograms['333'], // ヌードル
		'wf073' => self::$pictograms['289'], // マイク (カラオケ)
		'wf074' => self::$pictograms['262'], // むかっ (怒り)
		'wf075' => self::$pictograms['78'], // ひよこ
		'wf076' => self::$pictograms['445'], // 眠り顔
		'wf077' => self::$pictograms['93'], // コーヒー
		'wf078' => self::$pictograms['176'], // タバコ
		'wf079' => self::$pictograms['330'], // 汗
		'wf07a' => self::$pictograms['244'], // おにぎり
		'wf07b' => self::$pictograms['83'], // カバン
		'wf07c' => self::$pictograms['283'], // うんち
		'wf07d' => self::$pictograms['396'], // ネクタイ
		'wf07e' => self::$pictograms['335'], // シャツ
		'wf080' => self::$pictograms['238'], // すいか
		'wf081' => self::$pictograms['483'], // カキ氷
		'wf082' => self::$pictograms['413'], // ビキニ
		'wf083' => self::$pictograms['104'], // はさみ
		'wf084' => self::$pictograms['304'], // 注射
		'wf085' => self::$pictograms['211'], // 船 (錨)
		'wf086' => self::$pictograms['250'], // かえる
		'wf087' => self::$pictograms['320'], // バイバイ (手)
		'wf088' => self::$pictograms['265'], // 失恋
		'wf089' => self::$pictograms['315'], // ダイヤ (トランプ)
		'wf08a' => self::$pictograms['316'], // クローバー (トランプ)
		'wf08b' => self::$pictograms['314'], // スペード (トランプ)
		'wf08c' => self::$pictograms['143'], // クリップ
		'wf08d' => self::$pictograms['191'], // 雪だるま
		'wf08e' => self::$pictograms['313'], // ケーキ
		'wf08f' => self::$pictograms['434'], // りんご
		'wf090' => self::$pictograms['144'], // プレゼント
		'wf091' => self::$pictograms['233'], // お金 (ドル)
		'wf092' => '[EXIT]', // 出口
		'wf093' => '[ドア]', // 入り口
		'wf094' => self::$pictograms['80'], // おやじ
		'wf095' => self::$pictograms['161'], // PHS
		'wf096' => self::$pictograms['69'], // 星
		'wf097' => self::$pictograms['106'], // チケット
		'wf098' => self::$pictograms['266'], // 複数ハート
		'wf099' => self::$pictograms['77'], // ひらめき
		'wf09a' => self::$pictograms['276'], // 足跡
		'wf09b' => self::$pictograms['257'], // 笑顔
		'wf09c' => self::$pictograms['220'], // テニス
		'wf09d' => self::$pictograms['110'], // 映画
		'wf09e' => self::$pictograms['421'], // スキー
		'wf09f' => self::$pictograms['734'], // !!
		'wf0a0' => self::$pictograms['733'], // !?
		'wf0a1' => self::$pictograms['3'], // ?
		'wf0a2' => self::$pictograms['732'], // 下降 (矢印)
		'wf0a3' => self::$pictograms['731'], // 上昇 (矢印)
		'wf0a4' => self::$pictograms['287'], // グッド (親指)
		'wf0a5' => self::$pictograms['271'], // 力こぶ
		'wf0a6' => self::$pictograms['272'], // キューピット (ハートと矢)
		'wf0a7' => self::$pictograms['278'], // うずまき
		'wf0a8' => self::$pictograms['190'], // 台風
		'wf0a9' => self::$pictograms['379'], // 海
		'wf0aa' => self::$pictograms['751'], // サーフィン
		'wf0ab' => self::$pictograms['769'], // 山
		'wf0ac' => self::$pictograms['342'], // 富士山
		'wf0ad' => self::$pictograms['361'], // キャンプ
		'wf0ae' => self::$pictograms['358'], // 落ち葉
		'wf0af' => self::$pictograms['216'], // バス
		'wf0b0' => self::$pictograms['219'], // サッカー
		'wf0b1' => self::$pictograms['179'], // 初心者
		'wf0b2' => self::$pictograms['7'], // 巻き戻し
		'wf0b3' => self::$pictograms['8'], // 早送り
		'wf0b4' => '[重要]', // 重要
		'wf0b5' => self::$pictograms['98'], // 18禁
		'wf0b6' => self::$pictograms['1'], // 注意
		'wf0b7' => self::$pictograms['807'], // リサイクル
		'wf0b8' => self::$pictograms['381'], // 電界強度
		'wf0b9' => ')))', // 電波 (右)
		'wf0ba' => self::$pictograms['61'], // バツ
		'wf0bb' => self::$pictograms['81'], // コピーライト
		'wf0bc' => self::$pictograms['82'], // レジスタードトレードマーク
		'wf0bd' => self::$pictograms['229'], // スリーセブン
		'wf0be' => self::$pictograms['325'], // 0 (zero)
		'wf0bf' => self::$pictograms['180'], // 1 (one)
		'wf0c0' => self::$pictograms['181'], // 2 (two)
		'wf0c1' => self::$pictograms['182'], // 3 (three)
		'wf0c2' => self::$pictograms['183'], // 4 (four)
		'wf0c3' => self::$pictograms['184'], // 5 (five)
		'wf0c4' => self::$pictograms['185'], // 6 (six)
		'wf0c5' => self::$pictograms['186'], // 7 (seven)
		'wf0c6' => self::$pictograms['187'], // 8 (eight)
		'wf0c7' => self::$pictograms['188'], // 9 (nine)
		'wf0c8' => self::$pictograms['192'], // 牡羊座
		'wf0c9' => self::$pictograms['193'], // 牡牛座
		'wf0ca' => self::$pictograms['194'], // 双子座
		'wf0cb' => self::$pictograms['195'], // 蟹座
		'wf0cc' => self::$pictograms['196'], // 獅子座
		'wf0cd' => self::$pictograms['197'], // 乙女座
		'wf0ce' => self::$pictograms['198'], // 天秤座
		'wf0cf' => self::$pictograms['199'], // 蠍座
		'wf0d0' => self::$pictograms['204'], // へびつかい座
		'wf0d1' => self::$pictograms['200'], // 射手座
		'wf0d2' => self::$pictograms['201'], // 山羊座
		'wf0d3' => self::$pictograms['202'], // 水瓶座
		'wf0d4' => self::$pictograms['203'], // 魚座
		'wf0d5' => self::$pictograms['794'], // 地蔵
		'wf0d6' => self::$pictograms['245'], // マクドナルド
		'wf0d7' => self::$pictograms['245'], // モスバーガー
		'wf0d8' => '　', // [未使用]
		'wf0d9' => self::$pictograms['245'], // ロッテリア
		'wf0da' => '　', // [未使用]
		'wf0db' => self::$pictograms['93'], // ドトールコーヒー
		'wf0dc' => '　', // [未使用]
		'wf0dd' => '　', // [未使用]
		'wf0de' => '　', // [未使用]
		'wf0df' => '　', // [未使用]
		'wf0e0' => self::$pictograms['743'], // もも (バーミヤン?)
		'wf0e1' => '　', // [未使用]
		'wf0e2' => '　', // [未使用]
		'wf0e3' => self::$pictograms['146'], // びっくりドンキー
		'wf0e4' => '　', // [未使用]
		'wf0e5' => '　', // [未使用]
		'wf0e6' => '　', // [未使用]
		'wf0e7' => self::$pictograms['206'], // ローソン
		'wf0e8' => '　', // [未使用]
		'wf0e9' => self::$pictograms['206'], // am/pm
		'wf0ea' => '　', // [未使用]
		'wf0eb' => '　', // [未使用]
		'wf0ec' => '　', // [未使用]
		'wf0ed' => '　', // [未使用]
		'wf0ee' => '　', // [未使用]
		'wf0ef' => '　', // [未使用]
		'wf0f0' => self::$pictograms['495'], // 西武
		'wf0f1' => '　', // [未使用]
		'wf0f2' => '　', // [未使用]
		'wf0f3' => '　', // [未使用]
		'wf0f4' => '　', // [未使用]
		'wf0f5' => '　', // [未使用]
		'wf0f6' => '　', // [未使用]
		'wf0f7' => '　', // [未使用]
		'wf0f8' => '　', // [未使用]
		'wf0f9' => '　', // [未使用]
		'wf0fa' => '　', // [未使用]
		'wf0fb' => '　', // [未使用]
		'wf0fc' => self::$pictograms['134'], // ハチ公
		'wf140' => self::$pictograms['794'], // モヤイ
		'wf141' => '　', // [未使用]
		'wf142' => '　', // [未使用]
		'wf143' => '　', // [未使用]
		'wf144' => '　', // [未使用]
		'wf145' => '　', // [未使用]
		'wf146' => '　', // [未使用]
		'wf147' => '　', // [未使用]
		'wf148' => self::$pictograms['212'], // UFJ
		'wf149' => '　', // [未使用]
		'wf14a' => '　', // [未使用]
		'wf14b' => '　', // [未使用]
		'wf14c' => '　', // [未使用]
		'wf14d' => '[EXIT]', // 非常口
		'wf14e' => '　', // [未使用]
		'wf14f' => '　', // [未使用]
		'wf150' => self::$pictograms['259'], // 泣き顔
		'wf151' => '　', // [未使用]
		'wf152' => '　', // [未使用]
		'wf153' => '　', // [未使用]
		'wf154' => '　', // [未使用]
		'wf155' => '　', // [未使用]
		'wf156' => '　', // [未使用]
		'wf157' => '　', // [未使用]
		'wf158' => '　', // [未使用]
		'wf159' => '　', // [未使用]
		'wf15a' => '　', // [未使用]
		'wf15b' => '　', // [未使用]
		'wf15c' => '　', // [未使用]
		'wf15d' => '　', // [未使用]
		'wf15e' => '　', // [未使用]
		'wf15f' => '　', // [未使用]
	);
	$translated = apply_filters('ktai_pictogram_table', $translated, __CLASS__, $this->charset);
	$translated = apply_filters('pictogram_table/ktai_style.php', $translated);
	$buffer = preg_replace(
		'!<img localsrc="([^"]+)"( alt="(' . KtaiStyle::DOUBLE_QUOTED_STRING_REGEX . ')")?[^/>]*/?>!se', // <?php /* syntax hilighting fix */
		'isset($translated["$1"]) ? $translated["$1"] : ("$3" ? "$3" : "〓")', 
		$buffer);
	$entities = array(
		'&spades;' => self::$pictograms['314'],
		'&#9824;'  => self::$pictograms['314'],
		'&#x2660;' => self::$pictograms['314'],
		'&clubs;'  => self::$pictograms['316'],
		'&#9827;'  => self::$pictograms['316'],
		'&#x2663;' => self::$pictograms['316'],
		'&hearts;' => self::$pictograms['414'],
		'&#9829;'  => self::$pictograms['414'],
		'&#x2665;' => self::$pictograms['414'],
		'&#9825;'  => self::$pictograms['51'], // WHITE HEART
		'&#x2661;' => self::$pictograms['51'], // WHITE HEART
		'&diams;'  => self::$pictograms['315'],
		'&#9830;'  => self::$pictograms['315'],
		'&#x2666;' => self::$pictograms['315'],
		'&#12336;' => '～～', // WAVY DASH
		'&#x3030;' => '～～', // WAVY DASH
	);
	$buffer = str_replace(array_keys($entities), $entities, $buffer);
	return parent::convert_pict($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_pre_split($buffer) {
	$buffer = preg_replace('!<(b|i|em|strong)>(.*?)</\\1>!s', '$2', $buffer);
	return parent::shrink_pre_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function pickup_pics($buffer) {
	$pictograms = array_flip(self::$pictograms);
	if (! $pictograms || ! function_exists('mb_regex_encoding')) {
		return $buffer;
	}
	mb_regex_encoding($this->charset);
	$replaced = mb_ereg_replace(
		"([\xf3\x40-\xf3\x5b]|[\xf3\x5d-\xf3\xfc]|[\xf4\x40-\xf4\x5b]|[\xf4\x5d-\xf4\xfc]|[\xf6\x40-\xf6\x5b]|[\xf6\x5d-\xf6\xfc]|[\xf7\x40-\xf7\x5b]|[\xf7\x5d-\xf7\xfc])", 
		'isset($pictograms["\1"]) ?
		"<img localsrc=\"" . $pictograms["\1"] . "\" />" :
		"<img localsrc=\"ez\" alt=\"" . "[0x" . bin2hex("\1") . "]\" />"', 
		$buffer, 'e');
	if ($replaced) {
		$replaced = mb_ereg_replace("\xf3\x5c", '<img localsrc="' . $pictograms["\xf3\x5c"] . '" />', $replaced);
		$replaced = mb_ereg_replace("\xf4\x5c", '<img localsrc="' . $pictograms["\xf4\x5c"] . '" />', $replaced);
		$replaced = mb_ereg_replace("\xf6\x5c", '<img localsrc="' . $pictograms["\xf6\x5c"] . '" />', $replaced);
		$replaced = mb_ereg_replace("\xf7\x5c", '<img localsrc="' . $pictograms["\xf7\x5c"] . '" />', $replaced);
	}
	return $replaced ? $replaced : $buffer;
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_EZweb_HDML class
   ================================================== */

class KtaiService_EZweb_HDML extends KtaiService_EZweb {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->type = 'HDML';
	preg_match('!^UP\.Browser/\d\.\d+-([A-Za-z0-9]+) !', $user_agent, $specs);
	$device_ID = $specs[1];
	$this->term_name = isset(parent::$device_IDs[$device_ID][0]) ? parent::$device_IDs[$device_ID][0] : NULL;
	$this->flat_rate = isset(parent::$device_IDs[$device_ID][1]) ? parent::$device_IDs[$device_ID][1] : NULL;
	if ( !$this->term_name ) {
		$this->term_name = "(Unknown au device:$device_ID)";
		$this->flat_rate = false;
	}
	$this->ext_css_available = false;
	$this->textarea_size = 1024;
	$this->page_size  = 7500;
	$this->cache_size = (isset($_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU']) && $_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU'] > 0) ? intval($_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU']) : 49152;
	$this->xhtml_head = '';
	return;
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_EZweb_WAP2 class
   ================================================== */

class KtaiService_EZweb_WAP2 extends KtaiService_EZweb {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->type = 'WAP2.0';
	preg_match('!^KDDI-([A-Za-z0-9]+) !', $user_agent, $specs);
	$device_ID = $specs[1];
	$this->term_name = isset(parent::$device_IDs[$device_ID][0]) ? parent::$device_IDs[$device_ID][0] : NULL;
	$this->flat_rate = isset(parent::$device_IDs[$device_ID][1]) ? parent::$device_IDs[$device_ID][1] : NULL;
	if ( !$this->term_name ) {
		$this->term_name = "(Unknown au device:$device_ID)";
		$this->flat_rate = true;
	}
	$this->ext_css_available = true;
	$this->available_js_version = false;
	$this->textarea_size = 1024;
	$this->cache_size = (isset($_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU']) && $_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU'] > 0) ? intval($_SERVER['HTTP_X_UP_DEVCAP_MAX_PDU'] * 0.96) : 102400;
	$this->page_size  = min(20000, $this->cache_size);
	$this->xhtml_head = '<html xmlns="http://www.w3.org/1999/xhtml">';
	add_action('ktai_wp_head', array($this, 'paragraph_margin') );
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
	$buffer = $this->font_to_big_small($buffer);
	if ($this->mime_type == 'application/xhtml+xml') {
		$buffer = $this->input_to_style($buffer);
	}
	return parent::shrink_post_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
protected function font_to_big_small($buffer) {
	$buffer = str_replace(array("\375", "\376"), array('', ''), $buffer);
	$buffer = str_replace(array('<font', '</font>'), array("\375", "\376"), $buffer, $num_replaced);
	$loop = 0;
	while (preg_match('!\\375([^<>]*)>([^\\375\\376]*?)\\376!s', $buffer, $f)) {
		if ($loop++ > $num_replaced) { // infinity loop check
			break;
		}
		$attr       = $f[1];
		$html       = $f[2];
		if (preg_match('/ ?size=([\'"])([-+])1\\1/', $attr, $size)) { //"
			$attr = str_replace($size[0], '', $attr);
			$elem = ($size[2] == '+') ? 'big' : 'small';
			if (preg_match('/^\s*$/', $attr)) {
				$html ="<$elem>" . $html . "</$elem>";
			} else {
				$html = "<$elem><font$attr>" . $html . "</font></$elem>";
			}
		} else {
			$html = str_replace(array("\375", "\376"), array('<font', '</font>'), $f[0]);
		}
		$buffer = preg_replace('!' . preg_quote($f[0], '!') . '!', $html, $buffer, 1);
	}
	$buffer = str_replace(array("\375", "\376"), array('<font', '</font>'), $buffer, $num_replaced); // restore rest font tags
	return $buffer;
}

/* ==================================================
 * @param	none
 * @return	none
 * @since	2.0.0
 */
public function paragraph_margin() {
	echo '<style type="text/css"><![CDATA[ p {margin:0.75em 0;} ]]></style>' . "\n";
}

// ===== End of class ====================
}
?>