<?php
/* これは文字化け防止のための日本語文字列です。
   このソースファイルは Shift_JIS で保存されています。
   Above is a Japanese strings to avoid charset mis-understanding.
   This source file is saved with Shift_JIS.

   ***** DO NOT EDIT THIS FILE WITH WORDPRESS ADMIN PANEL *****
*/

/* ==================================================
 *   KtaiService_imode class
   ================================================== */

if ( !defined('KTAI_IMODE_UID') ) {
	define('KTAI_IMODE_UID', false);
}

class KtaiService_imode extends KtaiServices {
	static public $networks;
	static public $pictograms;

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->operator = 'DoCoMo';
	$this->image_pictograms = false;
	$this->use_redir = true;
	$this->show_plugin_icon = false;
	$this->pcview_enabled = false;
	$this->sub_ID_available = true;
	if ( KTAI_IMODE_UID ) {
		$this->sub_ID = ( isset($_GET['uid']) && preg_match('/^\d+$/', $_GET['uid']) ) ? $_GET['uid'] : NULL;
	} else {
		$this->sub_ID = isset($_SERVER['HTTP_X_DCMGUID']) ? $_SERVER['HTTP_X_DCMGUID'] : NULL;
	}
	$this->cookie_available = false;
	$this->ext_css_available = false;
	$this->available_js_version = false;
	$this->charset = 'SJIS-win';
	$this->mime_type = 'text/html';
	$this->require_id_msg = "ERROR: Please send your mobile phone info, or configure to notify your i-mode ID.\nGo iMenu &gt; Charges &amp;Apply/Prefs &gt; 4.Options &gt; i-mode ID notify preference.";
	// http://www.nttdocomo.co.jp/service/imode/make/content/pictograph/basic/

	// http://www.nttdocomo.co.jp/service/imode/make/content/ip/
	// Last Update: 2010-11
	$this->networks = array(
		'210.153.84.0/24',
		'210.136.161.0/24',
		'210.153.86.0/24',
		'124.146.174.0/24', // Since 2008-10-10
		'124.146.175.0/24', // Since 2009-12-15
		'202.229.176.0/24', // Since 2010-May
		'202.229.177.0/24', // Since 2010-May
		'202.229.178.0/24', // Since 2010-May
	);
	// http://www.nttdocomo.co.jp/service/imode/make/content/pictograph/
	self::$pictograms = array(
		'd001' => "\xf8\x9f", // 晴れ
		'd002' => "\xf8\xa0", // 曇り
		'd003' => "\xf8\xa1", // 雨
		'd004' => "\xf8\xa2", // 雪 
		'd005' => "\xf8\xa3", // 雷
		'd006' => "\xf8\xa4", // 台風
		'd007' => "\xf8\xa5", // 霧
		'd008' => "\xf8\xa6", // 小雨
		'd009' => "\xf8\xa7", // 牡羊座
		'd010' => "\xf8\xa8", // 牡牛座
		'd011' => "\xf8\xa9", // 双子座
		'd012' => "\xf8\xaa", // 蟹座
		'd013' => "\xf8\xab", // 獅子座
		'd014' => "\xf8\xac", // 乙女座
		'd015' => "\xf8\xad", // 天秤座
		'd016' => "\xf8\xae", // 蠍座
		'd017' => "\xf8\xaf", // 射手座
		'd018' => "\xf8\xb0", // 山羊座
		'd019' => "\xf8\xb1", // 水瓶座
		'd020' => "\xf8\xb2", // 魚座
		'd021' => "\xf8\xb3", // スポーツ
		'd022' => "\xf8\xb4", // 野球
		'd023' => "\xf8\xb5", // ゴルフ
		'd024' => "\xf8\xb6", // テニス
		'd025' => "\xf8\xb7", // サッカー
		'd026' => "\xf8\xb8", // スキー
		'd027' => "\xf8\xb9", // バスケットボール
		'd028' => "\xf8\xba", // モータースポーツ (チェッカーフラッグ)
		'd029' => "\xf8\xbb", // ポケットベル
		'd030' => "\xf8\xbc", // 電車
		'd031' => "\xf8\xbd", // 地下鉄
		'd032' => "\xf8\xbe", // 新幹線
		'd033' => "\xf8\xbf", // 車 (セダン)
		'd034' => "\xf8\xc0", // 車 (RV)
		'd035' => "\xf8\xc1", // バス
		'd036' => "\xf8\xc2", // 船
		'd037' => "\xf8\xc3", // 飛行機
		'd038' => "\xf8\xc4", // 家
		'd039' => "\xf8\xc5", // ビル
		'd040' => "\xf8\xc6", // 郵便局
		'd041' => "\xf8\xc7", // 病院
		'd042' => "\xf8\xc8", // 銀行
		'd043' => "\xf8\xc9", // ATM
		'd044' => "\xf8\xca", // ホテル
		'd045' => "\xf8\xcb", // コンビニ
		'd046' => "\xf8\xcc", // ガソリンスタンド
		'd047' => "\xf8\xcd", // 駐車場
		'd048' => "\xf8\xce", // 信号
		'd049' => "\xf8\xcf", // トイレ
		'd050' => "\xf8\xd0", // レストラン
		'd051' => "\xf8\xd1", // 喫茶店
		'd052' => "\xf8\xd2", // バー (マティーニ)
		'd053' => "\xf8\xd3", // ビール
		'd054' => "\xf8\xd4", // ファーストフード (ハンバーガー)
		'd055' => "\xf8\xd5", // ブティック
		'd056' => "\xf8\xd6", // 美容院 (鋏)
		'd057' => "\xf8\xd7", // カラオケ
		'd058' => "\xf8\xd8", // 映画
		'd059' => "\xf8\xd9", // 右斜め上
		'd060' => "\xf8\xda", // 遊園地 (木馬)
		'd061' => "\xf8\xdb", // 音楽 (ヘッドホン)
		'd062' => "\xf8\xdc", // アート
		'd063' => "\xf8\xdd", // 演劇
		'd064' => "\xf8\xde", // イベント (サーカス)
		'd065' => "\xf8\xdf", // チケット
		'd066' => "\xf8\xe0", // 喫煙
		'd067' => "\xf8\xe1", // 禁煙
		'd068' => "\xf8\xe2", // カメラ
		'd069' => "\xf8\xe3", // カバン
		'd070' => "\xf8\xe4", // 本
		'd071' => "\xf8\xe5", // リボン
		'd072' => "\xf8\xe6", // プレゼント
		'd073' => "\xf8\xe7", // バースデー
		'd074' => "\xf8\xe8", // 電話
		'd075' => "\xf8\xe9", // 携帯電話
		'd076' => "\xf8\xea", // メモ
		'd077' => "\xf8\xeb", // TV
		'd078' => "\xf8\xec", // ゲーム
		'd079' => "\xf8\xed", // CD
		'd080' => "\xf8\xee", // ハート
		'd081' => "\xf8\xef", // スペード
		'd082' => "\xf8\xf0", // ダイヤ
		'd083' => "\xf8\xf1", // クラブ
		'd084' => "\xf8\xf2", // 目
		'd085' => "\xf8\xf3", // 耳
		'd086' => "\xf8\xf4", // 手 (グー)
		'd087' => "\xf8\xf5", // 手 (チョキ)
		'd088' => "\xf8\xf6", // 手 (パー)
		'd089' => "\xf8\xf7", // 右斜め下
		'd090' => "\xf8\xf8", // 左斜め上
		'd091' => "\xf8\xf9", // 足
		'd092' => "\xf8\xfa", // くつ
		'd093' => "\xf8\xfb", // 眼鏡
		'd094' => "\xf8\xfc", // 車椅子
		'd095' => "\xf9\x40", // 新月
		'd096' => "\xf9\x41", // やや欠け月
		'd097' => "\xf9\x42", // 半月
		'd098' => "\xf9\x43", // 三日月
		'd099' => "\xf9\x44", // 満月
		'd100' => "\xf9\x45", // 犬
		'd101' => "\xf9\x46", // 猫
		'd102' => "\xf9\x47", // リゾート (ヨット)
		'd103' => "\xf9\x48", // クリスマス
		'd104' => "\xf9\x49", // 左斜め下
		'd105' => "\xf9\x72", // phone to
		'd106' => "\xf9\x73", // mail to
		'd107' => "\xf9\x74", // fax to
		'd108' => "\xf9\x75", // iモード
		'd109' => "\xf9\x76", // iモード (枠付き)
		'd110' => "\xf9\x77", // メール
		'd111' => "\xf9\x78", // ドコモ提供
		'd112' => "\xf9\x79", // ドコモポイント
		'd113' => "\xf9\x7a", // 有料
		'd114' => "\xf9\x7b", // 無料
		'd115' => "\xf9\x7c", // ID
		'd116' => "\xf9\x7d", // パスワード
		'd117' => "\xf9\x7e", // 次項有
		'd118' => "\xf9\x80", // クリア
		'd119' => "\xf9\x81", // サーチ (調べる)
		'd120' => "\xf9\x82", // NEW
		'd121' => "\xf9\x83", // 位置情報
		'd122' => "\xf9\x84", // フリーダイヤル
		'd123' => "\xf9\x85", // シャープダイヤル
		'd124' => "\xf9\x86", // モバQ
		'd125' => "\xf9\x87", // 1 (one)
		'd126' => "\xf9\x88", // 2 (two)
		'd127' => "\xf9\x89", // 3 (three)
		'd128' => "\xf9\x8a", // 4 (four)
		'd129' => "\xf9\x8b", // 5 (five)
		'd130' => "\xf9\x8c", // 6 (six)
		'd131' => "\xf9\x8d", // 7 (seven)
		'd132' => "\xf9\x8e", // 8 (eight)
		'd133' => "\xf9\x8f", // 9 (nine)
		'd134' => "\xf9\x90", // 0 (zero)
		'd135' => "\xf9\xb0", // 決定 (OK)
		'd136' => "\xf9\x91", // 黒ハート
		'd137' => "\xf9\x92", // 揺れるハート
		'd138' => "\xf9\x93", // 失恋
		'd139' => "\xf9\x94", // ハートたち (複数ハート)
		'd140' => "\xf9\x95", // わーい (嬉しい顔)
		'd141' => "\xf9\x96", // ちっ (怒った顔)
		'd142' => "\xf9\x97", // がく～ (落胆した顔)
		'd143' => "\xf9\x98", // もうやだ～ (悲しい顔)
		'd144' => "\xf9\x99", // ふらふら
		'd145' => "\xf9\x9a", // グッド (上向き矢印)
		'd146' => "\xf9\x9b", // るんるん (音符)
		'd147' => "\xf9\x9c", // いい気分 (温泉)
		'd148' => "\xf9\x9d", // かわいい
		'd149' => "\xf9\x9e", // キスマーク
		'd150' => "\xf9\x9f", // ぴかぴか (新しい)
		'd151' => "\xf9\xa0", // ひらめき
		'd152' => "\xf9\xa1", // むかっ (怒り)
		'd153' => "\xf9\xa2", // パンチ
		'd154' => "\xf9\xa3", // 爆弾
		'd155' => "\xf9\xa4", // ムード
		'd156' => "\xf9\xa5", // バッド (下向き矢印)
		'd157' => "\xf9\xa6", // 眠い (睡眠)
		'd158' => "\xf9\xa7", // exclamation
		'd159' => "\xf9\xa8", // exclamation and question
		'd160' => "\xf9\xa9", // double exclamation
		'd161' => "\xf9\xaa", // どんっ (衝撃)
		'd162' => "\xf9\xab", // あせあせ (飛び散る汗)
		'd163' => "\xf9\xac", // たらーっ (汗)
		'd164' => "\xf9\xad", // ダッシュ (走り出すさま)
		'd165' => "\xf9\xae", // ー (長音記号1)
		'd166' => "\xf9\xaf", // ー (長音記号2)
		'd167' => "\xf9\x50", // カチンコ
		'd168' => "\xf9\x51", // ふくろ
		'd169' => "\xf9\x52", // ペン
		'd170' => "\xf9\x55", // 人影
		'd171' => "\xf9\x56", // いす
		'd172' => "\xf9\x57", // 夜
		'd173' => "\xf9\x5b", // soon
		'd174' => "\xf9\x5c", // on
		'd175' => "\xf9\x5d", // end
		'd176' => "\xf9\x5e", // 時計
		'd201' => "\xf9\xb1", // iアプリ
		'd202' => "\xf9\xb2", // iアプリ (枠付き)
		'd203' => "\xf9\xb3", // Tシャツ (ボーダー)
		'd204' => "\xf9\xb4", // がま口財布
		'd205' => "\xf9\xb5", // 化粧
		'd206' => "\xf9\xb6", // ジーンズ
		'd207' => "\xf9\xb7", // スノボ
		'd208' => "\xf9\xb8", // チャペル
		'd209' => "\xf9\xb9", // ドア
		'd210' => "\xf9\xba", // ドル袋
		'd211' => "\xf9\xbb", // パソコン
		'd212' => "\xf9\xbc", // ラブレター
		'd213' => "\xf9\xbd", // レンチ
		'd214' => "\xf9\xbe", // 鉛筆
		'd215' => "\xf9\xbf", // 王冠
		'd216' => "\xf9\xc0", // 指輪
		'd217' => "\xf9\xc1", // 砂時計
		'd218' => "\xf9\xc2", // 自転車
		'd219' => "\xf9\xc3", // 湯のみ
		'd220' => "\xf9\xc4", // 腕時計
		'd221' => "\xf9\xc5", // 考えてる顔
		'd222' => "\xf9\xc6", // ほっとした顔
		'd223' => "\xf9\xc7", // 冷や汗 (顔)
		'd224' => "\xf9\xc8", // 冷や汗2 (顔)
		'd225' => "\xf9\xc9", // ぷっくっくな顔
		'd226' => "\xf9\xca", // ボケーっとした顔
		'd227' => "\xf9\xcb", // 目がハート (顔)
		'd228' => "\xf9\xcc", // 指でOK
		'd229' => "\xf9\xcd", // あっかんべー
		'd230' => "\xf9\xce", // ウィンク
		'd231' => "\xf9\xcf", // うれしい顔
		'd232' => "\xf9\xd0", // がまん顔
		'd233' => "\xf9\xd1", // 猫2
		'd234' => "\xf9\xd2", // 泣き顔
		'd235' => "\xf9\xd3", // 涙
		'd236' => "\xf9\xd4", // NG
		'd237' => "\xf9\xd5", // クリップ
		'd238' => "\xf9\xd6", // コピーライト (C)
		'd239' => "\xf9\xd7", // トレードマーク (TM)
		'd240' => "\xf9\xd8", // 走る人
		'd241' => "\xf9\xd9", // マル秘
		'd242' => "\xf9\xda", // リサイクル
		'd243' => "\xf9\xdb", // レジスタードトレードマーク (R)
		'd244' => "\xf9\xdc", // 危険・警告 (!)
		'd245' => "\xf9\xdd", // 禁止
		'd246' => "\xf9\xde", // 空室・空席・空車
		'd247' => "\xf9\xdf", // 合格マーク
		'd248' => "\xf9\xe0", // 満室・満席・満車
		'd249' => "\xf9\xe1", // 矢印左右
		'd250' => "\xf9\xe2", // 矢印上下
		'd251' => "\xf9\xe3", // 学校
		'd252' => "\xf9\xe4", // 波
		'd253' => "\xf9\xe5", // 富士山
		'd254' => "\xf9\xe6", // クローバー
		'd255' => "\xf9\xe7", // さくらんぼ
		'd256' => "\xf9\xe8", // チューリップ
		'd257' => "\xf9\xe9", // バナナ
		'd258' => "\xf9\xea", // りんご
		'd259' => "\xf9\xeb", // 芽
		'd260' => "\xf9\xec", // もみじ
		'd261' => "\xf9\xed", // 桜
		'd262' => "\xf9\xee", // おにぎり
		'd263' => "\xf9\xef", // ショートケーキ
		'd264' => "\xf9\xf0", // とっくり (おちょこ付き)
		'd265' => "\xf9\xf1", // どんぶり
		'd266' => "\xf9\xf2", // パン
		'd267' => "\xf9\xf3", // かたつむり
		'd268' => "\xf9\xf4", // ひよこ
		'd269' => "\xf9\xf5", // ペンギン
		'd270' => "\xf9\xf6", // 魚
		'd271' => "\xf9\xf7", // うまい! (顔)
		'd272' => "\xf9\xf8", // ウッシッシ (顔)
		'd273' => "\xf9\xf9", // ウマ
		'd274' => "\xf9\xfa", // ブタ
		'd275' => "\xf9\xfb", // ワイングラス
		'd276' => "\xf9\xfc", // げっそり (顔)
	);
	return;
}

/* ==================================================
 * @param	boolean $allow_search_engine
 * @return	boolean $in_network
 */
public function in_network($allow_search_engine = false) {
	return parent::in_network(self::$networks, $allow_search_engine);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function replace_smiley($buffer) {
	$smiles = array(
		'icon_smile.gif'     => self::$pictograms['d140'],
		'icon_biggrin.gif'   => self::$pictograms['d231'],
		'icon_sad.gif'       => self::$pictograms['d143'],
		'icon_surprised.gif' => self::$pictograms['d276'],
		'icon_eek.gif'       => self::$pictograms['d276'],
		'icon_confused.gif'  => self::$pictograms['d221'],
		'icon_cool.gif'      => self::$pictograms['d271'],
		'icon_mad.gif'       => self::$pictograms['d141'],
		'icon_razz.gif'      => self::$pictograms['d229'],
		'icon_neutral.gif'   => self::$pictograms['d226'],
		'icon_wink.gif'      => self::$pictograms['d230'],
		'icon_lol.gif'       => self::$pictograms['d229'],
		'icon_redface.gif'   => self::$pictograms['d227'],
		'icon_cry.gif'       => self::$pictograms['d234'],
		'icon_evil.gif'      => self::$pictograms['d225'],
		'icon_twisted.gif'   => self::$pictograms['d225'],
		'icon_rolleyes.gif'  => self::$pictograms['d221'],
		'icon_exclaim.gif'   => self::$pictograms['d244'],
		'icon_question.gif'  => '(?)',
		'icon_idea.gif'      => self::$pictograms['d151'],
		'icon_arrow.gif'     => self::$pictograms['d173'],
		'icon_mrgreen.gif'   => self::$pictograms['d272'],
	);
	$smiles = apply_filters('ktai_smiley_table', $smiles, __CLASS__);
	$smiles = apply_filters('smiley_table/ktai_style.php', $smiles);
	return parent::replace_smiley($buffer, $smiles);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function convert_pict($buffer) {
	// http://www.au.kddi.com/email/emoji/
	// http://mb.softbank.jp/mb/service/3G/mail/pictogram/
	// http://www.nttdocomo.co.jp/service/mail/imode_mail/emoji_convert/
	// http://www.willcom-inc.com/ja/service/e_mail/pdf/conversiontable.pdf
	$translated = self::$pictograms + array(
		'1'     => self::$pictograms['d244'], // 「!」
		'2'     => self::$pictograms['d158'], // 「!」
		'3'     => '?', // 「?」
		'4'     => self::$pictograms['d124'], // 「Q」
		'5'     => '＜', // 左向き三角1
		'6'     => '＞', // 右向き三角1
		'7'     => '≪', // 左向き三角2
		'8'     => '≫', // 右向き三角2
		'9'     => '□', // 小四角 1
		'10'    => '■', // 小四角 2
		'11'    => '[i]', // インフォメーションシンボル
		'12'    => self::$pictograms['d275'], // ワイングラス
		'13'    => '[スピーカー]', // スピーカー
		'14'    => '$', // ドルマーク
		'15'    => self::$pictograms['d098'], // 月 1
		'16'    => self::$pictograms['d005'], // いなずま
		'17'    => '□', // 中四角 1
		'18'    => '■', // 中四角 2
		'19'    => '◇', // 小菱形 1
		'20'    => '◆', // 小菱形 2
		'21'    => '□', // 中四角 1
		'22'    => '■', // 中四角 2
		'23'    => '◇', // 小菱形 1
		'24'    => '◆', // 小菱形 2
		'25'    => self::$pictograms['d220'], // 腕時計
		'26'    => '+', // プラス
		'27'    => '-', // マイナス
		'28'    => '☆', // 星 1
		'29'    => '↑', // 上矢印 1
		'30'    => '↓', // 下矢印 1
		'31'    => self::$pictograms['d245'], // 丸に斜め線
		'32'    => '▽', // 下三角 1
		'33'    => '△', // 上三角 1
		'34'    => '▼', // 下三角 2
		'35'    => '▲', // 上三角 2
		'36'    => '◇', // 大菱形 1
		'37'    => '◆', // 大菱形 2
		'38'    => '□', // 特大四角 1
		'39'    => '■', // 特大四角 2
		'40'    => '○', // 大丸 1
		'41'    => '●', // 大丸 2
		'42'    => self::$pictograms['d090'], // 上矢印 2 (左上)
		'43'    => self::$pictograms['d089'], // 下矢印 2 (右下)
		'44'    => self::$pictograms['d001'], // 太陽
		'45'    => self::$pictograms['d022'], // 野球ボール
		'46'    => self::$pictograms['d176'], // 時計
		'47'    => self::$pictograms['d097'], // 月 2 (顔つき)
		'48'    => self::$pictograms['d208'], // ベル
		'49'    => '[画鋲]', // プッシュピン (画鋲)
		'50'    => self::$pictograms['d170'], // 小顔
		'51'    => self::$pictograms['d136'], // ハート
		'52'    => self::$pictograms['d052'], // マティーニ (カクテルグラス)
		'53'    => self::$pictograms['d254'], // 四つ葉
		'54'    => self::$pictograms['d239'], // トレードマーク (TM)
		'55'    => '×', // かける
		'56'    => self::$pictograms['d076'], // 文書 1
		'57'    => self::$pictograms['d217'], // 砂時計 1
		'58'    => self::$pictograms['d217'], // 砂時計 2
		'59'    => '[フロッピー]', // フロッピーディスク 1
		'60'    => '*', // 雪の結晶
		'61'    => '×', // バツ 1
		'62'    => '×', // バツ 2
		'63'    => '→', // 右矢印 1
		'64'    => '←', // 左矢印 1
		'65'    => self::$pictograms['d053'], // マグカップ
		'66'    => '÷', // 割る
		'67'    => '[カレンダー]', // カレンダー
		'68'    => self::$pictograms['d140'], // スマイルフェイス
		'69'    => '★', // 星 2
		'70'    => self::$pictograms['d059'], // 右矢印 2 (右上)
		'71'    => self::$pictograms['d104'], // 左矢印 2 (左下)
		'72'    => self::$pictograms['d216'], // ジュエリー
		'73'    => 'レ', // チェックマーク 1
		'74'    => self::$pictograms['d100'], // 犬 (プードル)
		'75'    => '☆', // 星 3
		'76'    => self::$pictograms['d150'], // スパーク
		'77'    => self::$pictograms['d151'], // 電球
		'78'    => self::$pictograms['d268'], // 鳥
		'79'    => '[閉フォルダ]', // フォルダ 1 (閉)
		'80'    => self::$pictograms['d140'], // 顔 1
		'81'    => self::$pictograms['d238'], // コピーライトマーク (C)
		'82'    => self::$pictograms['d243'], // レジスタードマーク (R)
		'83'    => self::$pictograms['d069'], // ブリーフケース (ハンドバック)
		'84'    => '[開フォルダ]', // フォルダ 2 (開)
		'85'    => self::$pictograms['d074'], // 電話 1 (プッシュホン)
		'86'    => self::$pictograms['d076'], // 吹き出しコメント
		'87'    => '[クレジットカード]',// クレジットカード
		'88'    => '△', // 上三角 3
		'89'    => '▽', // 下三角 3
		'90'    => '[USA]', // USA (国旗)
		'91'    => self::$pictograms['d076'], // ノート 3
		'92'    => self::$pictograms['d076'], // クリップボード
		'93'    => self::$pictograms['d051'], // カップ
		'94'    => self::$pictograms['d068'], // カメラ
		'95'    => self::$pictograms['d003'], // 雨
		'96'    => '[フットボール]', // フットボール
		'97'    => self::$pictograms['d070'], // 本 1
		'98'    => self::$pictograms['d245'], // 立ち入り禁止
		'99'    => self::$pictograms['d048'], // 信号
		'100'   => self::$pictograms['d070'], // 本 2
		'101'   => self::$pictograms['d070'], // 本 3
		'102'   => self::$pictograms['d070'], // 本 4
		'103'   => self::$pictograms['d076'], // 文書 2
		'104'   => self::$pictograms['d056'], // はさみ
		'105'   => '[カレンダー]', // ひめくりカレンダー
		'106'   => self::$pictograms['d065'], // チケット・キップ
		'107'   => self::$pictograms['d002'], // くもり
		'108'   => self::$pictograms['d110'], // 封筒
		'109'   => self::$pictograms['d113'], // 小切手 (CHECK)
		'110'   => self::$pictograms['d058'], // ビデオカメラ
		'111'   => self::$pictograms['d058'], // ハンディカム
		'112'   => self::$pictograms['d038'], // 家
		'113'   => self::$pictograms['d256'], // 花 (チューリップ)
		'114'   => '[ナイフ]', // ナイフ
		'115'   => '[ビデオテープ]', // ビデオテープ
		'116'   => self::$pictograms['d093'], // めがね
		'117'   => '└→', // 回り矢印 1
		'118'   => self::$pictograms['d117'], // 回り矢印 2
		'119'   => self::$pictograms['d119'], // むしめがね
		'120'   => self::$pictograms['d116'], // 鍵
		'121'   => self::$pictograms['d076'], // ノート 1
		'122'   => self::$pictograms['d076'], // ノート 2 (開)
		'123'   => '[ボルトとナット]', // ボルト & ナット
		'124'   => self::$pictograms['d055'], // くつ (ハイヒール)
		'125'   => self::$pictograms['d033'], // 車
		'126'   => '[フロッピー]', // フロッピー 2
		'127'   => '[棒グラフ]', // チャート (棒グラフ)
		'128'   => '[折れ線グラフ]', // グラフ 1 (折れ線グラフ)
		'129'   => self::$pictograms['d110'], // メールボックス
		'130'   => '[懐中電灯]', // 懐中電灯
		'131'   => '[Roldex]', // Roldex
		'132'   => 'レ', // チェックマーク 2
		'134'   => self::$pictograms['d100'], // 猟犬
		'135'   => '[電池]', // 電池
		'136'   => '[スクロール]', // スクロール
		'137'   => '[画鋲]', // がびょう
		'138'   => self::$pictograms['d116'], // 錠前
		'139'   => self::$pictograms['d065'], // ドル札
		'140'   => '←', // 指差し確認左
		'141'   => '→', // 指差し確認右
		'142'   => self::$pictograms['d070'], // 台帳
		'143'   => self::$pictograms['d237'], // クリップ
		'144'   => self::$pictograms['d072'], // プレゼント
		'145'   => '[名札]', // 名札
		'146'   => self::$pictograms['d050'], // ゴハン 1 (ナイフとフォーク)
		'147'   => self::$pictograms['d070'], // 複数本
		'148'   => '[トラック]', // トラック
		'149'   => self::$pictograms['d214'], // エンピツ
		'150'   => '[IDO]', // ロゴ (PDC社)
		'151'   => self::$pictograms['d106'], // 封筒 2
		'152'   => self::$pictograms['d213'], // レンチ
		'153'   => self::$pictograms['d110'] . "→", // 送信 BOX
		'154'   => self::$pictograms['d106'], // 受信 BOX
		'155'   => self::$pictograms['d074'], // 電話 2 (受話器)
		'156'   => self::$pictograms['d039'], // 工場・建物
		'157'   => '□', // 定規 1 (直線)
		'158'   => '△', // 定規 2 (三角)
		'159'   => '[折れ線グラフ]', // グラフ 2
		'160'   => self::$pictograms['d050'], // 食事 2 (マンガ肉)
		'161'   => self::$pictograms['d075'], // 電話 3 (携帯)
		'162'   => '[コンセント]', // コンセント
		'163'   => self::$pictograms['d170'], // 家族
		'164'   => self::$pictograms['d071'], // リンク
		'165'   => self::$pictograms['d072'], // パッケージ
		'166'   => self::$pictograms['d107'], // FAX
		'167'   => self::$pictograms['d001'] . self::$pictograms['d002'], // ときどき曇り
		'168'   => self::$pictograms['d037'], // 飛行機
		'169'   => self::$pictograms['d102'], // ボート (船)
		'170'   => '[サイコロ]', // サイコロ
		'171'   => self::$pictograms['d076'], // 新聞
		'172'   => self::$pictograms['d030'], // 電車
		'173'   => '　', // 全部ブランク
		'174'   => ' ', // 半分ブランク
		'175'   => ' ', // 4分の1ブランク
		'176'   => self::$pictograms['d066'], // 喫煙
		'177'   => self::$pictograms['d067'], // 禁煙
		'178'   => self::$pictograms['d094'], // 車椅子
		'179'   => '[初心者]', // 若葉マーク
		'180'   => self::$pictograms['d125'], // 四角数字 1
		'181'   => self::$pictograms['d126'], // 四角数字 2
		'182'   => self::$pictograms['d127'], // 四角数字 3
		'183'   => self::$pictograms['d128'], // 四角数字 4
		'184'   => self::$pictograms['d129'], // 四角数字 5
		'185'   => self::$pictograms['d130'], // 四角数字 6
		'186'   => self::$pictograms['d131'], // 四角数字 7
		'187'   => self::$pictograms['d132'], // 四角数字 8
		'188'   => self::$pictograms['d133'], // 四角数字 9
		'189'   => self::$pictograms['d134'], // 四角数字 10
		'190'   => self::$pictograms['d006'], // 台風
		'191'   => self::$pictograms['d004'], // ゆきだるま
		'192'   => self::$pictograms['d009'], // 星座 (おひつじ座)
		'193'   => self::$pictograms['d010'], // 星座 (おうし座)
		'194'   => self::$pictograms['d011'], // 星座 (双子座)
		'195'   => self::$pictograms['d012'], // 星座 (かに座)
		'196'   => self::$pictograms['d013'], // 星座 (しし座)
		'197'   => self::$pictograms['d014'], // 星座 (おとめ座)
		'198'   => self::$pictograms['d015'], // 星座 (天秤座)
		'199'   => self::$pictograms['d016'], // 星座 (さそり座)
		'200'   => self::$pictograms['d017'], // 星座 (いて座)
		'201'   => self::$pictograms['d018'], // 星座 (やぎ座)
		'202'   => self::$pictograms['d019'], // 星座 (水瓶座)
		'203'   => self::$pictograms['d020'], // 星座 (うお座)
		'204'   => '[蛇遣座]', // 星座 (へびつかい座)
		'205'   => self::$pictograms['d043'], // ATM
		'206'   => self::$pictograms['d045'], // 24 HOURS (コンビニ)
		'207'   => self::$pictograms['d049'], // トイレ
		'208'   => self::$pictograms['d047'], // パーキング
		'209'   => self::$pictograms['d035'], // バス停
		'210'   => self::$pictograms['d121'], // アンテナ (位置情報マーク)
		'211'   => self::$pictograms['d036'], // 港 (いかりマーク)
		'212'   => self::$pictograms['d042'], // 銀行
		'213'   => self::$pictograms['d046'], // ガススタンド
		'214'   => '[地図]', // 地図
		'215'   => self::$pictograms['d218'], // 自転車
		'216'   => self::$pictograms['d035'], // バス
		'217'   => self::$pictograms['d032'], // 新幹線
		'218'   => self::$pictograms['d240'], // マラソン
		'219'   => self::$pictograms['d025'], // サッカー
		'220'   => self::$pictograms['d024'], // テニス
		'221'   => self::$pictograms['d207'], // スノーボード
		'222'   => self::$pictograms['d028'], // チェッカーフラッグ (モータースポーツ)
		'223'   => self::$pictograms['d060'], // 遊園地
		'224'   => self::$pictograms['d147'], // 温泉
		'225'   => self::$pictograms['d264'], // 居酒屋 (赤ちょうちん)
		'226'   => self::$pictograms['d167'], // 映画 (かちんこ)
		'227'   => self::$pictograms['d172'], // 夜の橋
		'228'   => '[東京タワー]', // 東京タワー
		'229'   => '[777]', // スロット (777)
		'230'   => '[くす玉]', // くす玉 (アタリのくす玉)
		'231'   => '◎←', // 当選弓矢
		'232'   => self::$pictograms['d078'], // ゲームのコントローラ
		'233'   => self::$pictograms['d210'], // 賞金
		'234'   => self::$pictograms['d103'], // クリスマスツリー
		'235'   => self::$pictograms['d261'], // 花見 (さくら)
		'236'   => '[お化け]', // お化け
		'237'   => '[日本]', // 旗 (祝日・日の丸)
		'238'   => '[西瓜]', // スイカ
		'239'   => self::$pictograms['d263'], // ケーキ
		'240'   => '[フライパン]', // フライパン (目玉焼き)
		'241'   => self::$pictograms['d255'], // さくらんぼ
		'242'   => '[河豚]', // ふぐ
		'243'   => '[苺]', // イチゴ
		'244'   => self::$pictograms['d262'], // おにぎり
		'245'   => self::$pictograms['d054'], // ハンバーガー (ファーストフード)
		'246'   => '[鯨]', // くじら
		'247'   => '[兎]', // うさぎ
		'248'   => self::$pictograms['d273'], // うま
		'249'   => '[猿]', // さる
		'250'   => '[蛙]', // かえる
		'251'   => self::$pictograms['d101'], // 猫
		'252'   => self::$pictograms['d269'], // ペンギン
		'253'   => '[蟻]', // あり
		'254'   => self::$pictograms['d274'], // ぶた
		'255'   => '[椰子の木]', // やしのき
		'256'   => '[向日葵]', // ひまわり
		'257'   => self::$pictograms['d140'], // 顔 1 (うれしいカオ)
		'258'   => self::$pictograms['d141'], // 顔 2 (おこったカオ)
		'259'   => self::$pictograms['d143'], // 顔 3 (かなしいカオ)
		'260'   => self::$pictograms['d144'], // 顔 4 (つかれたカオ)
		'261'   => self::$pictograms['d157'], // 眠い (ZZZ...)
		'262'   => self::$pictograms['d152'], // 怒り (ムカッ)
		'263'   => self::$pictograms['d235'], // 雫 (涙・汗)
		'264'   => self::$pictograms['d229'], // からかう (あっかんべえ)
		'265'   => self::$pictograms['d138'], // ハート 2 (われている)
		'266'   => self::$pictograms['d139'], // ハート 3 (大きい & 小さい)
		'267'   => self::$pictograms['d150'], // スパーク 2 (キラリマーク)
		'268'   => self::$pictograms['d154'], // 爆弾
		'269'   => '[炎]', // 炎
		'270'   => '[SOS]', // 捜索 (SOS)
		'271'   => '[力こぶ]', // 力こぶ
		'272'   => '→' . self::$pictograms['d136'], // ハート 5 (矢がささっている)
		'273'   => self::$pictograms['d149'], // キスマーク
		'274'   => self::$pictograms['d170'], // 宇宙人
		'275'   => self::$pictograms['d006'], // なると
		'276'   => self::$pictograms['d091'], // 足跡 (犬)
		'277'   => '↑' . self::$pictograms['d225'] . '↑', // 悪魔
		'278'   => self::$pictograms['d155'], // 花丸
		'279'   => self::$pictograms['d241'], // 丸秘
		'280'   => '[100点満点]', // 100点満点
		'281'   => self::$pictograms['d153'], // パンチ
		'282'   => self::$pictograms['d164'], // ダッシュ
		'283'   => '[ウンチ]', // ウンチマーク
		'284'   => '↑', // 人差し指サイン
		'285'   => '(得)', // マル得
		'286'   => '[ドクロ]', // どくろ
		'287'   => self::$pictograms['d228'], // おやゆびサイン (指が上)
		'288'   => self::$pictograms['d077'], // テレビ
		'289'   => self::$pictograms['d057'], // マイク
		'290'   => self::$pictograms['d204'], // 財布
		'291'   => self::$pictograms['d155'], // メロディ
		'292'   => '[ギター]', // ギター (エレキ)
		'293'   => '[バイオリン]', // バイオリン (クラシック)
		'294'   => self::$pictograms['d061'], // ヘッドフォン
		'295'   => self::$pictograms['d205'], // 口紅
		'296'   => '[ピストル]', // アクション (ピストル)
		'297'   => '[エステ]', // エステ
		'298'   => '[EZ]', // EZ マーク
		'299'   => self::$pictograms['d114'], // 無料 (FREE)
		'300'   => self::$pictograms['d079'], // CD/DVD
		'301'   => self::$pictograms['d203'], // 婦人服
		'302'   => '[UFO]', // UFO
		'303'   => self::$pictograms['d150'], // 更新 (UP!)
		'304'   => '[注射]', // 注射器 (血)
		'305'   => self::$pictograms['d007'], // 霧
		'306'   => self::$pictograms['d023'], // ゴルフ
		'307'   => self::$pictograms['d027'], // バスケットボール
		'308'   => self::$pictograms['d029'], // ポケットベル
		'309'   => self::$pictograms['d062'], // アート
		'310'   => self::$pictograms['d063'], // 演劇
		'311'   => self::$pictograms['d064'], // イベント (サーカス)
		'312'   => self::$pictograms['d071'], // リボン
		'313'   => self::$pictograms['d073'], // バースデー
		'314'   => self::$pictograms['d081'], // スペード
		'315'   => self::$pictograms['d082'], // ダイヤ
		'316'   => self::$pictograms['d083'], // クラブ
		'317'   => self::$pictograms['d084'], // 目
		'318'   => self::$pictograms['d085'], // 耳
		'319'   => self::$pictograms['d087'], // 手 (チョキ)
		'320'   => self::$pictograms['d088'], // 手 (パー)
		'321'   => self::$pictograms['d095'], // 新月
		'322'   => self::$pictograms['d096'], // やや欠け月
		'323'   => self::$pictograms['d097'], // 半月
		'324'   => self::$pictograms['d118'], // クリア
		'325'   => self::$pictograms['d134'], // 四角数字 0
		'326'   => self::$pictograms['d135'], // 決定 (OK)
		'327'   => self::$pictograms['d144'], // ふらふら (顔)
		'328'   => self::$pictograms['d148'], // かわいい
		'329'   => self::$pictograms['d161'], // どんっ (衝撃)
		'330'   => self::$pictograms['d162'], // あせあせ (飛び散る汗)
		'331'   => '[ezplus]', // イージープラス
		'332'   => '[地球]', // 地球
		'333'   => self::$pictograms['d265'], // ラーメン
		'334'   => self::$pictograms['d120'], // NEW
		'335'   => self::$pictograms['d203'], // 紳士服
		'336'   => self::$pictograms['d092'], // 紳士靴
		'337'   => self::$pictograms['d211'], // パソコン
		'338'   => self::$pictograms['d061'], // ラジオ
		'339'   => '[薔薇]', // バラ
		'340'   => self::$pictograms['d208'], // チャペル
		'341'   => self::$pictograms['d031'], // 地下鉄
		'342'   => self::$pictograms['d253'], // 富士山
		'343'   => self::$pictograms['d061'], // 八分音符
		'344'   => '[天使]', // 天使
		'345'   => '[虎]', // トラ
		'346'   => '[熊]', // くま
		'347'   => '[鼠]', // ねずみ
		'348'   => self::$pictograms['d230'], // ウィンク (顔)
		'349'   => self::$pictograms['d227'], // 目がハート (顔)
		'350'   => self::$pictograms['d276'], // ショッキング (顔)
		'351'   => self::$pictograms['d221'], // 困り (顔)
		'352'   => '[蛸]', // たこ
		'353'   => '[ロケット]', // ロケット
		'354'   => self::$pictograms['d215'], // 王冠
		'355'   => self::$pictograms['d149'], // チュー (キスしている)
		'356'   => '[ハンマー]', // ハンマー
		'357'   => '[花火]', // 打ち上げ花火
		'358'   => self::$pictograms['d260'], // 枯れ葉
		'359'   => self::$pictograms['d069'], // 仕事かばん
		'360'   => '[噴水]', // 噴水
		'361'   => '[キャンプ]', // キャンプ
		'362'   => '[麻雀]', // 麻雀
		'363'   => '[VS]', // VS (バーサス)
		'364'   => '[トロフィー]', // トロフィー
		'365'   => '[亀]', // カメ
		'366'   => '[スペイン]', // スペイン国旗
		'367'   => '[ロシア]', // ロシア国旗
		'368'   => '[工事中]', // 工事中
		'369'   => self::$pictograms['d147'], // 風呂
		'370'   => '[祝]', // 祝日マーク
		'371'   => '[夕方]', // 夕方街並み
		'372'   => '[卵]', // 卵割り
		'373'   => '[株価]', // 株価
		'374'   => '[警察官]', // ポリス
		'375'   => self::$pictograms['d040'], // 郵便局
		'376'   => self::$pictograms['d041'], // 病院
		'377'   => self::$pictograms['d251'], // 学校
		'378'   => self::$pictograms['d044'], // ホテル
		'379'   => self::$pictograms['d036'], // 船
		'380'   => self::$pictograms['d245'], // 18禁
		'381'   => '[.i|]', // 圏内
		'382'   => '[COOL!]', // COOL!
		'383'   => '[割]', // 割マーク
		'384'   => '[サ]', // ザ・マーク
		'385'   => self::$pictograms['d115'], // IDマーク
		'386'   => self::$pictograms['d248'], // 満マーク
		'387'   => self::$pictograms['d246'], // 空マーク
		'388'   => '[指]', // 指定マーク
		'389'   => '[営]', // 営業中マーク
		'390'   => '↑', // 上指差し
		'391'   => '↓', // 下指差し
		'392'   => '[占い]', // 占い (水晶)
		'393'   => self::$pictograms['d075'], // マナーモード
		'394'   => self::$pictograms['d075'], // 電源OFF
		'395'   => self::$pictograms['d076'], // メモする
		'396'   => '[ネクタイ]', // ネクタイ
		'397'   => self::$pictograms['d148'], // ハイビスカス
		'398'   => self::$pictograms['d148'], // 花束
		'399'   => '[サボテン]', // サボテン
		'400'   => self::$pictograms['d264'], // お銚子 & 杯
		'401'   => self::$pictograms['d053'], // 乾杯 (ビール)
		'402'   => '[祝]', // 祝マーク
		'403'   => '[薬]', // 風邪薬 (カプセル)
		'404'   => '[風船]', // 風船
		'405'   => '[クラッカー]', // クラッカー
		'406'   => '[eznavi]', // eznavigation
		'407'   => '[帽子]', // 帽子
		'408'   => self::$pictograms['d092'], // ロングブーツ
		'409'   => self::$pictograms['d205'], // ネイル
		'410'   => self::$pictograms['d056'], // 美容院
		'411'   => '[理髪店]', // 床屋
		'412'   => '[着物]', // 着物
		'413'   => self::$pictograms['d021'], // ビキニ
		'414'   => self::$pictograms['d080'], // ハート (トランプ)
		'415'   => self::$pictograms['d136'], // 光るハート
		'416'   => self::$pictograms['d136'], // 青ハート
		'417'   => self::$pictograms['d136'], // 緑ハート
		'418'   => self::$pictograms['d136'], // 黄ハート
		'419'   => self::$pictograms['d136'], // 紫ハート
		'420'   => self::$pictograms['d150'], // きらきら
		'421'   => self::$pictograms['d026'], // スキー
		'422'   => '○', // ○
		'423'   => self::$pictograms['d219'], // 日本茶
		'424'   => self::$pictograms['d266'], // 食パン
		'425'   => '[ソフトクリーム]', // ソフトクリーム
		'426'   => '[ポテト]', // ポテト
		'427'   => '[団子]', // だんご
		'428'   => '[お煎餅]', // おせんべい
		'429'   => '[御飯]', // ごはん
		'430'   => '[スパゲティ]', // スパゲティ
		'431'   => '[カレー]', // カレー
		'432'   => '[おでん]', // おでん
		'433'   => '[寿司]', // 寿司
		'434'   => self::$pictograms['d258'], // りんご
		'435'   => '[蜜柑]', // みかん
		'436'   => '[トマト]', // トマト
		'437'   => '[茄子]', // なす
		'438'   => '[弁当]', // 弁当
		'439'   => '[鍋]', // 鍋
		'440'   => self::$pictograms['d222'], // ふっ (顔)
		'441'   => self::$pictograms['d142'], // しょんぼり (顔)
		'442'   => self::$pictograms['d231'], // 勝ち誇り (顔)
		'443'   => self::$pictograms['d143'], // 失敗 (顔)
		'444'   => self::$pictograms['d221'], // わからん
		'445'   => self::$pictograms['d157'], // 眠い
		'446'   => self::$pictograms['d223'], // てれてれ (顔)
		'447'   => self::$pictograms['d224'], // 青ざめ (顔)
		'448'   => self::$pictograms['d232'], // 風邪ひき
		'449'   => self::$pictograms['d225'], // 熱 (顔)
		'450'   => self::$pictograms['d226'], // 横目 (顔)
		'451'   => self::$pictograms['d276'], // びっくり (顔)
		'452'   => self::$pictograms['d224'], // あせり (顔)
		'453'   => self::$pictograms['d155'], // 楽譜
		'454'   => self::$pictograms['d231'], // にこにこ (顔)
		'455'   => self::$pictograms['d227'], // チュー 2 (顔)
		'456'   => self::$pictograms['d227'], // チュッ (顔)
		'457'   => '[鼻]', // 鼻
		'458'   => self::$pictograms['d149'], // 口
		'459'   => '[ゴメン]', // ゴメン／お願い
		'460'   => self::$pictograms['d088'] . self::$pictograms['d088'], // 拍手
		'461'   => self::$pictograms['d135'], // OK! (指で丸サイン)
		'462'   => self::$pictograms['d156'], // ブーイング (指が下)
		'463'   => self::$pictograms['d088'], // バイバイ
		'464'   => self::$pictograms['d236'], // NG (ネコ)
		'465'   => self::$pictograms['d135'], // OK! 2 (ネコ)
		'466'   => '[ゴメン]', // 平謝り (ネコ)
		'467'   => '[カップル]', // カップル
		'468'   => '[バニー]', // バニー
		'469'   => '[トラペット]', // トランペット
		'470'   => '[ビリヤード]', // ビリヤード
		'471'   => '[水泳]', // 水泳
		'472'   => self::$pictograms['d033'], // 消防車
		'473'   => self::$pictograms['d033'], // 救急車
		'474'   => self::$pictograms['d033'], // パトカー
		'475'   => self::$pictograms['d032'], // ジェットコースター
		'476'   => '[門松]', // 門松
		'477'   => '[雛祭り]', // 雛祭り
		'478'   => '[卒業式]', // 卒業式
		'479'   => '[入学式]', // 入学式
		'480'   => self::$pictograms['d270'], // こいのぼり
		'481'   => self::$pictograms['d008'], // 傘
		'482'   => self::$pictograms['d170'], // 花嫁
		'483'   => '[かき氷]', // かき氷
		'484'   => '[線香花火]', // 線香花火
		'485'   => '[巻貝]', // 巻き貝
		'486'   => '[風鈴]', // 風鈴
		'487'   => '[ハロウィン]', // ハロウィン
		'488'   => self::$pictograms['d172'], // お月見
		'489'   => '[サンタ]', // サンタ
		'490'   => self::$pictograms['d172'], // 夜／流れ星
		'491'   => '[虹]', // 虹
		'492'   => self::$pictograms['d044'], // ホテル 2
		'493'   => self::$pictograms['d001'], // 日の出
		'494'   => self::$pictograms['d063'], // シルクハット
		'495'   => self::$pictograms['d039'], // デパート
		'496'   => self::$pictograms['d039'], // 城 (日本)
		'497'   => self::$pictograms['d039'], // 城 (ヨーロッパ)
		'498'   => self::$pictograms['d039'], // 工場 2
		'499'   => '[フランス]', // フランス国旗
		'500'   => '[オープンウェーブ]',// オープンウェーブ
		'501'   => self::$pictograms['d116'], // ロック確認
		'502'   => '[ABC]', // 大文字
		'503'   => '[abc]', // 小文字
		'504'   => '[012]', // 数字
		'505'   => '[,@#]', // 記号
		'506'   => '[可]', // アクセプト
		'507'   => 'レ', // チェックボックス
		'508'   => self::$pictograms['d169'], // エディット
		'509'   => '◎', // ラジオボタン
		'510'   => self::$pictograms['d119'], // 見る (虫眼鏡)
		'511'   => self::$pictograms['d117'], // 戻る
		'512'   => self::$pictograms['d076'], // お気に入り
		'513'   => self::$pictograms['d175'], // 終了
		'514'   => self::$pictograms['d038'], // ホーム
		'515'   => self::$pictograms['d106'], // 受信箱 1
		'516'   => '□', // マーク
		'517'   => self::$pictograms['d116'], // 個人 (鍵)
		'518'   => self::$pictograms['d242'], // 再読み込み
		'700'   => '[ドイツ]', // ドイツ国旗
		'701'   => '[イタリア]', // イタリア国旗
		'702'   => '[イギリス]', // イギリス国旗
		'703'   => '[中国]', // 中国国旗
		'704'   => '[韓国]', // 韓国国旗
		'705'   => '[白人]', // 白人
		'706'   => '[中国人]', // 中国人
		'707'   => '[インド人]', // インド人
		'708'   => self::$pictograms['d170'], // おじいさん
		'709'   => self::$pictograms['d170'], // おばあさん
		'710'   => self::$pictograms['d222'], // 赤ちゃん
		'711'   => self::$pictograms['d170'], // 工事現場の人
		'712'   => self::$pictograms['d170'], // お姫様
		'713'   => self::$pictograms['d270'], // イルカ
		'714'   => '[ダンス]', // ダンス
		'715'   => self::$pictograms['d270'], // 熱帯魚
		'716'   => '[毛虫]', // げじげじ
		'717'   => '[象]', // 象
		'718'   => '[コアラ]', // コアラ
		'719'   => '[牛]', // ホルスタイン
		'720'   => '[蛇]', // ヘビ
		'721'   => self::$pictograms['d268'], // 鶏
		'722'   => '[猪]', // うりぼう
		'723'   => '[ラクダ]', // ふたこぶらくだ
		'724'   => '[A型]', // A型
		'725'   => '[B型]', // B型
		'726'   => '[O型]', // O型
		'727'   => '[AB型]', // AB型
		'728'   => self::$pictograms['d091'], // 足跡
		'729'   => self::$pictograms['d092'], // スニーカー
		'730'   => self::$pictograms['d121'], // 旗
		'731'   => self::$pictograms['d145'], // 上向きカーブ矢印
		'732'   => self::$pictograms['d156'], // 下向きカーブ矢印
		'733'   => self::$pictograms['d159'], // 「!?」
		'734'   => self::$pictograms['d160'], // 「!!」
		'735'   => self::$pictograms['d166'], // くるり
		'736'   => '[メロン]', // メロン
		'737'   => '[パイナップル]', // パイナップル
		'738'   => '[葡萄]', // ぶどう
		'739'   => self::$pictograms['d257'], // バナナ
		'740'   => '[とうもろこし]', // とうもろこし
		'741'   => '[きのこ]', // きのこ
		'742'   => '[栗]', // 栗
		'743'   => '[桃]', // 桃
		'744'   => '[焼芋]', // やきいも
		'745'   => '[ピザ]', // ピザ
		'746'   => '[ターキー]', // ターキー
		'747'   => '[七夕]', // 七夕笹飾り
		'748'   => self::$pictograms['d275'], // トロピカルドリンク
		'749'   => '[辰]', // 辰
		'750'   => '[ピアノ]', // ピアノ
		'751'   => self::$pictograms['d252'], // サーフィン
		'752'   => self::$pictograms['d270'], // 釣り
		'753'   => '[ボウリング]', // ボウリング
		'754'   => '[なまはげ]', // なまはげ
		'755'   => self::$pictograms['d225'], // 天狗
		'756'   => '[パンダ]', // パンダ
		'757'   => self::$pictograms['d229'], // あかんべー
		'758'   => self::$pictograms['d274'], // ぶたの鼻
		'759'   => self::$pictograms['d148'], // 花
		'760'   => '[アイスクリーム]', // アイスクリーム
		'761'   => '◎', // ドーナツ
		'762'   => '[クッキー]', // クッキー
		'763'   => '[チョコ]', // チョコ
		'764'   => '[キャンディ]', // キャンディ (包み)
		'765'   => '[ぺろぺろキャンディ]',// キャンディ (ぺろぺろ)
		'766'   => '(/_＼)', // 見ざる (猿)
		'767'   => '(・x・)', // 言わざる (猿)
		'768'   => '|(・_・)|', // 聞かざる (猿)
		'769'   => self::$pictograms['d253'], // 火山
		'770'   => self::$pictograms['d136'] . self::$pictograms['d071'], // リボンがけのハート
		'771'   => '[ABC]', // 英語「ABC」
		'772'   => '[プリン]', // プリン
		'773'   => '[蜜蜂]', // ミツバチ
		'774'   => '[てんとう虫]', // テントウムシ
		'775'   => '[蜂蜜ポット]', // 蜂蜜ポット
		'776'   => self::$pictograms['d258'], // 青りんご
		'777'   => self::$pictograms['d113'], // 羽のはえたお札
		'778'   => self::$pictograms['d006'], // 目がまわる時の記号
		'779'   => self::$pictograms['d225'], // ぷー (かわいく怒)
		'780'   => self::$pictograms['d225'], // ぷー (かわいく怒) (ネコ)
		'781'   => self::$pictograms['d172'], // 天の川
		'782'   => self::$pictograms['d227'], // チュー (ネコ)
		'783'   => self::$pictograms['d231'], // にこ (ネコ)
		'784'   => self::$pictograms['d106'], // メールする
		'785'   => self::$pictograms['d231'], // 泣き笑い (ネコ)
		'786'   => self::$pictograms['d231'], // 泣き笑い (顔)
		'787'   => self::$pictograms['d227'], // 目がハート (ネコ)
		'788'   => self::$pictograms['d234'], // ほえー (ネコ)
		'789'   => self::$pictograms['d234'], // ほえー (顔)
		'790'   => self::$pictograms['d235'], // 涙ぽろり (ネコ)
		'791'   => self::$pictograms['d235'], // 涙ぽろり (顔)
		'792'   => self::$pictograms['d226'], // きりり (ネコ)
		'793'   => '[ドレス]', // ドレス
		'794'   => '[モヤイ像]', // モヤイ像
		'795'   => '[駅]', // 駅
		'796'   => '[花札]', // 花札
		'797'   => '[ジョーカー]', // ジョーカー
		'798'   => '[海老フライ]', // エビフライ
		'799'   => self::$pictograms['d110'], // eメールアイコン
		'800'   => self::$pictograms['d240'], // 歩く人
		'801'   => '[パトカー]', // パトカーのランプ
		'802'   => self::$pictograms['d058'], // ezmovie
		'803'   => self::$pictograms['d137'], // ドキドキしているハート
		'804'   => self::$pictograms['d268'], // 正面向きのひよこ
		'805'   => self::$pictograms['d206'], // ジーンズ
		'806'   => self::$pictograms['d212'], // ハートつきメール
		'807'   => self::$pictograms['d242'], // 循環矢印
		'808'   => self::$pictograms['d249'], // 左右両方矢印
		'809'   => self::$pictograms['d250'], // 上下両方矢印
		'810'   => self::$pictograms['d252'], // 荒波
		'811'   => self::$pictograms['d259'], // 双葉
		'812'   => self::$pictograms['d267'], // かたつむり
		'813'   => self::$pictograms['d272'], // うっしっし (ネコ)
		'814'   => self::$pictograms['d272'], // うっしっし (顔)
		'815'   => self::$pictograms['d110'], // Cメールアイコン
		'816'   => self::$pictograms['d259'], // ハーブ
		'817'   => self::$pictograms['d086'], // 手 (グー)
		'818'   => self::$pictograms['d123'], // 「#」
		'819'   => self::$pictograms['d140'], // 挙手 (キャラクター)
		'820'   => self::$pictograms['d231'], // 万歳 (キャラクター)
		'821'   => self::$pictograms['d142'], // しょんぼり (キャラクター)
		'822'   => self::$pictograms['d225'], // かわいく怒る (キャラクター)
		'se001' => self::$pictograms['d140'], // 男の子
		'se002' => self::$pictograms['d140'], // 女の子
		'se003' => self::$pictograms['d149'], // 美容 (キスマーク)
		'se004' => self::$pictograms['d140'], // お父さん
		'se005' => self::$pictograms['d140'], // お母さん
		'se006' => self::$pictograms['d203'], // 洋服
		'se007' => self::$pictograms['d092'], // ブーツ
		'se008' => self::$pictograms['d068'], // カメラ
		'se009' => self::$pictograms['d074'], // 電話
		'se00a' => self::$pictograms['d075'], // 携帯電話
		'se00b' => self::$pictograms['d107'], // FAX
		'se00c' => self::$pictograms['d211'], // パソコン
		'se00d' => self::$pictograms['d153'], // パンチ
		'se00e' => self::$pictograms['d228'], // GOOD!
		'se00f' => '[No.1!]', // No.1!
		'se010' => self::$pictograms['d086'], // グー
		'se011' => self::$pictograms['d087'], // チョキ
		'se012' => self::$pictograms['d088'], // パー
		'se013' => self::$pictograms['d026'], // スキー
		'se014' => self::$pictograms['d023'], // ゴルフ
		'se015' => self::$pictograms['d024'], // テニス
		'se016' => self::$pictograms['d022'], // 野球
		'se017' => self::$pictograms['d207'], // サーフィン
		'se018' => self::$pictograms['d025'], // サッカー
		'se019' => self::$pictograms['d270'], // 魚
		'se01a' => self::$pictograms['d273'], // うま
		'se01b' => self::$pictograms['d033'], // 車
		'se01c' => self::$pictograms['d102'], // ヨット
		'se01d' => self::$pictograms['d037'], // 飛行機
		'se01e' => self::$pictograms['d030'], // 電車
		'se01f' => self::$pictograms['d032'], // 新幹線
		'se020' => '?', // ハテナ
		'se021' => self::$pictograms['d158'], // ビックリ
		'se022' => self::$pictograms['d136'], // ハートマーク
		'se023' => self::$pictograms['d138'], // ハートブレイク
		'se024' => self::$pictograms['d176'], // 1時
		'se025' => self::$pictograms['d176'], // 2時
		'se026' => self::$pictograms['d176'], // 3時
		'se027' => self::$pictograms['d176'], // 4時
		'se028' => self::$pictograms['d176'], // 5時
		'se029' => self::$pictograms['d176'], // 6時
		'se02a' => self::$pictograms['d176'], // 7時
		'se02b' => self::$pictograms['d176'], // 8時
		'se02c' => self::$pictograms['d176'], // 9時
		'se02d' => self::$pictograms['d176'], // 10時
		'se02e' => self::$pictograms['d176'], // 11時
		'se02f' => self::$pictograms['d176'], // 12時
		'se030' => self::$pictograms['d176'], // お花見
		'se031' => self::$pictograms['d215'], // エンブレム
		'se032' => self::$pictograms['d261'], // バラ
		'se033' => self::$pictograms['d103'], // クリスマス
		'se034' => self::$pictograms['d216'], // 指輪
		'se035' => self::$pictograms['d216'], // 宝石
		'se036' => self::$pictograms['d038'], // 家
		'se037' => '[教会]', // 教会
		'se038' => self::$pictograms['d039'], // ビル
		'se039' => '[駅]', // 駅
		'se03a' => self::$pictograms['d046'], // ガソリンスタンド
		'se03b' => self::$pictograms['d253'], // 山
		'se03c' => self::$pictograms['d057'], // マイク
		'se03d' => self::$pictograms['d058'], // 映画
		'se03e' => self::$pictograms['d146'], // 音楽
		'se03f' => self::$pictograms['d116'], // カギ
		'se040' => '[サックス]', // サックス
		'se041' => '[ギター]', // ギター
		'se042' => '[トランペット]', // トランペット
		'se043' => self::$pictograms['d050'], // レストラン
		'se044' => self::$pictograms['d052'], // カクテル
		'se045' => self::$pictograms['d051'], // コーヒー
		'se046' => self::$pictograms['d263'], // ケーキ
		'se047' => self::$pictograms['d053'], // ビール
		'se048' => self::$pictograms['d004'], // 雪
		'se049' => self::$pictograms['d002'], // 曇り
		'se04a' => self::$pictograms['d001'], // 晴れ (昼)
		'se04b' => self::$pictograms['d003'], // 雨
		'se04c' => self::$pictograms['d098'], // 晴れ (夜)
		'se04d' => self::$pictograms['d001'], // 朝
		'se04e' => '[天使]', // 天使
		'se04f' => self::$pictograms['d101'], // ねこ
		'se050' => '[虎]', // とら
		'se051' => '[熊]', // くま
		'se052' => self::$pictograms['d100'], // いぬ
		'se053' => '[鼠]', // ねずみ
		'se054' => '[鯨]', // クジラ
		'se055' => self::$pictograms['d269'], // ペンギン
		'se056' => self::$pictograms['d140'], // 楽 (顔)
		'se057' => self::$pictograms['d231'], // 喜 (顔)
		'se058' => self::$pictograms['d142'], // 哀 (顔)
		'se059' => self::$pictograms['d141'], // 怒 (顔)
		'se05a' => '[ウンチ]', // ウンチ
		'se101' => self::$pictograms['d106'], // メール受信
		'se102' => self::$pictograms['d110'] . '→', // メール送信
		'se103' => self::$pictograms['d106'], // メール宛先
		'se104' => self::$pictograms['d105'], // 電話連絡先
		'se105' => self::$pictograms['d229'], // アカンベー (顔)
		'se106' => self::$pictograms['d227'], // ラブラブ (顔)
		'se107' => self::$pictograms['d276'], // ガビーン (顔)
		'se108' => self::$pictograms['d224'], // タラー (顔)
		'se109' => '[猿]', // さる
		'se10a' => '[蛸]', // タコ
		'se10b' => self::$pictograms['d274'], // ぶた
		'se10c' => self::$pictograms['d170'], // 宇宙人
		'se10d' => '[ロケット]', // ロケット
		'se10e' => self::$pictograms['d215'], // 王冠
		'se10f' => self::$pictograms['d151'], // 電球
		'se110' => self::$pictograms['d254'], // よつば
		'se111' => self::$pictograms['d149'], // キス
		'se112' => self::$pictograms['d072'], // バースデー (プレゼント)
		'se113' => '[ピストル]', // ピストル
		'se114' => self::$pictograms['d119'], // 虫眼鏡
		'se115' => self::$pictograms['d240'], // 陸上
		'se116' => '[オークション]', // オークション
		'se117' => self::$pictograms['d150'], // 花火
		'se118' => self::$pictograms['d260'], // もみじ
		'se119' => self::$pictograms['d260'], // 落ち葉
		'se11a' => '[悪魔]', // 悪魔
		'se11b' => '[お化け]', // おばけ
		'se11c' => '[ドクロ]', // ドクロ
		'se11d' => '[炎]', // ファイヤー
		'se11e' => self::$pictograms['d069'], // かばん
		'se11f' => self::$pictograms['d171'], // 座席
		'se120' => self::$pictograms['d054'], // ハンバーガー
		'se121' => '[公園]', // 公園
		'se122' => '[キャンプ]', // キャンプ場
		'se123' => self::$pictograms['d147'], // 温泉
		'se124' => self::$pictograms['d060'], // 遊園地
		'se125' => self::$pictograms['d065'], // チケット
		'se126' => self::$pictograms['d079'], // CD
		'se127' => self::$pictograms['d079'], // DVD
		'se128' => self::$pictograms['d061'], // ラジオ
		'se129' => '[ビデオ]', // ビデオ
		'se12a' => self::$pictograms['d077'], // テレビ
		'se12b' => self::$pictograms['d078'], // ゲーム
		'se12c' => self::$pictograms['d146'], // 歌い出し
		'se12d' => '[麻雀]', // マージャン
		'se12e' => '[VS]', // 対決
		'se12f' => self::$pictograms['d210'], // 賞金 (ドル袋)
		'se130' => '[当たり]', // 当たり
		'se131' => '[トロフィー]', // トロフィー
		'se132' => self::$pictograms['d028'], // ゴール (チェッカーフラッグ)
		'se133' => '[777]', // スロット (777)
		'se134' => self::$pictograms['d273'], // 競馬
		'se135' => self::$pictograms['d102'], // 競艇
		'se136' => self::$pictograms['d218'], // 競輪
		'se137' => '[工事中]', // 工事中
		'se138' => '♂', // 男性
		'se139' => '♀', // 女性
		'se13a' => '[赤ちゃん]', // 乳幼児
		'se13b' => '[注射]', // 注射器
		'se13c' => self::$pictograms['d157'], // 睡眠 (Zzz)
		'se13d' => self::$pictograms['d005'], // 雷
		'se13e' => self::$pictograms['d055'], // ハイヒール
		'se13f' => self::$pictograms['d147'], // 入浴
		'se140' => self::$pictograms['d049'], // トイレ
		'se141' => '[音声]', // 音声
		'se142' => '[メガホン]', // お知らせ (メガホン)
		'se143' => '[祝日]', // 祝日
		'se144' => self::$pictograms['d116'], // ロックON
		'se145' => self::$pictograms['d116'], // ロックOFF
		'se146' => '[街]', // 街
		'se147' => '[料理]', // 料理 (卵)
		'se148' => self::$pictograms['d070'], // 本
		'se149' => '[$\\]', // 為替相場
		'se14a' => '[株価]', // 株価
		'se14b' => '[パラボラ]', // ニュース (パラボラアンテナ)
		'se14c' => '[力こぶ]', // 元気 (力こぶ)
		'se14d' => self::$pictograms['d042'], // 銀行
		'se14e' => self::$pictograms['d048'], // 信号
		'se14f' => self::$pictograms['d047'], // 駐車場
		'se150' => self::$pictograms['d035'], // バス停
		'se151' => self::$pictograms['d049'], // 公衆トイレ
		'se152' => '[交番]', // 交番
		'se153' => self::$pictograms['d040'], // 郵便局
		'se154' => self::$pictograms['d043'], // ATM
		'se155' => self::$pictograms['d041'], // 病院
		'se156' => self::$pictograms['d045'], // コンビニ
		'se157' => self::$pictograms['d251'], // 学校
		'se158' => self::$pictograms['d044'], // ホテル
		'se159' => self::$pictograms['d035'], // バス
		'se15a' => self::$pictograms['d033'], // タクシー
		'se201' => self::$pictograms['d240'], // 徒歩
		'se202' => self::$pictograms['d036'], // 船
		'se203' => '[ココ]', // 目的地 (ココ)
		'se204' => self::$pictograms['d148'], // 飾罫1
		'se205' => self::$pictograms['d148'], // 飾罫2
		'se206' => self::$pictograms['d148'], // 飾罫3
		'se207' => self::$pictograms['d245'], // 18禁
		'se208' => self::$pictograms['d067'], // 禁煙
		'se209' => '[初心者]', // 初心者
		'se20a' => self::$pictograms['d094'], // バリアフリー (車椅子マーク)
		'se20b' => '[.i|]', // アンテナマーク
		'se20c' => self::$pictograms['d080'], // ハート (トランプ)
		'se20d' => self::$pictograms['d082'], // ダイヤ (トランプ)
		'se20e' => self::$pictograms['d081'], // スペード (トランプ)
		'se20f' => self::$pictograms['d083'], // クラブ (トランプ)
		'se210' => self::$pictograms['d123'], // シャープダイヤル
		'se211' => self::$pictograms['d122'], // フリーダイヤル
		'se212' => self::$pictograms['d120'], // 新着
		'se213' => self::$pictograms['d150'], // 更新
		'se214' => self::$pictograms['d093'], // おすすめ (COOL)
		'se215' => self::$pictograms['d113'], // 有料
		'se216' => self::$pictograms['d114'], // 無料
		'se217' => '[月]', // 月額
		'se218' => '[申]', // 申し込み
		'se219' => '●', // 見出しボタン1 (オレンジ)
		'se21a' => '◎', // 見出しボタン2 (緑)
		'se21b' => '◎', // 見出しボタン4 (紫)
		'se21c' => self::$pictograms['d125'], // 1 (one)
		'se21d' => self::$pictograms['d126'], // 2 (two)
		'se21e' => self::$pictograms['d127'], // 3 (three)
		'se21f' => self::$pictograms['d128'], // 4 (four)
		'se220' => self::$pictograms['d129'], // 5 (five)
		'se221' => self::$pictograms['d130'], // 6 (six)
		'se222' => self::$pictograms['d131'], // 7 (seven)
		'se223' => self::$pictograms['d132'], // 8 (eight)
		'se224' => self::$pictograms['d133'], // 9 (nine)
		'se225' => self::$pictograms['d134'], // 0 (zero)
		'se226' => '[得]', // お得
		'se227' => '[割]', // 割引
		'se228' => '[サ]', // サービス料
		'se229' => self::$pictograms['d115'], // ID
		'se22a' => self::$pictograms['d248'], // 満席
		'se22b' => self::$pictograms['d246'], // 空席
		'se22c' => '[指]', // 指定席
		'se22d' => '[営]', // 営業時間
		'se22e' => '↑', // 上へ (指)
		'se22f' => '↓', // 下へ (指)
		'se230' => '←', // 左へ (指)
		'se231' => '→', // 右へ (指)
		'se232' => '↑', // 上
		'se233' => '↓', // 下
		'se234' => '←', // 右
		'se235' => '→', // 左
		'se236' => self::$pictograms['d059'], // 右上
		'se237' => self::$pictograms['d090'], // 左上
		'se238' => self::$pictograms['d089'], // 右下
		'se239' => self::$pictograms['d104'], // 左下
		'se23a' => '＞', // 次へ
		'se23b' => '＜', // 前へ
		'se23c' => '≫', // 早送り 
		'se23d' => '≪', // 巻き戻し
		'se23e' => '[☆]', // 星座
		'se23f' => self::$pictograms['d009'], // おひつじ座
		'se240' => self::$pictograms['d010'], // おうし座
		'se241' => self::$pictograms['d011'], // ふたご座
		'se242' => self::$pictograms['d012'], // かに座
		'se243' => self::$pictograms['d013'], // しし座
		'se244' => self::$pictograms['d014'], // おとめ座
		'se245' => self::$pictograms['d015'], // てんぴん座
		'se246' => self::$pictograms['d016'], // さそり座
		'se247' => self::$pictograms['d017'], // いて座
		'se248' => self::$pictograms['d018'], // やぎ座
		'se249' => self::$pictograms['d019'], // みずがめ座
		'se24a' => self::$pictograms['d020'], // うお座
		'se24b' => '[蛇遣座]', // へびつかい座
		'se24c' => '[TOP]', // TOPページ
		'se24d' => self::$pictograms['d135'], // OKボタン
		'se24e' => self::$pictograms['d238'], // 著作権 (C)
		'se24f' => self::$pictograms['d243'], // 登録商標 (R)
		'se250' => self::$pictograms['d075'], // マナーモード
		'se251' => self::$pictograms['d075'], // 電源切
		'se252' => self::$pictograms['d244'], // ご注意 (!)
		'se253' => self::$pictograms['d170'], // ご案内
		'se254' => self::$pictograms['d039'], // J-PHONEショップ
		'se255' => self::$pictograms['d012'], // スカイウェブ
		'se256' => self::$pictograms['d110'], // スカイウォーカー
		'se257' => self::$pictograms['d146'] . self::$pictograms['d106'] , // スカイメロディ
		'se258' => 'J-', // J-PHONE 1
		'se259' => 'Pho', // J-PHONE 2
		'se25a' => 'ne', // J-PHONE 3
		'se301' => self::$pictograms['d076'], // メモ
		'se302' => '[ネクタイ]', // ネクタイ
		'se303' => self::$pictograms['d148'], // ハイビスカス
		'se304' => self::$pictograms['d256'], // チューリップ
		'se305' => self::$pictograms['d148'], // ひまわり
		'se306' => self::$pictograms['d150'], // 花束
		'se307' => '[椰子の木]', // やしの木
		'se308' => '[サボテン]', // サボテン
		'se309' => self::$pictograms['d049'], // トイレ
		'se30a' => self::$pictograms['d061'], // ヘッドホン
		'se30b' => self::$pictograms['d264'], // 晩酌 (とっくり)
		'se30c' => self::$pictograms['d053'], // 乾杯 (ビール)
		'se30d' => '(祝)', // 祝
		'se30e' => self::$pictograms['d066'], // 喫煙
		'se30f' => '[薬]', // カプセル薬
		'se310' => '[風船]', // 風船
		'se311' => self::$pictograms['d154'], // 爆弾
		'se312' => '[クラッカー]', // クラッカー
		'se313' => self::$pictograms['d056'], // ハサミ
		'se314' => self::$pictograms['d071'], // リボン
		'se315' => self::$pictograms['d241'], // マル秘
		'se316' => '[MD]', // MD
		'se317' => '[メガホン]', // メガフォン
		'se318' => self::$pictograms['d063'], // 帽子
		'se319' => '[ドレス]', // 可愛いワンピース
		'se31a' => self::$pictograms['d055'], // ミュール
		'se31b' => '[ブーツ]', // ロングブーツ
		'se31c' => self::$pictograms['d205'], // 口紅
		'se31d' => '[マニキュア]', // マニキュア
		'se31e' => '[エステ]', // エステ
		'se31f' => self::$pictograms['d056'], // 美容院
		'se320' => self::$pictograms['d056'], // 理髪店
		'se321' => '[着物]', // 着物
		'se322' => self::$pictograms['d021'], // ビキニ
		'se323' => self::$pictograms['d069'], // ブランドバッグ
		'se324' => self::$pictograms['d167'], // カチンコ
		'se325' => self::$pictograms['d208'], // すず
		'se326' => self::$pictograms['d155'], // 踊る音符
		'se327' => self::$pictograms['d137'], // ぴかぴかハート
		'se328' => self::$pictograms['d137'], // ドキドキハート
		'se329' => '→' . self::$pictograms['d136'], // ハートを射とめて
		'se32a' => self::$pictograms['d136'], // ハート (青)
		'se32b' => self::$pictograms['d136'], // ハート (緑)
		'se32c' => self::$pictograms['d136'], // ハート (黄)
		'se32d' => self::$pictograms['d136'], // ハート (紫)
		'se32e' => self::$pictograms['d150'], // NEW
		'se32f' => '☆', // ☆
		'se330' => self::$pictograms['d164'], // ダッシュ
		'se331' => self::$pictograms['d162'], // 飛び散る汗
		'se332' => self::$pictograms['d099'], // ○
		'se333' => '×', // ×
		'se334' => self::$pictograms['d152'], // 怒り
		'se335' => '☆', // ☆ (点滅)
		'se336' => '?', // 動く "?"
		'se337' => self::$pictograms['d158'], // 動く "!"
		'se338' => self::$pictograms['d219'], // お茶
		'se339' => self::$pictograms['d266'], // パン
		'se33a' => '[ソフトクリーム]', // ソフトクリーム
		'se33b' => '[ポテト]', // フライドポテト
		'se33c' => '[団子]', // 串団子 
		'se33d' => '[お煎餅]', // せんべい
		'se33e' => self::$pictograms['d265'], // ご飯
		'se33f' => '[スパゲティ]', // スパゲティ
		'se340' => self::$pictograms['d265'], // ラーメン
		'se341' => '[カレー]', // カレーライス
		'se342' => self::$pictograms['d262'], // おにぎり
		'se343' => '[おでん]', // おでん
		'se344' => '[寿司]', // 寿司
		'se345' => self::$pictograms['d258'], // りんご
		'se346' => '[蜜柑]', // みかん
		'se347' => '[苺]', // いちご
		'se348' => '[西瓜]', // すいか
		'se349' => '[トマト]', // トマト
		'se34a' => '[茄子]', // なす
		'se34b' => self::$pictograms['d073'], // バースデーケーキ
		'se34c' => '[駅弁]', // 駅弁
		'se34d' => '[鍋]', // ナベ
		'se401' => self::$pictograms['d224'], // あせり (顔)
		'se402' => self::$pictograms['d233'], // ほそくんでいる (顔)
		'se403' => self::$pictograms['d221'], // ひたすらごめんなさい (顔)
		'se404' => self::$pictograms['d272'], // えっへん (顔)
		'se405' => self::$pictograms['d230'], // ウィンク (顔)
		'se406' => self::$pictograms['d232'], // わさびがきいた (顔)
		'se407' => self::$pictograms['d143'], // 目がぐるぐる (顔)
		'se408' => self::$pictograms['d157'], // 鼻ちょうちん (顔)
		'se409' => self::$pictograms['d229'], // あっかんべー (顔)
		'se40a' => self::$pictograms['d222'], // 酔っ払い (顔)
		'se40b' => self::$pictograms['d276'], // ゲロゲロ (顔)
		'se40c' => '(#□#)', // マスクをつけた顔
		'se40d' => self::$pictograms['d231'], // 顔があかくなる
		'se40e' => self::$pictograms['d226'], // しらけ顔
		'se40f' => self::$pictograms['d224'], // 冷や汗 (顔)
		'se410' => self::$pictograms['d144'], // びっくり (顔)
		'se411' => self::$pictograms['d234'], // 泣き (顔)
		'se412' => self::$pictograms['d234'], // 泣いたり笑ったり (顔)
		'se413' => self::$pictograms['d235'], // 可愛く泣いてる人
		'se414' => self::$pictograms['d140'], // にこにこ (顔)
		'se415' => self::$pictograms['d231'], // あははと笑う (顔)
		'se416' => self::$pictograms['d225'], // めちゃめちゃ怒っている (顔)
		'se417' => self::$pictograms['d227'], // KISS:動く口
		'se418' => self::$pictograms['d227'], // 投げKISS
		'se419' => self::$pictograms['d084'], // 目
		'se41a' => '[鼻]', // 鼻
		'se41b' => self::$pictograms['d085'], // 耳
		'se41c' => self::$pictograms['d149'], // 口
		'se41d' => '[ゴメン]', // ごめんなさい (合わせた手)
		'se41e' => self::$pictograms['d088'], // バイバイ (手を振る)
		'se41f' => self::$pictograms['d088'] . self::$pictograms['d088'],// 拍手
		'se420' => self::$pictograms['d135'], // OK (指で丸サイン)
		'se421' => self::$pictograms['d156'], // Booing (親指を下)
		'se422' => self::$pictograms['d088'], // おっは～
		'se423' => self::$pictograms['d236'], // × (両腕をクロス)
		'se424' => self::$pictograms['d135'], // ○ (両腕を頭に)
		'se425' => self::$pictograms['d137'], // 手をつないでいる
		'se426' => 'm(__)m', // 土下座
		'se427' => '＼(^o^)／', // バンザイ
		'se428' => self::$pictograms['d170'] . self::$pictograms['d170'], // 人と人が歩いている
		'se429' => '[バニー]', // ラインダンス (バニーガール)
		'se42a' => self::$pictograms['d027'], // バスケットボール
		'se42b' => '[アメフト]', // フットボール
		'se42c' => '[ビリヤード]', // ビリヤード
		'se42d' => self::$pictograms['d252'], // 水泳
		'se42e' => self::$pictograms['d034'], // RV車
		'se42f' => '[トラック]', // トラック
		'se430' => '[消防車]', // 消防車
		'se431' => '[救急車]', // 救急車
		'se432' => '[パトカー]', // パトカー
		'se433' => '[ローラーコースター]',// ジェットコースター
		'se434' => self::$pictograms['d031'], // 地下鉄
		'se435' => self::$pictograms['d032'], // 新幹線(700系)
		'se436' => '[門松]', // 門松
		'se437' => '[チョコ]', // チョコ
		'se438' => '[お雛様]', // お雛様
		'se439' => '[卒業式]', // 卒業式
		'se43a' => '[ランドセル]', // ランドセル
		'se43b' => '[鯉のぼり]', // 鯉のぼり
		'se43c' => self::$pictograms['d008'], // とじかさ
		'se43d' => '[結婚式]', // 結婚式
		'se43e' => self::$pictograms['d252'], // 波がザーン
		'se43f' => '[かき氷]', // かき氷
		'se440' => '[線香花火]', // 線香花火
		'se441' => '[貝]', // 貝
		'se442' => '[風鈴]', // 風鈴
		'se443' => self::$pictograms['d006'], // 台風
		'se444' => '[稲穂]', // 稲穂
		'se445' => '[ハロウィン]', // ハロウィン
		'se446' => self::$pictograms['d099'], // お月見
		'se447' => self::$pictograms['d260'], // 風がビュー
		'se448' => '[サンタ]', // サンタクロース
		'se449' => self::$pictograms['d001'], // 朝日
		'se44a' => self::$pictograms['d001'], // 夕日
		'se44b' => self::$pictograms['d172'], // 流れ星
		'se44c' => '[虹]', // 虹
		'se501' => self::$pictograms['d044'] . self::$pictograms['d136'], // ラブホテル
		'se502' => self::$pictograms['d062'], // アート
		'se503' => self::$pictograms['d063'], // 演劇
		'se504' => self::$pictograms['d039'], // デパート
		'se505' => '[天守閣]', // お城 (和)
		'se506' => '[城]', // お城 (洋)
		'se507' => self::$pictograms['d058'], // 映画館
		'se508' => self::$pictograms['d039'], // 工場
		'se509' => '[東京タワー]', // 東京タワー 
		'se50a' => self::$pictograms['d039'], // 109 
		'se50b' => '[日本]', // 日本 
		'se50c' => '[アメリカ]', // アメリカ 
		'se50d' => '[フランス]', // フランス 
		'se50e' => '[ドイツ]', // ドイツ 
		'se50f' => '[イタリア]', // イタリア 
		'se510' => '[イギリス]', // イギリス 
		'se511' => '[スペイン]', // スペイン 
		'se512' => '[ロシア]', // ロシア 
		'se513' => '[中国]', // 中国 
		'se514' => '[韓国]', // 韓国 
		'se515' => '[白人]', // 白人 
		'se516' => '[中国人]', // 中国人 
		'se517' => '[インド人]', // インド人 
		'se518' => '[おじいちゃん]', // おじいちゃん
		'se519' => '[おばあちゃん]', // おばあちゃん
		'se51a' => '[赤ちゃん]', // あかちゃん
		'se51b' => '[工事人]', // 安全第一
		'se51c' => '[お姫様]', // お姫さま
		'se51d' => '[自由の女神]', // 自由の女神
		'se51e' => '[衛兵]', // 衛兵
		'se51f' => '[フラメンコ]', // フラメンコ
		'se520' => self::$pictograms['d270'], // イルカ
		'se521' => self::$pictograms['d268'], // とり
		'se522' => self::$pictograms['d270'], // 熱帯魚
		'se523' => self::$pictograms['d268'], // ひよこ
		'se524' => '[ハムスター]', // ハムスター
		'se525' => '[毛虫]', // けむし
		'se526' => '[象]', // ぞう
		'se527' => '[コアラ]', // コアラ
		'se528' => '[チンパンジー]', // チンパンジー
		'se529' => '[羊]', // ひつじ
		'se52a' => self::$pictograms['d100'], // おおかみ
		'se52b' => '[牛]', // うし
		'se52c' => '[兎]', // うさぎ
		'se52d' => '[蛇]', // へび
		'se52e' => self::$pictograms['d268'], // にわとり
		'se52f' => '[猪]', // いのしし
		'se530' => '[ラクダ]', // らくだ
		'se531' => '[蛙]', // かえる
		'se532' => '[A型]', // A型
		'se533' => '[B型]', // B型
		'se534' => '[AB型]', // AB型
		'se535' => '[O型]', // O型
		'se536' => self::$pictograms['d091'], // 足あと
		'se537' => self::$pictograms['d239'], // TM (商標)
		'se538' => 'J-', 
		'se539' => 'Sky', 
		'se53a' => '“', 
		'se53b' => '”', 
		'se53c' => '◎V', 
		'se53d' => 'odaf', 
		'se53e' => 'one', 
		'e253'  => '[指]', // 人差し指
		'e254'  => self::$pictograms['d049'], // カップル
		'e255'  => '[初心者]', // 若葉マーク
		'e256'  => '[ギター]', // ギター
		'e257'  => '[株価]', // 株価チャート
		'e258'  => self::$pictograms['d245'], // 18歳以上禁止
		'e259'  => '[麻雀]', // 麻雀牌
		'e260'  => '[コミュニティ]', // コミュニティ
		'e261'  => '[HIT]', // ヒット
		'e262'  => self::$pictograms['d076'], // 新聞
		'e263'  => '[サンタ]', // サンタクロース
		'e264'  => '[家族]', // 家族
		'e265'  => '　', // [未使用]
		'e266'  => '●', // コイン
		'e267'  => '　', // [未使用]
		'e268'  => '　', // [未使用]
		'e269'  => 'EM', // EMOBILE ロゴ (白地)
		'e270'  => 'EM', // EMOBILE ロゴ (赤地)
		'e271'  => '　', // [未使用]
		'e272'  => '　', // [未使用]
		'e273'  => '　', // [未使用]
		'e274'  => '　', // [未使用]
		'e275'  => '　', // [未使用]
		'e276'  => '　', // [未使用]
		'e277'  => '　', // [未使用]
		'e278'  => '　', // [未使用]
		'wf040' => self::$pictograms['d080'], // ハート
		'wf041' => self::$pictograms['d176'], // 時計
		'wf042' => self::$pictograms['d074'], // 電話
		'wf043' => self::$pictograms['d051'], // カップ
		'wf044' => '*', // *
		'wf045' => self::$pictograms['d250'], // 上下 (矢印)
		'wf046' => self::$pictograms['d249'], // 左右 (矢印)
		'wf047' => '(((', // 電波 (左)
		'wf048' => self::$pictograms['d001'], // 晴れ
		'wf049' => self::$pictograms['d003'], // 雨
		'wf04a' => self::$pictograms['d002'], // 曇り
		'wf04b' => self::$pictograms['d163'], // 涙
		'wf04c' => self::$pictograms['d140'], // 笑顔
		'wf04d' => self::$pictograms['d149'], // 口 (キスマーク)
		'wf04e' => self::$pictograms['d146'], // メロディ (十六分音符)
		'wf04f' => self::$pictograms['d033'], // 車
		'wf050' => self::$pictograms['d030'], // 電車
		'wf051' => self::$pictograms['d037'], // 飛行機
		'wf052' => '[バイク]'         , // バイク
		'wf053' => self::$pictograms['d038'], // 家
		'wf054' => self::$pictograms['d039'], // ビル
		'wf055' => self::$pictograms['d087'], // ピース (手)
		'wf056' => self::$pictograms['d050'], // ディナー (ナイフとフォーク)ォーク)
		'wf057' => self::$pictograms['d052'], // グラス
		'wf058' => self::$pictograms['d235'], // 泣く (顔)
		'wf059' => self::$pictograms['d256'], // チューリップ
		'wf05a' => self::$pictograms['d022'], // 野球 (バット)
		'wf05b' => self::$pictograms['d022'], // ボール
		'wf05c' => self::$pictograms['d086'], // パンチ (手)
		'wf05d' => self::$pictograms['d005'], // 雷
		'wf05e' => self::$pictograms['d141'], // 怒った顔
		'wf05f' => self::$pictograms['d053'], // ビール
		'wf060' => self::$pictograms['d076'], // ノート
		'wf061' => self::$pictograms['d214'], // ペン (鉛筆)
		'wf062' => '[ドクロ]', // ドクロ
		'wf063' => self::$pictograms['d110'], // メール
		'wf064' => self::$pictograms['d067'], // 禁煙
		'wf065' => self::$pictograms['d097'], // ベル
		'wf066' => self::$pictograms['d148'], // 花
		'wf067' => self::$pictograms['d147'], // 温泉
		'wf068' => self::$pictograms['d098'], // 月 (26日目)
		'wf069' => self::$pictograms['d121'], // 旗
		'wf06a' => '[風邪]', // マスク (顔)
		'wf06b' => self::$pictograms['d061'], // レコード
		'wf06c' => '[肉]', // 肉
		'wf06d' => self::$pictograms['d100'], // 犬
		'wf06e' => self::$pictograms['d101'], // 猫
		'wf06f' => '[猿]', // 猿
		'wf070' => '[象]', // 象
		'wf071' => '[蛸]', // たこ
		'wf072' => self::$pictograms['d265'], // ヌードル
		'wf073' => self::$pictograms['d057'], // マイク (カラオケ)
		'wf074' => self::$pictograms['d152'], // むかっ (怒り)
		'wf075' => self::$pictograms['d268'], // ひよこ
		'wf076' => self::$pictograms['d157'], // 眠り顔
		'wf077' => self::$pictograms['d051'], // コーヒー
		'wf078' => self::$pictograms['d066'], // タバコ
		'wf079' => self::$pictograms['d162'], // 汗
		'wf07a' => self::$pictograms['d262'], // おにぎり
		'wf07b' => self::$pictograms['d069'], // カバン
		'wf07c' => '[ウンチ]', // うんち
		'wf07d' => '[ネクタイ]', // ネクタイ
		'wf07e' => self::$pictograms['d203'], // シャツ
		'wf080' => '[西瓜]', // すいか
		'wf081' => '[かき氷]', // カキ氷
		'wf082' => '[水着]', // ビキニ
		'wf083' => self::$pictograms['d056'], // はさみ
		'wf084' => '[注射]', // 注射
		'wf085' => self::$pictograms['d036'], // 船 (錨)
		'wf086' => '[蛙]', // かえる
		'wf087' => self::$pictograms['d088'], // バイバイ (手)
		'wf088' => self::$pictograms['d138'], // 失恋
		'wf089' => self::$pictograms['d082'], // ダイヤ (トランプ)プ)
		'wf08a' => self::$pictograms['d083'], // クローバー (トランプ)
		'wf08b' => self::$pictograms['d081'], // スペード (トランプ)
		'wf08c' => self::$pictograms['d237'], // クリップ
		'wf08d' => self::$pictograms['d004'], // 雪だるま
		'wf08e' => self::$pictograms['d073'], // ケーキ
		'wf08f' => self::$pictograms['d258'], // りんご
		'wf090' => self::$pictograms['d072'], // プレゼント
		'wf091' => self::$pictograms['d168'], // お金 (ドル)
		'wf092' => self::$pictograms['d209'], // 出口
		'wf093' => self::$pictograms['d209'], // 入り口
		'wf094' => self::$pictograms['d170'], // おやじ
		'wf095' => self::$pictograms['d075'], // PHS
		'wf096' => '☆', // 星
		'wf097' => self::$pictograms['d065'], // チケット
		'wf098' => self::$pictograms['d139'], // 複数ハート
		'wf099' => self::$pictograms['d151'], // ひらめき
		'wf09a' => self::$pictograms['d091'], // 足跡
		'wf09b' => self::$pictograms['d140'], // 笑顔
		'wf09c' => self::$pictograms['d024'], // テニス
		'wf09d' => self::$pictograms['d058'], // 映画
		'wf09e' => self::$pictograms['d026'], // スキー
		'wf09f' => self::$pictograms['d160'], // !!
		'wf0a0' => self::$pictograms['d159'], // !?
		'wf0a1' => '?', // ?
		'wf0a2' => self::$pictograms['d156'], // 下降 (矢印)
		'wf0a3' => self::$pictograms['d145'], // 上昇 (矢印)
		'wf0a4' => self::$pictograms['d228'], // グッド (親指)
		'wf0a5' => '[力こぶ]', // 力こぶ
		'wf0a6' => '→' . self::$pictograms['d136'], // キューピット (ハートと矢)ート
		'wf0a7' => self::$pictograms['d155'], // うずまき
		'wf0a8' => self::$pictograms['d006'], // 台風
		'wf0a9' => self::$pictograms['d102'], // 海
		'wf0aa' => self::$pictograms['d252'], // サーフィン
		'wf0ab' => self::$pictograms['d253'], // 山
		'wf0ac' => self::$pictograms['d253'], // 富士山
		'wf0ad' => '[キャンプ]', // キャンプ
		'wf0ae' => self::$pictograms['d260'], // 落ち葉
		'wf0af' => self::$pictograms['d035'], // バス
		'wf0b0' => self::$pictograms['d025'], // サッカー
		'wf0b1' => '[初心者]', // 初心者
		'wf0b2' => '≪', // 巻き戻し
		'wf0b3' => '≫', // 早送り
		'wf0b4' => '[重要]', // 重要
		'wf0b5' => self::$pictograms['d245'], // 18禁
		'wf0b6' => self::$pictograms['d244'], // 注意
		'wf0b7' => self::$pictograms['d242'], // リサイクル
		'wf0b8' => '▽.i|', // 電界強度
		'wf0b9' => ')))', // 電波 (右)
		'wf0ba' => '×', // バツ
		'wf0bb' => self::$pictograms['d238'], // コピーライト
		'wf0bc' => self::$pictograms['d243'], // レジスタードトレードマーク
		'wf0bd' => '[777]', // スリーセブン
		'wf0be' => self::$pictograms['d134'], // 0 (zero)
		'wf0bf' => self::$pictograms['d125'], // 1 (one)
		'wf0c0' => self::$pictograms['d126'], // 2 (two)
		'wf0c1' => self::$pictograms['d127'], // 3 (three)
		'wf0c2' => self::$pictograms['d128'], // 4 (four)
		'wf0c3' => self::$pictograms['d129'], // 5 (five)
		'wf0c4' => self::$pictograms['d130'], // 6 (six)
		'wf0c5' => self::$pictograms['d131'], // 7 (seven)
		'wf0c6' => self::$pictograms['d132'], // 8 (eight)
		'wf0c7' => self::$pictograms['d133'], // 9 (nine)
		'wf0c8' => self::$pictograms['d009'], // 牡羊座
		'wf0c9' => self::$pictograms['d010'], // 牡牛座
		'wf0ca' => self::$pictograms['d011'], // 双子座
		'wf0cb' => self::$pictograms['d012'], // 蟹座
		'wf0cc' => self::$pictograms['d013'], // 獅子座
		'wf0cd' => self::$pictograms['d014'], // 乙女座
		'wf0ce' => self::$pictograms['d015'], // 天秤座
		'wf0cf' => self::$pictograms['d016'], // 蠍座
		'wf0d0' => '[蛇遣座]', // へびつかい座
		'wf0d1' => self::$pictograms['d017'], // 射手座
		'wf0d2' => self::$pictograms['d018'], // 山羊座
		'wf0d3' => self::$pictograms['d019'], // 水瓶座
		'wf0d4' => self::$pictograms['d020'], // 魚座
		'wf0d5' => self::$pictograms['d170'], // 地蔵
		'wf0d6' => self::$pictograms['d054'], // マクドナルド
		'wf0d7' => self::$pictograms['d054'], // モスバーガー
		'wf0d8' => '　', // [未使用]
		'wf0d9' => self::$pictograms['d054'], // ロッテリア
		'wf0da' => '　', // [未使用]
		'wf0db' => self::$pictograms['d051'], // ドトールコーヒー
		'wf0dc' => '　', // [未使用]
		'wf0dd' => '　', // [未使用]
		'wf0de' => '　', // [未使用]
		'wf0df' => '　', // [未使用]
		'wf0e0' => self::$pictograms['d050'], // もも (バーミヤン?)
		'wf0e1' => '　', // [未使用]
		'wf0e2' => '　', // [未使用]
		'wf0e3' => self::$pictograms['d050'], // びっくりドンキー
		'wf0e4' => '　', // [未使用]
		'wf0e5' => '　', // [未使用]
		'wf0e6' => '　', // [未使用]
		'wf0e7' => self::$pictograms['d045'], // ローソン
		'wf0e8' => '　', // [未使用]
		'wf0e9' => self::$pictograms['d045'], // am/pm
		'wf0ea' => '　', // [未使用]
		'wf0eb' => '　', // [未使用]
		'wf0ec' => '　', // [未使用]
		'wf0ed' => '　', // [未使用]
		'wf0ee' => '　', // [未使用]
		'wf0ef' => '　', // [未使用]
		'wf0f0' => self::$pictograms['d039'], // 西武
		'wf0f1' => '　', // [未使用]
		'wf0f2' => '　', // [未使用]
		'wf0f3' => '　', // [未使用]
		'wf0f4' => '　', // [未使用]
		'wf0f5' => '　', // [未使用]
		'wf0f6' => '　', // [未使用]
		'wf0f7' => '　', // [未使用]
		'wf0f8' => '　', // [未使用]
		'wf0f9' => '　', // [未使用]
		'wf0fa' => '　', // [未使用]
		'wf0fb' => '　', // [未使用]
		'wf0fc' => self::$pictograms['d100'], // ハチ公
		'wf140' => self::$pictograms['d170'], // モヤイ
		'wf141' => '　', // [未使用]
		'wf142' => '　', // [未使用]
		'wf143' => '　', // [未使用]
		'wf144' => '　', // [未使用]
		'wf145' => '　', // [未使用]
		'wf146' => '　', // [未使用]
		'wf147' => '　', // [未使用]
		'wf148' => self::$pictograms['d042'], // UFJ
		'wf149' => '　', // [未使用]
		'wf14a' => '　', // [未使用]
		'wf14b' => '　', // [未使用]
		'wf14c' => '　', // [未使用]
		'wf14d' => self::$pictograms['d209'], // 非常口
		'wf14e' => '　', // [未使用]
		'wf14f' => '　', // [未使用]
		'wf150' => self::$pictograms['d234'], // 泣き顔
		'wf151' => '　', // [未使用]
		'wf152' => '　', // [未使用]
		'wf153' => '　', // [未使用]
		'wf154' => '　', // [未使用]
		'wf155' => '　', // [未使用]
		'wf156' => '　', // [未使用]
		'wf157' => '　', // [未使用]
		'wf158' => '　', // [未使用]
		'wf159' => '　', // [未使用]
		'wf15a' => '　', // [未使用]
		'wf15b' => '　', // [未使用]
		'wf15c' => '　', // [未使用]
		'wf15d' => '　', // [未使用]
		'wf15e' => '　', // [未使用]
		'wf15f' => '　', // [未使用]
	);
	$translated = apply_filters('ktai_pictogram_table', $translated, __CLASS__, $this->charset);
	$translated = apply_filters('pictogram_table/ktai_style.php', $translated);
	$buffer = preg_replace(
		'!<img localsrc="([^"]+)"( alt="(' . KtaiStyle::DOUBLE_QUOTED_STRING_REGEX . ')")?[^/>]*/?>!se', // <?php /* syntax hilighting fix */
		'isset($translated["$1"]) ? $translated["$1"] : ("$3" ? "$3" : "〓")', 
		$buffer);
	$entities = array(
		'&spades;' => self::$pictograms['d081'],
		'&#9824;'  => self::$pictograms['d081'],
		'&#x2660;' => self::$pictograms['d081'],
		'&clubs;'  => self::$pictograms['d083'],
		'&#9827;'  => self::$pictograms['d083'],
		'&#x2663;' => self::$pictograms['d083'],
		'&hearts;' => self::$pictograms['d080'],
		'&#9829;'  => self::$pictograms['d080'],
		'&#x2665;' => self::$pictograms['d080'],
		'&#9825;'  => self::$pictograms['d136'], // WHITE HEART
		'&#x2661;' => self::$pictograms['d136'], // WHITE HEART
		'&diams;'  => self::$pictograms['d082'],
		'&#9830;'  => self::$pictograms['d082'],
		'&#x2666;' => self::$pictograms['d082'],
		'&#12336;' => self::$pictograms['d165'], // WAVY DASH
		'&#x3030;' => self::$pictograms['d165'], // WAVY DASH
	);
	$buffer = str_replace(array_keys($entities), $entities, $buffer);
	return parent::convert_pict($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_pre_split($buffer) {
	$buffer = preg_replace('!<img([^>]*?) src=([\'"])([^>]*?)\.png\\2!s', '<img$1 src=$2$3.gif$2', $buffer); //" syntax hilighting fix
	$buffer = preg_replace('!<a([^>]*?) href=([\'"])([^>]*?)\.png\\2!s', '<a$1 href=$2$3.gif$2', $buffer); //" syntax hilighting fix
	$buffer = preg_replace('!<(b|i|u|em|strong)>(.*?)</\\1>!s', '$2', $buffer);
	return parent::shrink_pre_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function pickup_pics($buffer) {
	$pictograms = array_flip(self::$pictograms);
	if (! $pictograms || ! function_exists('mb_regex_encoding')) {
		return $buffer;
	}
	mb_regex_encoding($this->charset);
	$replaced = mb_ereg_replace(
		"([\xf8\x40-\xf8\x5b]|[\xf8\x5d-\xf8\xfc]|[\xf9\x40-\xf9\x5b]|[\xf9\x5d-\xf9\xfc])", 
		'isset($pictograms["\1"]) ? 
		"<img localsrc=\"" . $pictograms["\1"] . "\" />" : 
		"<img localsrc=\"d\" alt=\"" . "[0x" . bin2hex("\1") . "]\" />"', 
		$buffer, 'e');
	if ($replaced) {
		$replaced = mb_ereg_replace("\xf8\x5c", '<img localsrc="d" alt="[0xf85c]" />', $replaced);
		$replaced = mb_ereg_replace("\xf9\x5c", '<img localsrc="' . $pictograms["\xf9\x5c"] . '" />', $replaced);
	}
	return $replaced ? $replaced : $buffer;
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_imode_mova class
   ================================================== */

class KtaiService_imode_mova extends KtaiService_imode {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->theme      = ks_option('ks_theme_mova');
	$this->type       = 'mova';
	$this->flat_rate  = false;
	if (preg_match('!1\.0/([-_.a-zA-Z0-9]+)(/c(\d+)(/\w+)*?(/ser(\w+))?)?!', $user_agent, $specs)) {
		$this->term_name  = $specs[1];
		$this->term_ID    = isset($specs[6]) ? $specs[6] : NULL;
		$this->cache_size = ($specs[3] > 0) ? intval($specs[3]) * 1024 : 5120;
	} else {
		$this->cache_size = 5120;
	}
	$this->textarea_size = 5000;
	$this->page_size  = 5000;
	$this->preamble   = '';
	$this->xhtml_head = '';
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
	$buffer = str_replace('&nbsp;', ' ', $buffer);
	$buffer = preg_replace('!\s*</(li|dt|dd|option)>\s*!', '', $buffer);
	$buffer = preg_replace('! ?/>!', '>', $buffer);
/*	$buffer = preg_replace('!<([-~_= a-zA-Z0-9%.,:;\'"/#*+]+?) ?/>!', '<$1>', $buffer); */
	return parent::shrink_post_split($buffer);
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_imode_FOMA class
   ================================================== */

class KtaiService_imode_FOMA extends KtaiService_imode {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->theme      = ks_option('ks_theme_foma');
	$this->type       = 'FOMA';
	$this->flat_rate  = true;
	if (preg_match('!2\.\d ([-_.a-zA-Z0-9]+)\(c(\d+)(;\w+)*?(;ser(\w+);icc(\w+))?\)!', $user_agent, $specs)) {
		$this->term_name  = $specs[1];
		$this->term_ID    = isset($specs[5]) ? $specs[5] : NULL;
		$this->usim_ID    = isset($specs[6]) ? $specs[6] : NULL;
		$this->cache_size = ($specs[2] > 0) ? intval($specs[2]) * 1024 : 102400;
	} else {
		$this->cache_size = 102400;
	}
	$this->textarea_size = 20000;
	$this->page_size  = 20000;
	$this->preamble   = '<?xml version="1.0" encoding="__CHARSET__"?>
<!DOCTYPE html PUBLIC "-//i-mode group (ja)//DTD XHTML i-XHTML(Locale/Ver.=ja/1.0) 1.0//EN" "i-xhtml_4ja_10.dtd">';// <?php /* syntax hilighting fix */
	$this->xhtml_head = '<html xmlns="http://www.w3.org/1999/xhtml">';
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
//	$buffer = str_replace('&nbsp;', ' ', $buffer);
	$buffer = $this->big_small_to_style($buffer);
	if ($this->mime_type == 'application/xhtml+xml') {
		$buffer = preg_replace('!<blink>(.*?)</blink>!s', '<span style="text-decoration:blink;">$1</span>', $buffer);
		$buffer = $this->input_to_style($buffer);
	}
	return parent::shrink_post_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
protected function big_small_to_style($buffer) {
	$buffer = str_replace(array("\375", "\376"), array('', ''), $buffer);
	$buffer = str_replace(array('<big>', '</big>'), array("\375", "\376"), $buffer, $num_replaced);
	$loop = 0;
	while (preg_match('!\\375([^\\375\\376]*?)\\376!', $buffer, $b)) {
		if ($loop++ > $num_replaced) { // infinity loop check
			break;
		}
		$html = '<span style="font-size:big;">' . $b[1] . '</span>';
		$buffer = preg_replace('!' . preg_quote($b[0], '!') . '!', $html, $buffer, 1);
	}
	$buffer = str_replace(array('<small>', '</small>'), array("\375", "\376"), $buffer, $num_replaced);
	$loop = 0;
	while (preg_match('!\\375([^\\375\\376]*?)\\376!', $buffer, $s)) {
		if ($loop++ > $num_replaced) { // infinity loop check
			break;
		}
		$html = '<span style="font-size:small;">' . $s[1] . '</span>';
		$buffer = preg_replace('!' . preg_quote($s[0], '!') . '!', $html, $buffer, 1);
	}
	return $buffer;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
protected function input_to_style($buffer) {
	if (preg_match_all('|<input ([^>]*?)/?>|', $buffer, $input, PREG_SET_ORDER)) { // <?php /* syntax hilighting fix */
		foreach ($input as $i) {
			$old_style = '';
			$style = '';
			$html = $i[0];
			$attr = $i[1];
			if (preg_match('/ style=([\'"])([^\\\\>]*?(\\\\.[^\\\\>]*?)*)\\1/s', $attr, $s)) { //"syntax highlighting fix
				$old_style = $s[2] . (substr_compare($s[2], ';', -1, 1) !== 0 ? ';' : '');
				$html = str_replace($s[0], '', $html);
			}
			if (preg_match('/ istyle=([\'"])([^\\\\>]*?(\\\\.[^\\\\>]*?)*)\\1/s', $attr, $istyle)) { //"syntax highlighting fix
				switch ($istyle[2]) {
				case 1: // Fullwidth Kana
					$style .= '-wap-input-format:&quot;*&lt;ja:h&gt;&quot;';
					break; 
				case 2: // Halfwidth Kana
					$style .= '-wap-input-format:&quot;*&lt;ja:hk&gt;&quot;';
					break; 
				case 3: // Alphabet
					$style .= '-wap-input-format:&quot;*&lt;ja:en&gt;&quot;';
					break; 
				case 4: // Numeric
					$style .= '-wap-input-format:&quot;*&lt;ja:n&gt;&quot;';
					break; 
				}
				$html = str_replace($istyle[0], '', $html);
			}
			if ($style) {
				$style = ' style="' . $old_style . $style . '"';
				$html = str_replace('<input', '<input' . $style, $html);
				$buffer = preg_replace('!' . preg_quote($i[0], '!') . '!', $html, $buffer, 1);
			}
		}
	}
	return $buffer;
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_imode_Browser2 class
   ================================================== */

class KtaiService_imode_Browser2 extends KtaiService_imode_FOMA {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->ext_css_available = true;
	$this->cookie_available = true;
	$this->available_js_version = '3.0';
	$this->preamble   = '<?xml version="1.0" encoding="__CHARSET__"?>
<!DOCTYPE html PUBLIC "-//i-mode group (ja)//DTD XHTML i-XHTML(Locale/Ver.=ja/2.3) 1.0//EN" "i-xhtml_4ja_10.dtd">';// <?php /* syntax hilighting fix */
	return;
}

// ===== End of class ====================
}
?>